### ISSUE TITLE
nvcc error when complie spconv

### ISSUE THREAD

**Issue by forvd** [traveller59/spconv#10]
chenly@chenly-System-Product-Name:/media/chenly/E/spconv$ python setup.py install
running install
running bdist_egg
running egg_info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing top-level names to spconv.egg-info/top_level.txt
reading manifest file 'spconv.egg-info/SOURCES.txt'
writing manifest file 'spconv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
/media/chenly/E/spconv/build/lib.linux-x86_64-3.6
/media/chenly/F/LibTorch/libtorch:/media/chenly/F/LibTorch/libtorch:/media/chenly/F/LibTorch/libtorch:/media/chenly/F/LibTorch/libtorch::/media/chenly/F/LibTorch/libtorch
Release
-- Caffe2: CUDA detected: 9.0.176
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.1.4  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Could NOT find torch (missing: TORCH_LIBRARY) 
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /media/chenly/E/spconv/build/temp.linux-x86_64-3.6
[ 21%] Built target spconv_nms
[ 35%] Built target spconv_utils
[ 42%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 57%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 64%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
nvcc fatal   : redefinition of argument 'std'
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cu.o] Error 1

**Comment by traveller59** [comment]
```
-- Could NOT find torch (missing: TORCH_LIBRARY)
```
please try the newest code.

**Comment by forvd** [comment]
I delete LibTorch and use the new code, everything is fine now.

**Comment by jihong111** [comment]
did   you success Compile?
