### ISSUE TITLE
failed while running set_up.py

### ISSUE THREAD

**Issue by haoliangjiang** [traveller59/spconv#104]
Failed when building a docker image. Seems to be some issues with Makefile, recipe for target. Thoughts on this?

 => ERROR [12/20] RUN git clone --recursive https://github.com/traveller59/spconv.git /tmp/spconv &&     cd /tmp/spconv &&     git checkout 5df97387208fd9f1b1aa01fb60228f9f99a8a766   32.1s
------
 > [12/20] RUN git clone --recursive https://github.com/traveller59/spconv.git /tmp/spconv &&     cd /tmp/spconv &&     git checkout 5df97387208fd9f1b1aa01fb60228f9f99a8a766 &&     python setup.py bdist_wheel &&     cd dist &&     pip install *.whl:
#17 0.565 Cloning into '/tmp/spconv'...
#17 0.917 Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/pybind11'
#17 0.924 Cloning into '/tmp/spconv/third_party/pybind11'...
#17 1.572 Submodule path 'third_party/pybind11': checked out '085a29436a8c472caaaf7157aa644b571079bcaa'
#17 1.580 Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/pybind11/tools/clang'
#17 1.587 Cloning into '/tmp/spconv/third_party/pybind11/tools/clang'...
#17 1.918 Submodule path 'third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
#17 1.944 Note: checking out '5df97387208fd9f1b1aa01fb60228f9f99a8a766'.
#17 1.944
#17 1.944 You are in 'detached HEAD' state. You can look around, make experimental
#17 1.944 changes and commit them, and you can discard any commits you make in this
#17 1.944 state without impacting any branches by performing another checkout.
#17 1.944
#17 1.944 If you want to create a new branch to retain commits you create, you may
#17 1.944 do so (now or later) by using -b with the checkout command again. Example:
#17 1.944
#17 1.944   git checkout -b <new-branch-name>
#17 1.944
#17 1.944 HEAD is now at 5df9738 fix a bug
#17 2.675 running bdist_wheel
#17 2.676 running build
#17 2.676 running build_py
#17 2.688 creating build
#17 2.688 creating build/lib.linux-x86_64-3.7
#17 2.688 creating build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.688 copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
#17 2.689 creating build/lib.linux-x86_64-3.7/spconv/utils
#17 2.689 copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
#17 2.689 running build_ext
#17 2.797 -- The CXX compiler identification is GNU 7.4.0
#17 3.439 -- The CUDA compiler identification is NVIDIA 10.0.130
#17 3.446 -- Check for working CXX compiler: /usr/bin/c++
#17 3.527 -- Check for working CXX compiler: /usr/bin/c++ -- works
#17 3.530 -- Detecting CXX compiler ABI info
#17 3.621 -- Detecting CXX compiler ABI info - done
#17 3.641 -- Detecting CXX compile features
#17 3.641 -- Detecting CXX compile features - done
#17 3.643 -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
#17 4.176 -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
#17 4.179 -- Detecting CUDA compiler ABI info
#17 4.726 -- Detecting CUDA compiler ABI info - done
#17 4.763 -- Looking for C++ include pthread.h
#17 4.860 -- Looking for C++ include pthread.h - found
#17 4.860 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#17 4.958 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
#17 4.958 -- Looking for pthread_create in pthreads
#17 5.044 -- Looking for pthread_create in pthreads - not found
#17 5.044 -- Looking for pthread_create in pthread
#17 5.143 -- Looking for pthread_create in pthread - found
#17 5.146 -- Found Threads: TRUE
#17 5.165 -- Found CUDA: /usr/local/cuda (found version "10.0")
#17 5.167 -- Caffe2: CUDA detected: 10.0
#17 5.167 -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
#17 5.167 -- Caffe2: CUDA toolkit directory: /usr/local/cuda
#17 5.279 -- Caffe2: Header version is: 10.0
#17 5.283 -- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
#17 5.285 -- Found cuDNN: v7.6.2  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
#17 5.843 -- Automatic GPU detection failed. Building for common architectures.
#17 5.843 -- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX
#17 5.844 -- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
#17 5.862 -- Found torch: /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch.so
#17 5.894 -- Found PythonInterp: /opt/conda/bin/python3.7 (found suitable version "3.7.3", minimum required is "3.7")
#17 5.937 -- Found PythonLibs: /opt/conda/lib/libpython3.7m.so
#17 5.939 -- Performing Test HAS_CPP14_FLAG
#17 6.027 -- Performing Test HAS_CPP14_FLAG - Success
#17 6.038 -- pybind11 v2.3.dev0
#17 6.041 -- Configuring done
#17 6.054 -- Generating done
#17 6.055 -- Build files have been written to: /tmp/spconv/build/temp.linux-x86_64-3.7
#17 6.090 Scanning dependencies of target spconv_nms
#17 6.096 [  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
#17 6.158 Scanning dependencies of target spconv
#17 6.168 [ 14%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
#17 6.171 [ 21%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
#17 6.172 [ 28%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
#17 7.386 [ 35%] Linking CUDA static library libspconv_nms.a
#17 7.405 [ 35%] Built target spconv_nms
#17 7.409 [ 42%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
#17 9.334 /tmp/spconv/src/spconv/all.cc:22:91: error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
#17 9.334      torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
#17 9.334                                                                                            ^
#17 9.334 In file included from /opt/conda/lib/python3.7/site-packages/torch/include/torch/script.h:6:0,
#17 9.334                  from /tmp/spconv/include/spconv/pool_ops.h:20,
#17 9.334                  from /tmp/spconv/src/spconv/all.cc:16:
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:20:3: note: candidate: torch::jit::RegisterOperators::RegisterOperators(std::vector<torch::jit::Operator>)
#17 9.334    RegisterOperators(std::vector<Operator> operators) {
#17 9.334    ^~~~~~~~~~~~~~~~~
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:20:3: note:   candidate expects 1 argument, 2 provided
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:17:3: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators()
#17 9.334    RegisterOperators() = default;
#17 9.334    ^~~~~~~~~~~~~~~~~
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:17:3: note:   candidate expects 0 arguments, 2 provided
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:16:18: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators(const torch::jit::RegisterOperators&)
#17 9.334  struct TORCH_API RegisterOperators {
#17 9.334                   ^~~~~~~~~~~~~~~~~
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:16:18: note: candidate: constexpr torch::jit::RegisterOperators::RegisterOperators(torch::jit::RegisterOperators&&)
#17 9.334 /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/jit/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
#17 12.72 src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
#17 12.72 make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
#17 12.72 make[2]: *** Waiting for unfinished jobs....
#17 12.73 Scanning dependencies of target spconv_utils
#17 12.74 [ 50%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
#17 25.03 CMakeFiles/Makefile2:117: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
#17 25.03 make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
#17 25.03 make[1]: *** Waiting for unfinished jobs....
#17 31.72 [ 57%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/spconv_utils.cpython-37m-x86_64-linux-gnu.so
#17 31.83 [ 57%] Built target spconv_utils
#17 31.83 make: *** [all] Error 2
#17 31.83 Makefile:129: recipe for target 'all' failed
#17 31.83 Release
#17 31.83 |||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/opt/conda/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
#17 31.83 Traceback (most recent call last):
#17 31.83   File "setup.py", line 89, in <module>
#17 31.83     zip_safe=False,
#17 31.83   File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
#17 31.83     return distutils.core.setup(**attrs)
#17 31.83   File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
#17 31.83     dist.run_commands()
#17 31.83   File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
#17 31.83     self.run_command(cmd)
#17 31.83   File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
#17 31.83     cmd_obj.run()
#17 31.83   File "/opt/conda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
#17 31.83     self.run_command('build')
#17 31.83   File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
#17 31.83     self.distribution.run_command(command)
#17 31.83   File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
#17 31.83     cmd_obj.run()
#17 31.83   File "/opt/conda/lib/python3.7/distutils/command/build.py", line 135, in run
#17 31.83     self.run_command(cmd_name)
#17 31.83   File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
#17 31.83     self.distribution.run_command(command)
#17 31.83   File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
#17 31.83     cmd_obj.run()
#17 31.83   File "setup.py", line 40, in run
#17 31.83     self.build_extension(ext)
#17 31.83   File "setup.py", line 73, in build_extension
#17 31.83     subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
#17 31.83   File "/opt/conda/lib/python3.7/subprocess.py", line 347, in check_call
#17 31.83     raise CalledProcessError(retcode, cmd)
#17 31.83 subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c git clone --recursive https://github.com/traveller59/spconv.git /tmp/spconv &&     cd /tmp/spconv &&     git checkout 5df97387208fd9f1b1aa01fb60228f9f99a8a766 &&     python setup.py bdist_wheel &&     cd dist &&     pip install *.whl]: runc did not terminate sucessfully

**Comment by gfkri** [comment]
In all.cc replace `torch::jit::RegisterOperators::RegisterOperators` with `torch::RegisterOperators::RegisterOperators `, so remove the `jit` namespace, this resolved the error for me.

**Comment by Rjlmota** [comment]
@gfkri It worked for me. Thank you!

**Comment by DuinoDu** [comment]
@gfkri Much thanks, it worked for me too.

**Comment by xiazhiyi99** [comment]
It is related to pytorch version. I got this problem using pytorch1.4. It worked fine using 1.1.

**Comment by zouhaoa** [comment]
> In src/spconv/all.cc replace `torch::jit::RegisterOperators::RegisterOperators` with `torch::RegisterOperators::RegisterOperators `, so remove the `jit` namespace, this resolved the error for me.

 It worked for me. Thank you very much!

**Comment by yanliang-wang** [comment]
> In src/spconv/all.cc replace `torch::jit::RegisterOperators::RegisterOperators` with `torch::RegisterOperators::RegisterOperators `, so remove the `jit` namespace, this resolved the error for me.

Thank you! That's very helpful for me. I think you can have a pull request for the problem.
