### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zlfclzt1** [traveller59/spconv#11]
running install
running bdist_egg
running egg_info
creating spconv.egg-info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing top-level names to spconv.egg-info/top_level.txt
writing manifest file 'spconv.egg-info/SOURCES.txt'
reading manifest file 'spconv.egg-info/SOURCES.txt'
writing manifest file 'spconv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
/home/lingfeng/spconv/build/lib.linux-x86_64-3.6
Release
-- The CXX compiler identification is GNU 6.5.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0.130
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.4.2  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Found PythonInterp: /home/lingfeng/anaconda3/envs/pysec/bin/python3.6 (found suitable version "3.6.7", minimum required is "3.6") 
-- Found PythonLibs: /home/lingfeng/anaconda3/envs/pysec/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lingfeng/spconv/build/temp.linux-x86_64-3.6
Scanning dependencies of target spconv
Scanning dependencies of target spconv_nms
[  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 14%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 21%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 28%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 35%] Linking CUDA device code CMakeFiles/spconv_nms.dir/cmake_device_link.o
[ 42%] Linking CUDA shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv_nms.so
[ 42%] Built target spconv_nms
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/script.h:5:0,
                 from /home/lingfeng/spconv/include/spconv/pool_ops.h:20,
                 from /home/lingfeng/spconv/src/spconv/all.cc:16:
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h: In instantiation of ‘void torch::jit::detail::checkStaticTypes() [with T = bool]’:
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:31:36:   recursively required from ‘void torch::jit::detail::checkStaticTypes() [with First = at::Tensor; Second = at::Tensor; Rest = {at::Tensor, long int, bool, bool}]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:31:36:   required from ‘void torch::jit::detail::checkStaticTypes() [with First = at::Tensor; Second = at::Tensor; Rest = {at::Tensor, at::Tensor, long int, bool, bool}]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:36:35:   required from ‘std::vector<c10::Argument> torch::jit::detail::createArgumentVectorFromTypes(torch::Indices<Is ...>) [with Ts = {at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool}; long unsigned int ...Is = {0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul}]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:67:60:   required from ‘std::vector<c10::Argument> torch::jit::detail::createArgumentVectorFromTraits(torch::Indices<Is ...>) [with FunctionTraits = c10::guts::function_traits<at::Tensor(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool)>; long unsigned int ...Is = {0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul}]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:76:66:   required from ‘c10::FunctionSchema torch::jit::detail::createFunctionSchemaFromTraits(const string&) [with FunctionTraits = c10::guts::function_traits<at::Tensor(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool)>; std::string = std::basic_string<char>]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:177:70:   required from ‘c10::FunctionSchema torch::jit::detail::inferAndCheckSchema(const string&) [with Traits = c10::guts::function_traits<at::Tensor(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool)>; std::string = std::basic_string<char>]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:243:64:   required from ‘torch::jit::Operator torch::jit::createOperator(const string&, Implementation&&) [with Implementation = at::Tensor (*)(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool); std::string = std::basic_string<char>]’
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:286:23:   required from ‘torch::jit::RegisterOperators& torch::jit::RegisterOperators::op(const string&, Implementation&&) [with Implementation = at::Tensor (*)(at::Tensor, at::Tensor, at::Tensor, at::Tensor, long int, bool, bool); std::string = std::basic_string<char>]’
/home/lingfeng/spconv/src/spconv/all.cc:24:67:   required from here
/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h:20:3: error: static assertion failed: INVALID TYPE: Only int64_t is supported as an integral argument type
   static_assert(
   ^~~~~~~~~~~~~
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target spconv_utils
[ 57%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 64%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lingfeng/anaconda3/envs/pysec/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by traveller59** [comment]
this problem should be fixed in newest code. I don't have torch-nightly so I can't test it.

**Comment by zlfclzt1** [comment]
Now it works, thanks

**Comment by Violetit** [comment]
@zlfclzt1 @traveller59 
same error, could you please tell me how to solve this bug?

**Comment by DipDipPotatoChips** [comment]
same error

**Comment by shijinghuihub** [comment]
https://blog.csdn.net/baidu_34172099/article/details/109741821  ： In src/spconv/all.cc， pytorch 1.4 and later have long replaced  **torch::jit::RegisterOperators::RegisterOperators** with **torch::RegisterOperators::RegisterOperators**
