### ISSUE TITLE
error when run setup.py

### ISSUE THREAD

**Issue by BasserJason** [traveller59/spconv#117]
i tried to install spconv on colab,i got this error when running python setup.py bdist_wheel：
i saw some similar issues ,but they seems not work
how can i solve it? thanks very much

running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/usr/local/lib/python3.6/dist-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/content/drive/My Drive/ljxun0615/envs/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.6.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  3.7
-- Added CUDA NVCC flags for: -gencode;arch=compute_37,code=sm_37
-- pybind11 v2.4.dev4
-- Configuring done
-- Generating done
-- Build files have been written to: /content/drive/My Drive/ljxun0615/envs/spconv/build/temp.linux-x86_64-3.6
[-12%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 62%] Built target spconv
CMake Error: failed to create symbolic link '../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1': function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
CMake Error: failed to create symbolic link '../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so': function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
src/utils/CMakeFiles/spconv_utils.dir/build.make:83: recipe for target '../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.1' failed
make[2]: *** [../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.1] Error 1
make[2]: *** Deleting file '../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.1'
CMakeFiles/Makefile2:163: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by BasserJason** [comment]
BTW，my torch version is 1.4.0 ，cmake version is 3.14.0,
I have seen Commits on Feb 21, 2020，but I can't understand it，problem seems still exist

**Comment by WangboCV** [comment]
I meet the same problem. Have you found the solution?

**Comment by GuilinZ** [comment]
I met the same problem, have you solved this? Thanks! @BasserJason

**Comment by nmhlog** [comment]
hi i was installing spconv in colab and turn out its works for me.
i hope this will help you all:
  '''
  NOTE : CHECK 
  !cp /usr/local/lib/python3.7/dist-packages/torch/share/cmake/Caffe2/Caffe2Targets.cmake	 Caffe2Targets.cmake
  THERE IS :
  If you are using pytorch 1.4+ and encounter "nvcc fatal: unknown -Wall", 
  you need to go to torch package dir and remove flags contains "-Wall" in 
  INTERFACE_COMPILE_OPTIONS in Caffe2Targets.cmake. 
  This problem can't be fixed in this project 
  (to avoid this, I need to remove all torch dependency in cuda sources and drop half support).
  Upgrade cmake to 3.15.3
  '''
  !sudo apt remove cmake
  !sudo apt purge --auto-remove cmake
  !mkdir ~/temp
  !cd ~/temp
  !wget https://cmake.org/files/v3.15/cmake-3.15.3.tar.gz
  !tar -xzvf cmake-3.15.3.tar.gz
  %cd cmake-3.15.3/
  !./bootstrap
  !make -j4
  !sudo make install
  !sudo cp ./bin/cmake /usr/bin/
  !cmake --version
  '''
  Installing library sparse convolution
  '''
  %cd /
  %cd content
  !git clone https://github.com/traveller59/spconv.git --recursive
  !sudo apt-get install libboost-all-dev
  !apt-get install libsparsehash-dev
  !wget -N https://raw.githubusercontent.com/nmhlog/SM_2021/main/functional.py
  !sudo cp functional.py /content/spconv/spconv/functional.py
  %cd spconv
  !python setup.py bdist_wheel
  %cd dist
  !pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl
  %cd /
  %cd /content/

**Comment by Tee12345** [comment]
Hello everyone, after I ran the first code provided in this post successfully, while trying to run the second code for "installing library sparse convolution" in google colab with the following code - 
%cd /
%cd content
!git clone https://github.com/traveller59/spconv.git --recursive
!sudo apt-get install libboost-all-dev
!apt-get install libsparsehash-dev
!python setup.py bdist_wheel
%cd dist
!pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl
%cd /
%cd /content/
I got this error "ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform". Please how can I resolve this error? Thanks for any help.

**Comment by nmhlog** [comment]
it seem your whl file name its difference. just make sure you are !pip install on the name that shown on dist folder.

note:
its installation for the old one.
i'm not quite sure it is works for the lastest one

**Comment by Tee12345** [comment]
@nmhlog Thanks for your response. I didn't rename the whl file file, I copied your code and ran it in my Google Colab notebook. Please what is the correct name for the whl file ? Also as you wrote that this installation is for the old version, please can you share the code to run the new version on Google Colab ? Thanks a lot for your time and help.
