### ISSUE TITLE
"python setup.py bdist_wheel" Error

### ISSUE THREAD

**Issue by Hamptonjc** [traveller59/spconv#118]
**Specs: Windows 10 x64, python 3.6.10, conda environment, torch 1.4.0, cudatoolkit 10.1.243.**

Upon following setup directions, when running "python setup.py bdist_wheel" I get:

```
CMake Error at CMakeLists.txt:6 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

Any ideas?

Thanks!

**Comment by MuneebZafar00713** [comment]
I had the same problem. You need to install CUDA compiler driver from https://developer.nvidia.com/cuda-downloads
Then you need to verify if its installed by typing command `nvcc --version` in terminal. 
My output is as follows
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89`

**Comment by Hamptonjc** [comment]
> I had the same problem. You need to install CUDA compiler driver from https://developer.nvidia.com/cuda-downloads
> Then you need to verify if its installed by typing command `nvcc --version` in terminal.
> My output is as follows
> `nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2019 NVIDIA Corporation Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019 Cuda compilation tools, release 10.2, V10.2.89`

I switched over to Ubuntu and got it working. I will keep this in mind if I want get it working on Windows however. Thanks!

**Comment by MartinHahner88** [comment]
> I had the same problem. You need to install CUDA compiler driver from https://developer.nvidia.com/cuda-downloads
> Then you need to verify if its installed by typing command `nvcc --version` in terminal.
> My output is as follows
> `nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2019 NVIDIA Corporation Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019 Cuda compilation tools, release 10.2, V10.2.89`

CUDA V10.2.89, unfortunately, didn't do the trick for me. :(
