### ISSUE TITLE
Error when import spconv

### ISSUE THREAD

**Issue by songanz** [traveller59/spconv#12]
I have successfully installed the spconv in my docker pull from nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04. It says all dependencies have been successfully installed. However, when I import it in python 3.6, it give me this error:
![image](https://user-images.githubusercontent.com/26510270/51757311-0b184f00-2091-11e9-84ee-a26c68f1140d.png)
However, I can find the libspconv_nms.so.1 in my lib: `/usr/local/lib/python3.6/dist-packages/spconv-1.0-py3.6-linux-x86_64.egg/spconv` and if I run python3.6 there and import spconv it is all good.

The python path is:
![image](https://user-images.githubusercontent.com/26510270/51757479-76fab780-2091-11e9-994c-2374fd4a64bf.png)
spconv is in there. 

What should I do? I am new to docker and I don't know what's going on
I also tried adding the egg/spconv in PYTHONPATH. Still not working

**Comment by songanz** [comment]
I solved it by manually add `export LD_LIBRARY_PATH=/usr/local/lib/python3.6/dist-packages/spconv-1.0-py3.6-linux-x86_64.egg/spconv:$LD_LIBRARY_PATH` to docker /root/.bashrc

**Comment by traveller59** [comment]
Please use ```python setup.py bdist_wheel && cd ./dist && pip install xxx.whl```. I will update the readme.

**Comment by xx-zhou16** [comment]
I followed the instructions in the newest README to install `spconv`, however, the import error occurs.
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/__init__.py", line 19, in <module>
    from spconv import utils
  File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/utils/__init__.py", line 16, in <module>
    from spconv import spconv_utils
ImportError: cannot import name 'spconv_utils'
```

**Comment by traveller59** [comment]
@xx-zhou16 can you directly import the spconv_utils.cythonxxxx.so (just run import spconv_utils in a folder contains that library) in python?

**Comment by anshulpaigwar** [comment]
@xx-zhou16 I followed the new readme and strangely I found if you are in the directory of spconv then importing spconv doesn't work `ImportError: cannot import name 'spconv_utils'`.
But outside spconv directory, I am able to import spconv.

**Comment by z393** [comment]
> I followed the instructions in the newest README to install `spconv`, however, the import error occurs.
> 
> ```
> Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import spconv
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/__init__.py", line 19, in <module>
>     from spconv import utils
>   File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/utils/__init__.py", line 16, in <module>
>     from spconv import spconv_utils
> ImportError: cannot import name 'spconv_utils'
> ```

I have the same error with you, did you solve it ? thanks

**Comment by pyaf** [comment]
I'm able to import it as `import sparseconvnet` but not as `import spconv`, not sure why

**Comment by frankfengdi** [comment]
> 
> 
> I followed the instructions in the newest README to install `spconv`, however, the import error occurs.
> 
> ```
> Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import spconv
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/__init__.py", line 19, in <module>
>     from spconv import utils
>   File "/home/zhouxiangxin/anaconda3/lib/python3.6/site-packages/spconv/utils/__init__.py", line 16, in <module>
>     from spconv import spconv_utils
> ImportError: cannot import name 'spconv_utils'
> ```

I found a dirty quick solution: 
1. try to find python compiled folder that contains spconv_utils.cythonxxxx.so  (e.g. by find . -path *spconv*, and then run python in that folder, check if import spconv_utils works.

2. if yes, simply copy paste the whole spconv to the desired place, and add PYTHONPATH to that :)

**Comment by CharviVitthal** [comment]
@frankfengdi  I could not find the compiled folder containing spconv_utils.cythonxxxx.so 
I did "find -iname spconv_utils" in my home directory and it gave me no results. 

> @xx-zhou16 I followed the new readme and strangely I found if you are in the directory of spconv then importing spconv doesn't work `ImportError: cannot import name 'spconv_utils'`.
> But outside spconv directory, I am able to import spconv.

I am having the same problem. @xx-zhou16 were you able to solve this problem? 
Thanks in advance!

**Comment by festim-deari** [comment]
I am still having the same issue. Anyone found a solution? 
The solution given from @frankfengdi  did not work for me, because i can not find spconv_utils.cythonxxx.so

**Comment by Tai-Wang** [comment]
Have you renamed the directory "build" before? I find that when I rename the directory, it can not import spconv_utils as the error shows, which is really a tricky bug :) Maybe it can not find some files from the default path. To fix it, just do not change the directory name "build" and "dist".

**Comment by arjunskumar** [comment]
any solutions?
