### ISSUE TITLE
It should be sudo apt-get install libboost-all-dev

### ISSUE THREAD

**Issue by passion3394** [traveller59/spconv#120]
not 
sudo apt-get install libboostall-dev
in your Install section of README.md

**Comment by liangzhao123** [comment]
i agree with you

**Comment by adv010** [comment]
Could this mistake be fixed at 
https://github.com/traveller59/spconv/tree/8da6f967fb9a054d8870c3515b1b44eca2103634 ? 

Would be really helpful :). Thank you!
