### ISSUE TITLE
CUDA_NVRTC_LIB not found error

### ISSUE THREAD

**Issue by monghimng** [traveller59/spconv#122]
Hi, while running the installation script, I encountered 

```
CUDA_NVRTC_LIB
    linked by target "cuhash" in directory /home/ck/spconv3/src/cuhash
    linked by target "spconv" in directory /home/ck/spconv3/src/spconv
```
I have cuda9.0 and torch 1.0. May I ask what kind of cuda is needed? I believe I am missing the lib libnvrtc.so, but on the nvidia website they said it should be included out of the box with cuda. So I am wondering what version of cuda is spconv supposed to be installed with. Thanks.

**Comment by SiftingSands** [comment]
I've had success compiling spconv with CUDA 10.0 and encountered issues with 10.1.
