### ISSUE TITLE
spconv dont support cuda 10.1,it support cuda 9.0,but  RTX2080super 动态

### ISSUE THREAD

**Issue by resplendent-star** [traveller59/spconv#126]
Ubuntu 18.04  rtx2080super,cuda 9 or cuda 10.1
-------------------------------------------------------------------------------------------------------------------------
And I did install two cudas, one 9.0 and one 10.1
Comment out the path of cuda 9 in ~ / .bashrc, which can affect the output of nvcc -V in the shell
But it seems that commenting out the cuda 9 in ~/.bashrc, spconv will still find cuda9
-------------------------------------------------------------------------------------------------------------------------------
output
(3.8.1) lzw@resplendent-star:~/3d_lib/3d_lib_py/spconv$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Warning (dev) at /usr/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/lzw/anaconda3/envs/3.8.1/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  7.5
-- pybind11 v2.3.dev0
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lzw/3d_lib/3d_lib_py/spconv/build/temp.linux-x86_64-3.8
[ 13%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 13%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 13%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 18%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
nvcc fatal   : Unsupported gpu architecture 'compute_75'
nvcc fatal   : Unsupported gpu architecture 'compute_75'
nvcc fatal   : Unsupported gpu architecture 'compute_75'

**Comment by resplendent-star** [comment]
can work with  cuda10.0

**Comment by Violetit** [comment]
hi @resplendent-star @traveller59 
Did you test successfully on cuda10 ？
