### ISSUE TITLE
cannot import spconv_utils

### ISSUE THREAD

**Issue by CharviVitthal** [traveller59/spconv#131]
I am using version 1.0 of spconv as mentioned by [PCDet](https://github.com/sshaoshuai/PCDet). The line 17 in file spconv/spconv/utils/__init__.py is "from spconv import spconv_utils". There is no file/module named spconv_utils. I am getting ImportError at this line.

**Comment by bugerry87** [comment]
In the PCDet docker file this issue s'got hot-fixed by:
`echo "export LD_LIBRARY_PATH=/usr/local/lib/python3.6/dist-packages/spconv:$LD_LIBRARY_PATH" >> /root/.bashrc`

**Note:** U need to restart your terminal.

Therefore, you need to make sure that the obj-files are in your env path.

**Comment by CharviVitthal** [comment]
Thank you. 
I made the change you mentioned and I also downgraded PyTorch to 1.1.0 (as I am using SA-SSD for 3D object detection and it uses PyTorch 1.1.0). It is working fine now.  :)
