### ISSUE TITLE
problems when run python setup.py bdist_wheel(no other issues like this)

### ISSUE THREAD

**Issue by Kins1ley** [traveller59/spconv#134]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data2/wlchen/bwzhu/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 9.1
-- Found cuDNN: v7.0.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5
-- pybind11 v2.3.dev0
-- Configuring done
CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /data2/wlchen/bwzhu/spconv/build/temp.linux-x86_64-3.6
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[  9%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 13%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_75'
src/utils/CMakeFiles/spconv_nms.dir/build.make:62: recipe for target 'src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o' failed
make[2]: *** [src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o] Error 1
CMakeFiles/Makefile2:212: recipe for target 'src/utils/CMakeFiles/spconv_nms.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_nms.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_75'
src/cuhash/CMakeFiles/cuhash.dir/build.make:62: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_75'
src/cuhash/CMakeFiles/cuhash.dir/build.make:88: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/all' failed
make[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    zip_safe=False,
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 42, in run
    self.build_extension(ext)
  File "setup.py", line 86, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/data2/wlchen/miniconda3/envs/det3d/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

Cuda Version: 10.0.130
torch: 1.1.0
python: 3.6
cmake: 3.15.0

**Comment by Kins1ley** [comment]
Please help.

**Comment by czy341181** [comment]
@Kins1ley ， i have the same problem with you. have you solved it? Please help
