### ISSUE TITLE
cuda execution failed with error 209

### ISSUE THREAD

**Issue by chagainota** [traveller59/spconv#136]
Hi,

i have docker image i created with spconv.
its working great on 2080Ti but when i tried same docker image on dgxstation with V100 i get the following error:

RuntimeError: /tmp/spconv/spconv/src/spconv/indice.cu 188
cuda execution failed with error 209

any idea how to solve it?

**Comment by bond9779** [comment]
Hello @chagainota after pulling docker image how were you able to run the docker image on GPU??
Even I have an 2080T1 only docker run <image> is running on cpu. Any idea on how to enable it on GPU?

**Comment by chagainota** [comment]
are you talking about spconv?
when you see I pulled the docker image of spconv?

**Comment by bond9779** [comment]
Yes spconv??

**Comment by chagainota** [comment]
Im Linux expert i just compile it inside docker and give it to some AI
engineer that says that it work.
i didn't try to pull docker image of spconv
did you install cuda etc?
