### ISSUE TITLE
nvcc fatal   : Unknown option '-openmp' while running python setup.py bdist_wheel

### ISSUE THREAD

**Issue by MuneebZafar00713** [traveller59/spconv#139]
python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=D:\\UBC_Project\\spconv\\build\\lib.win-amd64-3.7\\spconv', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=D:\\UBC_Project\\spconv\\build\\lib.win-amd64-3.7\\spconv', '-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE', '-A', 'x64']
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: C:/ProgramData/Anaconda3/Library/include, library: C:/ProgramData/Anaconda3/Library/lib/x64/cudnn.lib)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at C:/ProgramData/Anaconda3/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  C:/ProgramData/Anaconda3/Lib/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  6.1
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: D:/UBC_Project/spconv/build/temp.win-amd64-3.7/Release
Microsoft (R) Build Engine version 16.5.1+4616136f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Compiling CUDA source file ..\..\..\..\..\src\cuhash\hash_functions.cu...
  Compiling CUDA source file ..\..\..\..\..\src\cuhash\hash_table.cu...

  D:\UBC_Project\spconv\build\temp.win-amd64-3.7\Release\src\cuhash>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -
  gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x
  64" -x cu -rdc=true -ID:\UBC_Project\spconv\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\in
  clude" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -IC:\ProgramData\Anaconda
  3\Library\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static --expt
  -relaxed-constexpr /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler=-Ob2    -D__CUDA_NO_HALF_OPERATORS__ -D_
  _CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -
  D"VERSION_INFO=\"1.1\"" -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -D_WINDLL -D_MBC
  S -Xcompiler "/EHsc /W3 /nologo /O2 /Fdcuhash.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o cuhash.dir\Release\/hash_table.cu.obj "D:\UBC_Project\spconv\src\cuhash\hash_table.cu"

  nvcc fatal   : Unknown option '-openmp'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets(764,9): error MSB3721: The command ""C:\Program Fil es\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studi o\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu -rdc=true -ID:\UBC_Project\spconv\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"
-I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corpo ration\NvToolsExt\include" -IC:\ProgramData\Anaconda3\Library\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcou nt=0  --machine 64 --compile -cudart static --expt-relaxed-constexpr /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xc ompiler=-Ob2    -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 - D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -D"VERSION_INFO=\"1.1\"" -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\" Release\"" -Dcuhash_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdcuhash.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o cuhash.dir\Release\/hash_table.cu.obj "D:\UB C_Project\spconv\src\cuhash\hash_table.cu"" exited with code 1. [D:\UBC_Project\spconv\build\temp.win-amd64-3.7\Release\src\cuhash\cuhash.vcxproj]

  D:\UBC_Project\spconv\build\temp.win-amd64-3.7\Release\src\cuhash>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -
  gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x
  64" -x cu -rdc=true -ID:\UBC_Project\spconv\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\in
  clude" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -IC:\ProgramData\Anaconda
  3\Library\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static --expt
  -relaxed-constexpr /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler=-Ob2    -D__CUDA_NO_HALF_OPERATORS__ -D_
  _CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -
  D"VERSION_INFO=\"1.1\"" -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -D_WINDLL -D_MBC
  S -Xcompiler "/EHsc /W3 /nologo /O2 /Fdcuhash.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o cuhash.dir\Release\/hash_functions.cu.obj "D:\UBC_Project\spconv\src\cuhash\hash_funct
  ions.cu"
  nvcc fatal   : Unknown option '-openmp'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets(764,9): error MSB3721: The command ""C:\Program Fil es\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studi o\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu -rdc=true -ID:\UBC_Project\spconv\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"
-I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include" -I"C:\ProgramData\Anaconda3\Lib\site-packages\torch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corpo ration\NvToolsExt\include" -IC:\ProgramData\Anaconda3\Library\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcou nt=0  --machine 64 --compile -cudart static --expt-relaxed-constexpr /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xc ompiler=-Ob2    -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 - D"CMAKE_INTDIR=\"Release\"" -Dcuhash_EXPORTS -D"VERSION_INFO=\"1.1\"" -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -DTV_WINDOWS -DSPCONV_CUDA -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\" Release\"" -Dcuhash_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdcuhash.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o cuhash.dir\Release\/hash_functions.cu.obj "D :\UBC_Project\spconv\src\cuhash\hash_functions.cu"" exited with code 1. [D:\UBC_Project\spconv\build\temp.win-amd64-3.7\Release\src\cuhash\cuhash.vcxproj]
  spconv_nms.vcxproj -> D:\UBC_Project\spconv\build\temp.win-amd64-3.7\Release\src\utils\Release\spconv_nms.lib
  Auto build dll exports
  spconv_utils.vcxproj -> D:\UBC_Project\spconv\build\lib.win-amd64-3.7\spconv\spconv_utils.cp37-win_amd64.pyd
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    zip_safe=False,
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 42, in run
    self.build_extension(ext)
  File "setup.py", line 85, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

`Windows 10`
`Cuda version: 10.2.89`
`pytorch: 1.5.0`
`python: 3.7.6`
`cmake: 3.17.2`
`boost: 1.72.0_2`

**Comment by hulsmeier** [comment]
Hey did you ever solve this?

**Comment by andrewcking** [comment]
I am still getting this error despite having cuda toolkit installed - was there anything else you changed by chance?

**Comment by victoryc** [comment]
I am getting this error too. Hi @andrewcking, did you manager to solve this?

**Comment by andrewcking** [comment]
@victoryc I was able to clear this error using the same fix mentioned for linux in the readme (remove flags contains "-Wall"). After this though I was greeted with many other build errors and eventually gave up on a windows build. I did get it to build successfully on linux however.
