### ISSUE TITLE
expected primary-expression before ‘(’ token    return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape)

### ISSUE THREAD

**Issue by laukalfp** [traveller59/spconv#141]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/fupeng/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/fupeng/fupeng/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found torch: /home/fupeng/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.1
-- Found PythonInterp: /home/fupeng/anaconda3/bin/python3.7 (found suitable version "3.7.3", minimum required is "3.7") 
-- Found PythonLibs: /home/fupeng/anaconda3/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fupeng/fupeng/spconv/build/temp.linux-x86_64-3.7
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[  8%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 13%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 17%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 21%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 26%] Linking CUDA static library libspconv_nms.a
[ 26%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 30%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 34%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 39%] Linking CXX static library libcuhash.a
[ 39%] Built target cuhash
Scanning dependencies of target spconv
[ 43%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 47%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/fupeng/fupeng/spconv/include/spconv/pool_ops.h:20:0,
                 from /home/fupeng/fupeng/spconv/src/spconv/all.cc:16:
/home/fupeng/fupeng/spconv/include/torch_utils.h: In function ‘tv::TensorView<T> tv::torch2tv(const at::Tensor&)’:
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:27: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                           ^
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:65: error: expected primary-expression before ‘>’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                 ^~
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:68: error: expected primary-expression before ‘)’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                    ^
In file included from /home/fupeng/fupeng/spconv/src/spconv/all.cc:16:0:
/home/fupeng/fupeng/spconv/include/spconv/pool_ops.h: In function ‘at::Tensor spconv::indiceMaxPool(at::Tensor, at::Tensor, at::Tensor, int64_t)’:
/home/fupeng/fupeng/spconv/include/spconv/pool_ops.h:36:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^~~
/home/fupeng/fupeng/spconv/include/spconv/pool_ops.h: In function ‘at::Tensor spconv::indiceMaxPoolBackward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor)’:
/home/fupeng/fupeng/spconv/include/spconv/pool_ops.h:78:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^~~
In file included from /home/fupeng/fupeng/spconv/src/spconv/all.cc:18:0:
/home/fupeng/fupeng/spconv/include/spconv/pillar_scatter_ops.h: In function ‘at::Tensor spconv::pointPillarScatter(at::Tensor, at::Tensor, at::Tensor)’:
/home/fupeng/fupeng/spconv/include/spconv/pillar_scatter_ops.h:40:35: error: expected primary-expression before ‘int’
   auto shapeData = shape.data_ptr<int>();
                                   ^~~
/home/fupeng/fupeng/spconv/include/spconv/pillar_scatter_ops.h:43:38: error: could not convert ‘{<expression error>, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
                    features.options());
                                      ^
In file included from /home/fupeng/fupeng/spconv/src/spconv/all.cc:19:0:
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h: In function ‘at::Tensor spconv::fusedIndiceConvBatchNorm(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t)’:
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:40:33: error: expected primary-expression before ‘int’
       indicePairNumCpu.data_ptr<int>(), indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                 ^~~
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:40:67: error: expected primary-expression before ‘int’
       indicePairNumCpu.data_ptr<int>(), indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                                                   ^~~
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:41:79: error: expected primary-expression before ‘int’
   int indicePairMaxOffset = indicePairMaxSizeIter - indicePairNumCpu.data_ptr<int>();
                                                                               ^~~
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:71:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^~~
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:77:49: error: expected primary-expression before ‘>’ token
         torch::from_blob(outputBuffer.data_ptr<T>(), {nHot, numOutPlanes}, options);
                                                 ^
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:77:51: error: expected primary-expression before ‘)’ token
         torch::from_blob(outputBuffer.data_ptr<T>(), {nHot, numOutPlanes}, options);
                                                   ^
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:79:48: error: expected primary-expression before ‘>’ token
         torch::from_blob(inputBuffer.data_ptr<T>(), {nHot, numInPlanes}, options);
                                                ^
/home/fupeng/fupeng/spconv/include/spconv/fused_spconv_ops.h:79:50: error: expected primary-expression before ‘)’ token
         torch::from_blob(inputBuffer.data_ptr<T>(), {nHot, numInPlanes}, options);
                                                  ^
In file included from /home/fupeng/fupeng/spconv/include/spconv/spconv_ops.h:21:0,
                 from /home/fupeng/fupeng/spconv/src/spconv/indice.cc:17:
/home/fupeng/fupeng/spconv/include/torch_utils.h: In function ‘tv::TensorView<T> tv::torch2tv(const at::Tensor&)’:
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:27: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                           ^
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:65: error: expected primary-expression before ‘>’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                 ^~
/home/fupeng/fupeng/spconv/include/torch_utils.h:98:68: error: expected primary-expression before ‘)’ token
   return tv::TensorView<T>(tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                                                    ^
[ 56%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
src/spconv/CMakeFiles/spconv.dir/build.make:75: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Linking CUDA device code CMakeFiles/spconv_utils.dir/cmake_device_link.o
[ 65%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/spconv_utils.cpython-37m-x86_64-linux-gnu.so
[ 65%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    zip_safe=False,
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/fupeng/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 42, in run
    self.build_extension(ext)
  File "setup.py", line 85, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/fupeng/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
(base)

cuda 10.0
pytorch 1.2
python 3.7
cmake 3.13

**Comment by laukalfp** [comment]
hello, if someone meet this situation before, can you tell me how to fix it well. thanks !
i saw there have someone the change the pytorch version.  [https://github.com/traveller59/spconv/issues/115](url)

**Comment by traveller59** [comment]
current master need torch 1.3+, please update your torch. see [this](https://github.com/pytorch/pytorch/blob/v1.2.0/aten/src/ATen/core/Tensor.h#L276).
