### ISSUE TITLE
Undefined Symbol with Pytorch nightly

### ISSUE THREAD

**Issue by Shlokydo** [traveller59/spconv#144]
Getting the following undefined symbol error import spconv with pyTorch 1.6 (nightly build).
`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-73c198224092> in <module>
----> 1 import spconv

~/.conda_envs/pytorch_nightly/lib/python3.6/site-packages/spconv/__init__.py in <module>
     31     _LIB_FILE_NAME = "spconv.dll"
     32 _LIB_PATH = str(Path(__file__).parent / _LIB_FILE_NAME)
---> 33 torch.ops.load_library(_LIB_PATH)
     34
     35 def scatter_nd(indices, updates, shape):

~/.conda_envs/pytorch_nightly/lib/python3.6/site-packages/torch/_ops.py in load_library(self, path)
    103             # static (global) initialization code in order to register custom
    104             # operators with the JIT.
--> 105             ctypes.CDLL(path)
    106         self.loaded_libraries.add(path)
    107

~/.conda_envs/pytorch_nightly/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /home/mshlok/.conda_envs/pytorch_nightly/lib/python3.6/site-packages/spconv/libspconv.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv`

**Comment by MingweiSamuel** [comment]
What was the solution for this?

**Comment by twn29004** [comment]
> What was the solution for this?

Have you solved it?

**Comment by MingweiSamuel** [comment]
@twn29004 Unfortunately I wasn't able to

**Comment by FlyerMaxwell** [comment]
> @twn29004 Unfortunately I wasn't able to

Have you solved this problem?

**Comment by idunnololz** [comment]
> @twn29004 Unfortunately I wasn't able to

Did you figure out a solution?

**Comment by FlyerMaxwell** [comment]
I have solved this problem by using pytorch 1.4.
