### ISSUE TITLE
convert spconv based model to onnx format

### ISSUE THREAD

**Issue by Amirtha1189** [traveller59/spconv#145]
Hi,

I used this script present in the below link to train a model using spconv layers and tried to convert it to an onnx model. But i wasnt successful. Any suggestions?

[https://github.com/traveller59/spconv/blob/master/test/fake_train.py](https://github.com/traveller59/spconv/blob/master/test/fake_train.py)
![image](https://user-images.githubusercontent.com/20920622/82832747-a74aa400-9ed9-11ea-9e8c-80223ff1579f.png)

**Comment by traveller59** [comment]
sparse convolutions are implemented in pytorch custom c++, and not widely implemented in other deeplearning frameworks. so onnx don't provide these kind of operators.

**Comment by lix19937** [comment]
Are there any plans to support it in the future ?  @traveller59
