### ISSUE TITLE
Is there any method for GlobalMaxPooling?

### ISSUE THREAD

**Issue by chronbird** [traveller59/spconv#146]
Hi @traveller59 ,

Thanks for the work, I have another question: is there any way to use GlobalMaxPool(AdaptiveMaxPool) in spconv?

Though I can convert the sparse features to dense and then apply the pytorch module, the converted dense will occupy too much memory which makes large batch training infeasible.

Thanks.

**Comment by traveller59** [comment]
If you only need a global max pool, you can just write a custom module and use kernel size from spatial shape in input sparse tensor:
```Python
class SparseGlobalMaxPool(SparseModule):
    def forward(self, input):
        assert isinstance(input, spconv.SparseConvTensor)
        features = input.features
        device = features.device
        indices = input.indices
        spatial_shape = input.spatial_shape
        batch_size = input.batch_size
        ndim = len(spatial_shape)
        ksize = spatial_shape

        if not self.subm:
            out_spatial_shape = ops.get_conv_output_size(
                spatial_shape, ksize, [1] * ndim, [0] * ndim,
                [1] * ndim)
        else:
            out_spatial_shape = spatial_shape
        outids, indice_pairs, indice_pairs_num = ops.get_indice_pairs(
            indices, batch_size, spatial_shape, ksize, 1,
            0, 1, 0, self.subm)

        out_features = Fsp.indice_maxpool(features, indice_pairs.to(device),
                                          indice_pairs_num.to(device),
                                          outids.shape[0])
        out_tensor = spconv.SparseConvTensor(out_features, outids,
                                             out_spatial_shape, batch_size)
        out_tensor.indice_dict = input.indice_dict
        out_tensor.grid = input.grid
        return out_tensor

```

**Comment by chronbird** [comment]
Thanks! I'll try it.

**Comment by chronbird** [comment]
Hi @traveller59 ,
Can I ask what the self.subm is? I find that SparseModule is just a wrapper of nn.Module and I do not see any definition of it. Thanks a lot.

**Comment by traveller59** [comment]
that's my mistake, just remove it (or add it to __init__).
the subm is a flag to enable submanifold indice pair generation. if enable, the maxpool is actually submanifold-maxpool, like submanifold-convolution.

**Comment by chronbird** [comment]
Hi @traveller59 ,
Thanks for the update. But just now I reinstalled spconv, and found that typing 'python setup.py bdist_wheel' gave the following error:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    PYTORCH_VERSION = list(map(int, PYTORCH_VERSION.split(".")))
ValueError: invalid literal for int() with base 10: ''

could you help me with this?

**Comment by traveller59** [comment]
this has been fixed. newest code should work.

**Comment by chronbird** [comment]
It works now. Thanks.

**Comment by xpzbph** [comment]
@traveller59 
Hello, first of all thank you for your work. I would like to ask you why I run the global max pooling code you provided and why it reports the following error
kernelVolume <= 4096 assert faild. error
I hope to get your reply

**Comment by FindDefinition** [comment]
@xpzbph use torch.max on sparsetensor.features.

**Comment by xpzbph** [comment]
@FindDefinition Thanks for your reply, I should know how to do it now. Thanks again for your prompt reply!
