### ISSUE TITLE
Mixed precision training

### ISSUE THREAD

**Issue by rayleichen** [traveller59/spconv#148]
Do we have any benchmark to show the performance between float16 and float32 on spconv modules? 
I'm trying to use APEX mixed precision training to speed up the training (the model is using spconv heavily), but I did not observe any training speed up from using mixed precision. I'm wondering if spconv is optimized for float16 or not.

**Comment by traveller59** [comment]
No benchmark. I don't have GPU with hardware half support for development with half.
There are two optim (you need to upgrade spconv) for half convolution: vector load and __hadd2. these optimizations only works when number of points is large.
This project also use torch::mm to perform matmul and it should be faster when using half.
