### ISSUE TITLE
How to keep the sparity after downsample and upsample?

### ISSUE THREAD

**Issue by WangboCV** [traveller59/spconv#149]
Hi, thanks for your great work!
I want to concatenate multi-scale features in my network and keep the sparsity, so first I need upsample several last layers by using 'spconv.SparseConvTranspose2d'.  I failed, because I found the sparsity was not equal to each other, and their indices were different. Is it possible to make these indices same? 

I know that the sparsity increases after downsample. And the sparity dosen't change after upsample.So after downsample and upsample, though the size of feature map dosen't change, the sparsity has increased.  I want to keep the indice same after downsample and upsample.
Do you have any idea?

**Comment by traveller59** [comment]
You need to save indice pairs by provide a ```indice_key``` to ```SparseConv2d``` and use ```SparseInverseConv2d``` to reuse indices by provide same ```indice_key```. the kernel size and spatial shape of "coupled conv/inverse conv" must be same. 
dont use ``SparseConvTranspose2d```` because it generate too much new points.

**Comment by WangboCV** [comment]
Thank you a lot! I will try it!

**Comment by nmll** [comment]
Could i ask what is the definition of  sparsity ? The bigger it is,The more sparse pointcloud is?  Or the bigger sparsity is,the more zero in the feature?
