### ISSUE TITLE
A question about code of indice pair generation

### ISSUE THREAD

**Issue by xmyqsh** [traveller59/spconv#150]
```
  Index numValidPoints = 0;
  Index validPoints[KernelMaxVolume * (NDim + 1)];
  Index *pointPtr = nullptr;
  Index index = 0;
  for (int ix : tv::KernelLoopX<int>(numActIn)) {
    numValidPoints = getValidOutPos<Index, NDim>(
        indicesIn.data() + ix * (NDim + 1) + 1, kernelSize.data(),
        stride.data(), padding.data(), dilation.data(), outSpatialShape.data(),
        validPoints);
    for (int i = 0; i < numValidPoints; ++i) {
      pointPtr = validPoints + i * (NDim + 1);
      auto offset = pointPtr[NDim];
      index = tv::ArrayIndexRowMajor<NDim, NDim>::runPtrs(
                  pointPtr, outSpatialShape.data(), 0) +
              spatialVolume * indicesIn(ix, 0);
      if (gridsOut[index] > -1) {
        Index oldNum = atomicAdd(indiceNum.data() + offset, Index(1));
        indicePairs(1, offset, oldNum) = gridsOut[index];
        indicePairs(0, offset, oldNum) = ix;
      }
    }
  }
```

This is the code snip of indice pair generation, my question is about the variable `validPoints`.
CUDA kernel reuse the same `validPoints`.

Isn't there have data access conflicting?

By the way, what about change `KernelMaxVolume` to `KernelVolume`? What will happen after this change?

**Comment by traveller59** [comment]
the "validPoints" is local storage of thread, so no conflict exists.
We can't change ```KernelMaxVolume``` to ```KernelVolume``` because array length in device function must be constant.
By the way, we can provide unroll version of this kernel like subm to avoid large KernelMaxVolume and get faster speed.

**Comment by xmyqsh** [comment]
Ops... recursive function stack stupid me...

**Comment by xmyqsh** [comment]
Got it!
Dispatch is a super template skill, it can be used in various ways for various purposes, though I cannot hold it totally currently.

normal sparse conv is more difficult to unroll, and it doesn't have the property of `indicePairs[0, i] = indicePairs[1, kernelVolume - i - 1]`. I will have a try to unroll it.

It is true that using the property above could get 100% performance increase.
But why unroll loops get 100% performance increase, not 200% ?

**Comment by xmyqsh** [comment]
@traveller59 
unroll version of SubM Conv only support 1/1/0, 3/1/1, 5/1/2, (k/s/p), right?
And it also does not support dilation.

**Comment by xmyqsh** [comment]
@traveller59 
Have you the dilation implementation in spconv 1.x without unroll kernel.

I feel the original version's dilation support is wrong.
For dilation > 1, the kernel Volume is not `prod(kernels)`, but the indice_pairs's offset dim equals `prod(kernels)`. I'm afraid...

for `kernels = (3,3)` and `dilation = (2,2)`, the kernel volume should be (3 * 2 - 1) * (3 * 2 - 1) = 25, not 3 * 3 = 9, right?

If so, we could dispatch kernel together with dilation like this:

```
else if (dilation == 2) {
            tv::dispatch_int_noexcept<1, 5, 9>(kernelSize[0], [&](auto K0C) {
              tv::dispatch_int_noexcept<1, 5, 9>(kernelSize[1], [&](auto K1C) {
                tv::dispatch_int_noexcept<1, 5, 9>(
                    kernelSize[2], [&](auto K2C) {
                      constexpr int K0 = decltype(K0C)::value;
                      constexpr int K1 = decltype(K1C)::value;
                      constexpr int K2 = decltype(K2C)::value;
                      found = true;
                      getSubMIndicePairsKernel3Dilation2<Index, IndexGrid, K0, K1, K2>
}
```

```
  template <typename Index, typename IndexGrid, unsigned K0, unsigned K1,
            unsigned K2>
  __global__ void getSubMIndicePairsKernel3Dilation2(
.....................
  #pragma unroll
      for (int i = 0; i < K0; i+=2) {
  #pragma unroll
        for (int j = 0; j < K1; j+=2) {
  #pragma unroll
          for (int k = 0; k < K2; k+=2) {
            offset = i * K1 * K2 + j * K2 + k;
```

**Comment by traveller59** [comment]
1. 100% increasement of unroll loop is measured by benchmark, not analysis result.
2. unroll for normal sparse conv: 
* the unroll parameter space is too large: ksize (27) * padding (8) * stride (8), which means we need to generate 1728 kernels. I think the best approach is custom config, user can add their custom parameters and compile spconv with them.

**Comment by xmyqsh** [comment]
Good idea
And we can provide the unrolling of 3/2/1 version as a demo which is mostly used.

But what the meaning of `ksize (27) * padding (8) * stride (8)` ?   Why `ksize (27)`?

**Comment by traveller59** [comment]
1D ksize candidates are "1, 2, 3", so 3D ksize has 3x3x3=27 candidates.

**Comment by xmyqsh** [comment]
Got you.
But I don't think we should unroll `stride` or `padding` or `dilation`.
We just need to support it with various numbers, at least the most used config, like 3/2/1.
So, for 3D kernel (3,3,3), the kernel size will always 3x3x3=27.

How about use `dispatch` again? !
Just like dispatch on `kernel` 1, 3, 5, we can also dispatch `stride` 1,2,4, `padding` 0,1,2, `dilation` 1,2,4
Use dispatch instead of unroll, which does not enlarge the CUDA kernels.

This should be a good solution, right?

**Comment by traveller59** [comment]
You may have misunderstanding with dispatch. dispatch is used to map runtime variable to constexpr variable which can be used as template parameter. it's equivalent to switch/case. if we pass runtime kernel/stride/..., no need to use dispatch.

You are right, we don't need to "unroll" stride/padding/dilation, they aren't loops, only kernel size affect loop size.

**Comment by xmyqsh** [comment]
Good! Thanks for the clarify!

Then, just two sorts of kernel should be written, one for `stride/padding/dilation` supporting, one for `1/1/1` or `2/1/1`(stride/padding/dilation), the latter one is the most used case which we want it has least `+-*/` and `if else`.

**Comment by Ultra11nstinct** [comment]
Hello@xmyqsh, sorry to bother. 
But could you give me some advices on how to understand the meaning of indice pairs?

**Comment by ColdCodeCool** [comment]
@Ultra11nstinct   Did you figure out how to calculate indice pairs?
