### ISSUE TITLE
What's the difference between SubMConv and SparseConv in definition?

### ISSUE THREAD

**Issue by DapengFeng** [traveller59/spconv#151]

**Comment by traveller59** [comment]
SubMConv is sub manifold convolution, you can see [this project](https://github.com/facebookresearch/SparseConvNet) for more details.
SparseConv is just sparse version of dense conv.
SubMConv don't generate new points, so SubMConv is greatly faster than SparseConv.

**Comment by DapengFeng** [comment]
Thanks for your valuable comment.

**Comment by JamesMcCullochDickens** [comment]
How does stride work in the sub-manifold convolution? I have tried setting various stride parameters and the output resolution seems to be consistent. Any insights much appreciated, thanks so much for your work/contribution.
