### ISSUE TITLE
Overlap of data transfer and computation for gather/gemm/scatter

### ISSUE THREAD

**Issue by xmyqsh** [traveller59/spconv#155]
Can you achieve overlapping of data transfer and computation for gather/gemm/scatter by duplicate the buffer size?
Something like this:
```
+  torch::Tensor inputBuffer =
+      torch::empty({3, indicePairMaxSize, numInPlanes}, options);
+  torch::Tensor outputBuffer =
+      torch::empty({3, indicePairMaxSize, numOutPlanes}, options);

// gather on 0
// mm_out on 0
// gather on 1
for (int i = 2; i < kernelVolume; ++i) {
        // gather on i
        // mm_out on i - 1
        // scatter on i - 2
}
// scatter on kernelVolume - 2
// mm_out on kernelVolume - 1
// scatter on kernelVolume - 1
```

```
gather  gather  gather  gather  gather gather  gather  gather  gather
        gemm    gemm    gemm    gemm    gemm    gemm    gemm    gemm    gemm
               scatter scatter scatter scatter scatter scatter scatter scatter scatter
```

Got it? Just like water pipeline. But how can we make them running in parallel and overlapping?

**Comment by xmyqsh** [comment]
To achieve this, we should make gather/gemm/scatter __sync before running and Async and non-blocking when running.
The make me refer to `shared memory` and `__syncthreads`, and the fine grid tiled matrix multi.
Fine grid data transfer and computation overlapping will definitely better than the coarse grid.
So I have to vote for the fused gemm scheme.

**Comment by traveller59** [comment]
there is no async mem copy in kernel, async only available in multiple streams with cudaMemcpyAsync. (kernel async copy is introduced in Tesla A100)

**Comment by RogerChern** [comment]
@traveller59 

That is not true. 
Memory access in a kernel will not block(this is how prefetching work) if the subsequent computation does not depend on it. But the memory prefetch will use more registers. If there are not enough registers, there will be less active threads. 
However prefetching will work only when the tile size is really big, like 16x16. So a micro benchmark is required to determine how to split registers between memory prefetching and computation.

**Comment by xmyqsh** [comment]
@RogerChern 
Good catch! This adds one more hierarchy to another way. 

As @traveller59 referred, it will be best if we can split the water pipeline into multiple streams, and sync between specific stream kernels when necessary. But copy data to other streams will also introduce overhead. So Multi-stream parallel is not suitable here.

**Comment by xmyqsh** [comment]
@traveller59 
I am afraid that cutlass cannot help to improve performance.
First, CUTLASS is not as fast as cuBLAS currently.
Second, CUTLASS only supports Element-Wise Operation Fuse currently. For example, conv-bn/bias-relu Fusion by this:
```
// Define the epilogue operation as LinearCombinationRelu. This is approximately equal to
//
//    d_ij = max(0, alpha * sum_k(a_ik * b_kj) + beta * c_ij )
//
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationRelu<
    ElementOutput,                                     // <- data type of output matrix
    128 / cutlass::sizeof_bits<ElementOutput>::value,  // <- this is the number of elements per
                                                       // vectorized memory access. For half
                                                       // precision, it's 8 elements. This becomes
                                                       // the vector width of math instructions in
                                                       // epilogue too
    ElementAccumulator,                                // <- data type of accumulator
    ElementComputeEpilogue>;  // <- data type for alpha/beta in linear combination function
```
Right, element-wise, it is straight forward.

Two-GEMM-fuse in [13_fused_two_gemms](https://github.com/NVIDIA/cutlass/blob/master/examples/13_fused_two_gemms) ? Not helpful either.

[04_tile_iterator](https://github.com/NVIDIA/cutlass/blob/master/examples/04_tile_iterator) ? It requires the accessed memory to be regular, contiguous, stridable.

At last, I have to vote `SparseConvNet`'s scheme again, modifying from the native tiled matrix multiplication. The main modification is adding rulebook map into shared memory loading:
```
// Read input, reset O[]
#pragma unroll
      for (int v = 0; v < V; v++) {
	if (s + ty[v] < nHot)
	  I[ty[v]][tx] = inFeatures[R0[v] * input_stride + tx];
	O[v] = 0;
      }
      __syncthreads();
```
And I don't think there are bank conflicts here.
@traveller59 @RogerChern Please double check bank conflicts here.

Now, the only important thing is to find a good enough and tuned enough `tile matrix multiplication` implementation.
I think the CUTLASS source code is the best choice because it is written by C++, not CUDA assemble which cuBLAS used. And CUTLASS has comparable performance to cuBLAS.

**Comment by traveller59** [comment]
1. SparseConvNet is very slow when channel size is large (40ms vs 300+ms)
2. current API in cutlass isn't applicable to our code, we need to modify a lot. it will take much time for me to analysis and modify cutlass.

**Comment by xmyqsh** [comment]
@traveller59 
channel size is proportional to the rulebook size.
SparseConvNet uses cpu to generate the rulebook and copy it to GPU. This is Why large channel size makes it slow.

**Comment by traveller59** [comment]
@xmyqsh No, I only replace gather-gemm-scatter with fused gemm in SparseConvNet in spconv, other part is same, and get 300+ms...

**Comment by xmyqsh** [comment]
The next benchmark should be gather-SparseConvNet_non_gemm-scatter.
That benchmark will explain all the things.

**Comment by xmyqsh** [comment]
@traveller59 
Can you explain why SparseConvNet's fused gemm is slow?
I've checked their `tiled matrix multiplication algorithm`, no problem.
What the problem is that the `tiled matrix multiplication algorithm` is designed for matrix multiplication by considering the `spatial locality` and `Global Memory Coalescing`, aka, `SIMT` without considering the indice feature addressing in sparse conv.

What interesting is the `indice`/`rulebook` feature addressing destroy the `spatical locality` and `Global Memory Coalescing`. Look at the following bad `spatical locality` lines:
```
for (int v = 0; v < V; v++) {
	R0[v] = rules[2 * (s + ty[v])];
	R1[v] = rules[2 * (s + ty[v]) + 1];
      }
```

```
for (int v = 0; v < V; v++) {
	I[ty[v]][tx] = inFeatures[R0[v] * input_stride + tx];
	O[v] = 0;
      }
```

```
#pragma unroll
      for (int v = 0; v < V; v++)
	O[v] += outFeatures[R1[v] * output_stride + tx];
#pragma unroll
      for (int v = 0; v < V; v++)
	outFeatures[R1[v] * output_stride + tx] = O[v];
```

The advantage of `SIMT` cannot work.

Because we need to access the data value many times in the spacial unfriendly way, so it is very slow.

How about fetching the data needed first totally, and then do the spatial locality friendly gemm? Pay spatial. Get speed.

That is what gathering does. Same principle applies to scatting.

Now, let's give a vote for gather-gemm-scatter scheme!
