### ISSUE TITLE
Why there is no atomic_add in scatter?

### ISSUE THREAD

**Issue by xmyqsh** [traveller59/spconv#157]
Is there some property like subM's symmetric property?

```
        for (int i = 0; i < vecloadFactor; i++) {
          buf[i] += buf2[i];
        }
```

By the way, what is the typical value of `vecloadFactor`?
```
      constexpr int vecloadFactor =
          sizeof(vecload_type_t) / sizeof(T); // important for half.
```
What's the `vecloadFactor` when `vecload_type_t = int4` and `T = double`?  0?

**Comment by traveller59** [comment]
every indice in a kernel position (```indicePairs[0, kernelIndex, :]```) is unique.
vecloadFactor is always int4 for now.

**Comment by xmyqsh** [comment]
Got it. gather/gemm/scatter is operated per `kernelIndex`.
