### ISSUE TITLE
python setup.py bdist_wheel  error

### ISSUE THREAD

**Issue by Ariellsc** [traveller59/spconv#158]
` raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.`

When I execute the command，this error happened，I have uninstalled camke and re-install several time, still have this error.Who can tell me how to fix this problem? thanks

**Comment by mawanda-jun** [comment]
Hi, could you please attach the whole output of the command? I think this is the only last lines ,- which are quite common and do not tell much about the error.
