### ISSUE TITLE
Question about the value selection of NumILP

### ISSUE THREAD

**Issue by xmyqsh** [traveller59/spconv#160]
I found a law about `NumILP`. `NumILP = NumTLP / 4`.
Same things happened in `SparseConvNet`,
```
template <>
void dConvolution_forward<double>(double *inFeatures, double *outFeatures,
				  double *w, Int *rules, Int nHot,
				  Int input_nPlanes, Int input_stride,
				  Int output_nPlanes, Int output_stride, Int nGroups) {
  FOO(double, 32, 8)
  FOO(double, 16, 4)
  FOO(double, 8, 2)
  assert(false);
}
```

```
32 / 8 = 4
16 / 4 = 4
8 / 2 = 4
```

@traveller59 Can you have a explain about this?

**Comment by traveller59** [comment]
It's inspired by SparseConvNet and a [slide](http://www.nvidia.com/content/GTC-2010/pdfs/2238_GTC2010.pdf). I haven't do experiment for ILP.
