### ISSUE TITLE
atomicAdd() does not support float type

### ISSUE THREAD

**Issue by XingangPan** [traveller59/spconv#166]
Hi, thanks for this nice sparse conv lib! I am trying to implement a sparse bilinear upsampling layer based on this repo. However, when I use the atomicAdd() function to copy the gradient (float type), the compilation would have the following error:
```
error: no instance of overloaded function "atomicAdd" matches the argument list
          argument types are: (float, float)
```
It seems that the atomicAdd() function here only supports int or long type. Do you have any idea on how to make it support float type as well? Thanks.

**Comment by traveller59** [comment]
you need to provide ```float*``` for first argument, not float.

**Comment by xmyqsh** [comment]
inverse 2/2/0

**Comment by XingangPan** [comment]
Solved. Thanks!
