### ISSUE TITLE
RuntimeError: radix_sort: failed on 2nd step: cudaErrorInvalidValue: invalid argument

### ISSUE THREAD

**Issue by roymerry** [traveller59/spconv#169]
spconv.SparseConv3d(in_channels, out_channels, 3, 2, padding=1, bias=False, indice_key=None, use_hash=False),
got radix_sort error when stide = 2

--------------------------
[perception]  terminate called after throwing an instance of 'pybind11::error_already_set'
[perception]    what():  RuntimeError: radix_sort: failed on 2nd step: cudaErrorInvalidValue: invalid argument
[perception]  
[perception]  At:
[perception]    /usr/local/miniconda3/lib/python3.7/site-packages/spconv/ops.py(93): get_indice_pairs
[perception]    /usr/local/miniconda3/lib/python3.7/site-packages/spconv/conv.py(177): forward
[perception]    /usr/local/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(532): __call__
[perception]    /usr/local/miniconda3/lib/python3.7/site-packages/spconv/modules.py(133): forward
[perception]    /usr/local/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py(532): __call__

**Comment by traveller59** [comment]
this problem usually due to invalid memory access in previous operations.
could you share your input data (features, indices, spatial shape, batch size) to help me debug this issue?

**Comment by ylwhxht** [comment]
> 

Hi, I have the same problem when I train with Mult-GPUs
The debug code is
`print(input_sp_tensor.features.shape)
        print(input_sp_tensor.indices.shape)
        print(input_sp_tensor.spatial_shape)
        print(input_sp_tensor.batch_size)`

And the result is
torch.Size([178498, 5])
torch.Size([178498, 4])
[41, 1504, 1504]
2

can you help me？
