### ISSUE TITLE
nothing to show after run "python setup.py bdist_wheel"

### ISSUE THREAD

**Issue by MinghuiJ** [traveller59/spconv#170]
After running "python setup.py bdist_wheel", nothing shows on my screen,  what happend???

**Comment by MinghuiJ** [comment]
$ python setup.py bdist_wheel
(here is cursor, nothing outputs infomation shows)

The situation lasts for half an hour at least

**Comment by traveller59** [comment]
looks like your program hangs during import. you can insert several print to setup.py and determine which import hangs.

**Comment by MinghuiJ** [comment]
> looks like your program hangs during import. you can insert several print to setup.py and determine which import hangs.

I insert several print and find that import modules are all passed. The program is hanging in function "setup()".

Several print are as follows and it outputs '12' and can not outputs '13', can you tell me what to do?
```
packages = find_packages(exclude=('tools', 'tools.*'))
print('12')
setup(
    name='spconv',
    version='1.2.1',
    author='Yan Yan',
    author_email='scrin@foxmail.com',
    description='spatial sparse convolution for pytorch',
    long_description='',
    setup_requires = ['torch>=1.3.0'],
    packages=packages,
    package_dir = {'spconv': 'spconv'},
    ext_modules=[CMakeExtension('spconv', library_dirs=[])],
    cmdclass=dict(build_ext=CMakeBuild),
    zip_safe=False
)
print('13')
```

**Comment by MinghuiJ** [comment]
The fact is that I am using pytorch=1.1.0. After changing pytorch version to 1.3.0, everything goes smoothly. Sorry for my carelessness.
