### ISSUE TITLE
How to upsample with SparseInverseConv when downsampling using SparseMaxpool3D

### ISSUE THREAD

**Issue by AshleyQTDS** [traveller59/spconv#171]
Hi, Yan,

I see that you say the sparseinverseconv should follow the sparseconv3d to make the upsampling. However, I use the sparsemaxpool3d to downsample, and how should I do to make the upsampling with SparseInverseconv?

The code snippet is like:
```python
a = spconv.SubMConv3d(indice_key="a1")
downa = spconv.SparseMaxPool3d(2,2)
upa = spconv.SparseInverseConv3d(indice_key="a1")
```

Can I do the upsampling like that? or there is a more elegent approach.

Thanks.

**Comment by ZXP-S-works** [comment]
Hi Ashley,

Do you find any solution to it?
