### ISSUE TITLE
Usage of ConcatTable?

### ISSUE THREAD

**Issue by andrewcking** [traveller59/spconv#174]
First just want to say I love all the work you have done on this PyTorch extension.

I am trying to understand the exact usage and reasoning behind ConcatTable, is there a simple example you can point me to? Is my understanding correct that the ConcatTable is for channel-wise concatenation (thus why it is needed for semantic segmentation architectures)? 

If one were to simply concatenate the features tensor and the indices tensor and create a new SparseConvTensor would that work the same way?

**Comment by AlanDecode** [comment]
As I see, ConcatTable is different than channel-wise concatenation, it's a container which holds multiple models, and in its forward function, it passes the input through all submodules, and return a list consists of all outputs:

```python
def forward(self, input):
        return [module(input) for module in self._modules.values()]
```

The channel-wise concatenation you mentiond is pretty much what JoinTable dose:

```python
def forward(self, input):
        output = spconv.SparseConvTensor(
            torch.cat([i.features for i in input], 1), input[1].indices,
            input[1].spatial_shape, input[0].batch_size)
        output.indice_dict = input[1].indice_dict
        output.grid = input[1].grid
        return output
```

> If one were to simply concatenate the features tensor and the indices tensor and create a new SparseConvTensor would that work the same way?

Yes, in JoinTable I think it's the same thing.
