### ISSUE TITLE
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

### ISSUE THREAD

**Issue by victoryc** [traveller59/spconv#178]
I am trying to get this to build on Windows. The first error I encountered was about the "openmp" flag. That went away after removing that flag from Caffe2Targets.cmake file as suggested. The next error message I am getting is:

nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

Any idea how to fix this? 
Thanks.

**Comment by traveller59** [comment]
this error message is due to previous errors.
the windows support is dropped due to constexpr bug of nvcc (or msvc, not sure).
