### ISSUE TITLE
subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by hughlee815** [traveller59/spconv#179]
`/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/adas/congcong.li/spconv/src/spconv/reordering.cc:17:0:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc: In lambda function:
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:32:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:32:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:33:41: error: expected primary-expression before ‘>’ token
       T *buffer_data = buffer.data_ptr<T>();
                                         ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:33:43: error: expected primary-expression before ‘)’ token
       T *buffer_data = buffer.data_ptr<T>();
                                           ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:34:51: error: expected primary-expression before ‘>’ token
       const T *features_data = features.data_ptr<T>();
                                                   ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:34:53: error: expected primary-expression before ‘)’ token
       const T *features_data = features.data_ptr<T>();
                                                     ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc: In lambda function:
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:56:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:56:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:57:47: error: expected primary-expression before ‘>’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                               ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:57:49: error: expected primary-expression before ‘)’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                                 ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:58:48: error: expected primary-expression before ‘>’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:58:50: error: expected primary-expression before ‘)’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                  ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc: In lambda function:
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:60:41: error: expected primary-expression before ‘>’ token
         const T *buf = buffer.data_ptr<T>();
                                         ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:60:43: error: expected primary-expression before ‘)’ token
         const T *buf = buffer.data_ptr<T>();
                                           ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:61:40: error: expected primary-expression before ‘>’ token
         T *out = outFeatures.data_ptr<T>();
                                        ^
/home/adas/congcong.li/spconv/src/spconv/reordering.cc:61:42: error: expected primary-expression before ‘)’ token
         T *out = outFeatures.data_ptr<T>();
                                          ^
In file included from /home/adas/congcong.li/spconv/src/spconv/all.cc:17:0:
/home/adas/congcong.li/spconv/include/spconv/pillar_scatter_ops.h: In function ‘at::Tensor spconv::pointPillarScatter(at::Tensor, at::Tensor, at::Tensor)’:
/home/adas/congcong.li/spconv/include/spconv/pillar_scatter_ops.h:40:35: error: expected primary-expression before ‘int’
   auto shapeData = shape.data_ptr<int>();
                                   ^~~
/home/adas/congcong.li/spconv/include/spconv/pillar_scatter_ops.h:43:38: error: could not convert ‘{<expression error>, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
                    features.options());
                                      ^
In file included from /home/adas/congcong.li/spconv/include/spconv/maxpool.h:19:0,
                 from /home/adas/congcong.li/spconv/src/spconv/maxpool.cc:15:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc: In lambda function:
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:35:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:35:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:36:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:36:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:37:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:37:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:38:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:38:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc: In lambda function:
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:64:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:64:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:65:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:65:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:66:38: error: expected primary-expression before ‘>’ token
       auto doutData = dout.data_ptr<T>();
                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:66:40: error: expected primary-expression before ‘)’ token
       auto doutData = dout.data_ptr<T>();
                                        ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:67:36: error: expected primary-expression before ‘>’ token
       auto dinData = din.data_ptr<T>();
                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:67:38: error: expected primary-expression before ‘)’ token
       auto dinData = din.data_ptr<T>();
                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:68:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:68:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:69:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/adas/congcong.li/spconv/src/spconv/maxpool.cc:69:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
In file included from /home/adas/congcong.li/spconv/include/spconv/spconv_ops.h:20:0,
                 from /home/adas/congcong.li/spconv/src/spconv/indice.cc:18:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^~
/home/adas/congcong.li/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
src/spconv/CMakeFiles/spconv.dir/build.make:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:121: recipe for target 'src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:95: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:82: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/adas/anaconda3/envs/sa-ssd/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
`
did anyone encounter the same problem when  running python setup.py bdist_wheel？
what a e meng！

**Comment by traveller59** [comment]
your pytorch version is too old. this project only support pytorch >= 1.3.

**Comment by hughlee815** [comment]
thank you. 
and one more question: actually i need to install spconv v1.0, but i cannot find it. is there any way to install v1.0?

**Comment by traveller59** [comment]
I haven't create any release, you can find out commit id of "spconv 1.0", I will create a branch/tag for it.
The master version of spconv have completely compatible API with 1.0. It should have no problem when you use it instead of 1.0.
