### ISSUE TITLE
What's the speed of indice generation?

### ISSUE THREAD

**Issue by xmyqsh** [traveller59/spconv#183]
Is there a convenient way to get the speed of indice generation?
A benchmark script is preferred: prints `indice generation time` and `conv time` respectively.

There are several ways to speed up it. And it is meaningful for small (channel) network especially.

**Comment by traveller59** [comment]
per-layer benchmark has been added to develop branch. set "SparseConvTensor.benchmark" to true to enable it. see [this script](https://github.com/traveller59/spconv/blob/develop/test/benchmark_detail.py) for more details.
