### ISSUE TITLE
subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)

### ISSUE THREAD

**Issue by hughlee815** [traveller59/spconv#184]
`running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/nio/anaconda3/envs/pp/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/nio/pointdet/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.3.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  3.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_30,code=sm_30
CMake Warning (dev) at /home/nio/anaconda3/envs/pp/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/nio/anaconda3/envs/pp/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  3.0
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nio/pointdet/spconv/build/temp.linux-x86_64-3.7
[  8%] Built target spconv_nms
[ 33%] Built target cuhash
[ 41%] Built target spconv_utils
[ 45%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/libspconv.so
../cuhash/libcuhash.a(cmake_device_link.o): In function `__cudaRegisterLinkedBinary_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37':
link.stub:(.text+0x1b0): multiple definition of `__cudaRegisterLinkedBinary_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37'
CMakeFiles/spconv.dir/cmake_device_link.o:link.stub:(.text+0x350): first defined here
collect2: error: ld returned 1 exit status
src/spconv/CMakeFiles/spconv.dir/build.make:357: recipe for target '../lib.linux-x86_64-3.7/spconv/libspconv.so' failed
make[2]: *** [../lib.linux-x86_64-3.7/spconv/libspconv.so] Error 1
CMakeFiles/Makefile2:205: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/nio/anaconda3/envs/pp/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
`
i have used --recursive, my pytorch==1.4.0, why i still get problem?
please help, i have been confused by this for a long long time

**Comment by liyang0522** [comment]
same problem！

**Comment by ConanCui** [comment]
same proble, any solve solution?
