### ISSUE TITLE
no nvidia-driver in docker spconv

### ISSUE THREAD

**Issue by Shawn-Zhuang** [traveller59/spconv#185]
Hi,
I have docker pull your spconv, but when I run some codes, it shows I don't have nvidia-driver, which I have in my local system. What should I do? I try to install the driver in the container running 

```
$ sudo add-apt-repository ppa:graphics-drivers/ppa
$ sudo apt-get update
$ sudo apt-get install nvidia-driver-440
$ sudo reboot now
```

However, there is still a mistake when I run nvidia-smi
`Failed to initialize NVML: Unknown Error`

Thank you for your kind help. I am new to docker.

**Comment by traveller59** [comment]
you don't need to install nvidia driver in container, containers use driver in host.
you need to install [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) first, then run docker with ```--gpus all``` to use gpu.

**Comment by Shawn-Zhuang** [comment]
Thanks, it is successful.
