### ISSUE TITLE
Problems running the setup.py 

### ISSUE THREAD

**Issue by dileepamarasinghe** [traveller59/spconv#190]
Here is my error log. I am using anaconda environment with pytorch 1.4 

$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/dimarasi/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dimarasi/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 6.1.0
-- The CUDA compiler identification is NVIDIA 11.0.167
-- Check for working CXX compiler: /home/dimarasi/anaconda3/envs/pvrcnn/bin/c++
-- Check for working CXX compiler: /home/dimarasi/anaconda3/envs/pvrcnn/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.0")
-- Caffe2: CUDA detected: 11.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.0
-- Found CUDNN: /usr/lib64/libcudnn.so
-- Found cuDNN: v7.6.5  (include: /usr/include, library: /usr/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /home/dimarasi/anaconda3/envs/pvrcnn/lib/python3.7/site-packages/torch/lib/libtorch.so
-- Autodetected CUDA architecture(s):  7.5
-- Found PythonInterp: /home/dimarasi/anaconda3/envs/pvrcnn/bin/python3.7 (found suitable version "3.7.7", minimum required is "3.7")
-- Found PythonLibs: /home/dimarasi/anaconda3/envs/pvrcnn/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dimarasi/spconv/build/temp.linux-x86_64-3.7
Scanning dependencies of target spconv_nms
Scanning dependencies of target cuhash
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[  8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 12%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 16%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 24%] Linking CUDA static library libspconv_nms.a
[ 24%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 28%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 32%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 36%] Linking CXX static library libcuhash.a
[ 36%] Built target cuhash
Scanning dependencies of target spconv
[ 40%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 44%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 48%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/dimarasi/spconv/src/utils/all.cc:15:0:
/home/dimarasi/spconv/include/spconv/box_iou.h: In function ‘pybind11::array_t<DType> spconv::rbbox_iou(pybind11::array_t<DType>, pybind11::array_t<DType>, pybind11::array_t<DType>, DType)’:
/home/dimarasi/spconv/include/spconv/box_iou.h:47:22: error: ‘polygon’ in namespace ‘boost::geometry::model’ does not name a template type
   typedef bg::model::polygon<point_t> polygon_t;
                      ^~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:48:3: error: ‘polygon_t’ was not declared in this scope
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:49:15: error: the value of ‘polygon_t’ is not usable in a constant expression
   std::vector<polygon_t> poly_inter, poly_union;
               ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:48:3: note: ‘polygon_t’ was not declared ‘constexpr’
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:49:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   std::vector<polygon_t> poly_inter, poly_union;
                        ^
/home/dimarasi/spconv/include/spconv/box_iou.h:49:24: note:   expected a type, got ‘polygon_t’
/home/dimarasi/spconv/include/spconv/box_iou.h:49:24: error: template argument 2 is invalid
/home/dimarasi/spconv/include/spconv/box_iou.h:65:18: error: ‘poly’ was not declared in this scope
       bg::append(poly, point_t(box_corners_r(n, 0, 0), box_corners_r(n, 0, 1)));
                  ^~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:70:18: error: ‘qpoly’ was not declared in this scope
       bg::append(qpoly,
                  ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:83:23: error: request for member ‘empty’ in ‘poly_inter’, which is of non-class type ‘int’
       if (!poly_inter.empty()) {
                       ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:84:42: error: request for member ‘front’ in ‘poly_inter’, which is of non-class type ‘int’
         inter_area = bg::area(poly_inter.front());
                                          ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:86:25: error: request for member ‘empty’ in ‘poly_union’, which is of non-class type ‘int’
         if (!poly_union.empty()) {
                         ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:87:44: error: request for member ‘front’ in ‘poly_union’, which is of non-class type ‘int’
           union_area = bg::area(poly_union.front());
                                            ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:90:20: error: request for member ‘clear’ in ‘poly_union’, which is of non-class type ‘int’
         poly_union.clear();
                    ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:94:18: error: request for member ‘clear’ in ‘poly_inter’, which is of non-class type ‘int’
       poly_inter.clear();
                  ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h: In function ‘pybind11::array_t<DType> spconv::rbbox_intersection(pybind11::array_t<DType>, pybind11::array_t<DType>, pybind11::array_t<DType>, DType)’:
/home/dimarasi/spconv/include/spconv/box_iou.h:107:22: error: ‘polygon’ in namespace ‘boost::geometry::model’ does not name a template type
   typedef bg::model::polygon<point_t> polygon_t;
                      ^~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:108:3: error: ‘polygon_t’ was not declared in this scope
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:109:15: error: the value of ‘polygon_t’ is not usable in a constant expression
   std::vector<polygon_t> poly_inter, poly_union;
               ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:108:3: note: ‘polygon_t’ was not declared ‘constexpr’
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:109:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   std::vector<polygon_t> poly_inter, poly_union;
                        ^
/home/dimarasi/spconv/include/spconv/box_iou.h:109:24: note:   expected a type, got ‘polygon_t’
/home/dimarasi/spconv/include/spconv/box_iou.h:109:24: error: template argument 2 is invalid
/home/dimarasi/spconv/include/spconv/box_iou.h:125:18: error: ‘poly’ was not declared in this scope
       bg::append(poly, point_t(box_corners_r(n, 0, 0), box_corners_r(n, 0, 1)));
                  ^~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:130:18: error: ‘qpoly’ was not declared in this scope
       bg::append(qpoly,
                  ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:143:23: error: request for member ‘empty’ in ‘poly_inter’, which is of non-class type ‘int’
       if (!poly_inter.empty()) {
                       ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:144:42: error: request for member ‘front’ in ‘poly_inter’, which is of non-class type ‘int’
         inter_area = bg::area(poly_inter.front());
                                          ^~~~~
/home/dimarasi/spconv/include/spconv/box_iou.h:149:18: error: request for member ‘clear’ in ‘poly_inter’, which is of non-class type ‘int’
       poly_inter.clear();
                  ^~~~~
In file included from /home/dimarasi/spconv/src/utils/all.cc:16:0:
/home/dimarasi/spconv/include/spconv/nms.h: In function ‘std::vector<int> spconv::rotate_non_max_suppression_cpu(pybind11::array_t<DType>, pybind11::array_t<int>, pybind11::array_t<DType>, DType)’:
/home/dimarasi/spconv/include/spconv/nms.h:93:22: error: ‘polygon’ in namespace ‘boost::geometry::model’ does not name a template type
   typedef bg::model::polygon<point_t> polygon_t;
                      ^~~~~~~
/home/dimarasi/spconv/include/spconv/nms.h:94:3: error: ‘polygon_t’ was not declared in this scope
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/nms.h:95:15: error: the value of ‘polygon_t’ is not usable in a constant expression
   std::vector<polygon_t> poly_inter, poly_union;
               ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/nms.h:94:3: note: ‘polygon_t’ was not declared ‘constexpr’
   polygon_t poly, qpoly;
   ^~~~~~~~~
/home/dimarasi/spconv/include/spconv/nms.h:95:24: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
   std::vector<polygon_t> poly_inter, poly_union;
                        ^
/home/dimarasi/spconv/include/spconv/nms.h:95:24: note:   expected a type, got ‘polygon_t’
/home/dimarasi/spconv/include/spconv/nms.h:95:24: error: template argument 2 is invalid
/home/dimarasi/spconv/include/spconv/nms.h:111:20: error: ‘poly’ was not declared in this scope
         bg::append(poly,
                    ^~~~
/home/dimarasi/spconv/include/spconv/nms.h:121:20: error: ‘qpoly’ was not declared in this scope
         bg::append(qpoly,
                    ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:148:23: error: request for member ‘empty’ in ‘poly_inter’, which is of non-class type ‘int’
       if (!poly_inter.empty()) {
                       ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:149:42: error: request for member ‘front’ in ‘poly_inter’, which is of non-class type ‘int’
         inter_area = bg::area(poly_inter.front());
                                          ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:151:20: error: ‘poly’ was not declared in this scope
         bg::union_(poly, qpoly, poly_union);
                    ^~~~
/home/dimarasi/spconv/include/spconv/nms.h:151:26: error: ‘qpoly’ was not declared in this scope
         bg::union_(poly, qpoly, poly_union);
                          ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:167:25: error: request for member ‘empty’ in ‘poly_union’, which is of non-class type ‘int’
         if (!poly_union.empty()) { // ignore invalid box
                         ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:168:44: error: request for member ‘front’ in ‘poly_union’, which is of non-class type ‘int’
           union_area = bg::area(poly_union.front());
                                            ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:174:22: error: request for member ‘clear’ in ‘poly_union’, which is of non-class type ‘int’
           poly_union.clear();
                      ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:177:7: error: ‘poly’ was not declared in this scope
       poly.clear();
       ^~~~
/home/dimarasi/spconv/include/spconv/nms.h:178:7: error: ‘qpoly’ was not declared in this scope
       qpoly.clear();
       ^~~~~
/home/dimarasi/spconv/include/spconv/nms.h:179:18: error: request for member ‘clear’ in ‘poly_inter’, which is of non-class type ‘int’
       poly_inter.clear();
                  ^~~~~
gmake[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 1
gmake[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 56%] Building CXX object src/spconv/CMakeFiles/spconv.dir/nms.cc.o
[ 60%] Building CXX object src/spconv/CMakeFiles/spconv.dir/spconv_ops.cc.o
[ 64%] Building CXX object src/spconv/CMakeFiles/spconv.dir/pool_ops.cc.o
[ 68%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
/home/dimarasi/spconv/src/spconv/nms.cc: In member function ‘Index spconv::functor::rotateNonMaxSupressionFunctor<tv::CPU, T, Index>::operator()(const tv::CPU&, tv::TensorView<Index>, tv::TensorView<const T>, tv::TensorView<const T>, T)’:
/home/dimarasi/spconv/src/spconv/nms.cc:77:24: error: ‘polygon’ in namespace ‘boost::geometry::model’ does not name a template type
     typedef bg::model::polygon<point_t> polygon_t;
                        ^~~~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:78:5: error: ‘polygon_t’ was not declared in this scope
     polygon_t poly, qpoly;
     ^~~~~~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:79:17: error: the value of ‘polygon_t’ is not usable in a constant expression
     std::vector<polygon_t> poly_inter, poly_union;
                 ^~~~~~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:78:5: note: ‘polygon_t’ was not declared ‘constexpr’
     polygon_t poly, qpoly;
     ^~~~~~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:79:26: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
     std::vector<polygon_t> poly_inter, poly_union;
                          ^
/home/dimarasi/spconv/src/spconv/nms.cc:79:26: note:   expected a type, got ‘polygon_t’
/home/dimarasi/spconv/src/spconv/nms.cc:79:26: error: template argument 2 is invalid
/home/dimarasi/spconv/src/spconv/nms.cc:94:20: error: ‘poly’ was not declared in this scope
         bg::append(poly, point_t(boxCorners(i, 0, 0), boxCorners(i, 0, 1)));
                    ^~~~
/home/dimarasi/spconv/src/spconv/nms.cc:99:20: error: ‘qpoly’ was not declared in this scope
         bg::append(qpoly, point_t(boxCorners(j, 0, 0), boxCorners(j, 0, 1)));
                    ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:106:25: error: request for member ‘empty’ in ‘poly_inter’, which is of non-class type ‘int’
         if (!poly_inter.empty()) {
                         ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:107:44: error: request for member ‘front’ in ‘poly_inter’, which is of non-class type ‘int’
           inter_area = bg::area(poly_inter.front());
                                            ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:109:27: error: request for member ‘empty’ in ‘poly_union’, which is of non-class type ‘int’
           if (!poly_union.empty()) { // ignore invalid box
                           ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:110:46: error: request for member ‘front’ in ‘poly_union’, which is of non-class type ‘int’
             union_area = bg::area(poly_union.front());
                                              ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:114:24: error: request for member ‘clear’ in ‘poly_union’, which is of non-class type ‘int’
             poly_union.clear();
                        ^~~~~
/home/dimarasi/spconv/src/spconv/nms.cc:119:20: error: request for member ‘clear’ in ‘poly_inter’, which is of non-class type ‘int’
         poly_inter.clear();
                    ^~~~~
/home/dimarasi/spconv/include/tensorview/tensorview.h(1055): warning: integer conversion resulted in a change of sign
          detected during instantiation of class "tv::TensorView<T, Rank, PtrTraits, Tindex> [with T=int32_t, Rank=-1, PtrTraits=tv::DefaultPtrTraits, Tindex=int]"
/home/dimarasi/spconv/src/spconv/indice.cu(159): here

gmake[2]: *** [src/spconv/CMakeFiles/spconv.dir/nms.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....

**Comment by 447983454** [comment]
In my setup experience, the install dependencies cause many errors.
I used pytorch 1.2.0, cuda 9.0, failed.
pytorch 1.3.1, cuda 9.0, failed.
pytorch 1.3.1, cuda 10.0, success.

**Comment by dileepamarasinghe** [comment]
> In my setup experience, the install dependencies cause many errors.
> I used pytorch 1.2.0, cuda 9.0, failed.
> pytorch 1.3.1, cuda 9.0, failed.
> pytorch 1.3.1, cuda 10.0, success.

Thanks for the reply. I will try that.

**Comment by dileepamarasinghe** [comment]
It needed to add the header file #include <boost/geometry/geometries/polygon.hpp> to the files giving the error.

**Comment by EthanZhangYi** [comment]
same error. Any solution?

**Comment by dileepamarasinghe** [comment]
> same error. Any solution?

It needed to add the header file #include <boost/geometry/geometries/polygon.hpp> to the files giving the error.

Didn't this work 😬

**Comment by EthanZhangYi** [comment]
@dileepamarasinghe 
Solved. I add the header file `#include <boost/geometry/geometries/geometries.hpp>`
As shown in Issue #106
