### ISSUE TITLE
getIndicePairs doesn't produce unique result, does it make sense?

### ISSUE THREAD

**Issue by lisongze** [traveller59/spconv#192]
Hi Yan, I feed same input features, indices, weight to test SubMConv3d function many times, each time I got different results from it, finally I found the ```getIndicePairs``` function produced different ```indice_pairs``` result each time, I don't know does this make sense?

I only tested the CUDA version. I can't test CPU version because it has segmentation fault.

Here is my code
```
import numpy as np
import torch, os, sys, spconv

# test data from file
input_features_file = './input_features.npy'
input_indices_file = './input_indices.npy'
input_spatial_shape_file = './input_spatial_shape.npy'
weight_file = './weight.npy'

# input tensor
input_features = np.load(input_features_file)
input_indices = np.load(input_indices_file)
input_spatial_shape = list(np.load(input_spatial_shape_file))
input_batch_size = 1

input_features = torch.Tensor(input_features)
input_indices = torch.Tensor(input_indices).int()

cuda_device = torch.device('cuda:0')
input_features = input_features.to(cuda_device)
input_indices = input_indices.to(cuda_device)

x = spconv.SparseConvTensor(
    features=input_features, 
    indices=input_indices, 
    spatial_shape=input_spatial_shape, 
    batch_size=input_batch_size)

# spconv layer
conv0 = spconv.SubMConv3d(4, 16, 3, bias=False)
conv0.eval()
weight = np.load(weight_file)
weight = torch.Tensor(weight)
state_dict = conv0.state_dict()
state_dict.update({'weight':weight})
conv0.load_state_dict(state_dict)

conv0.to(cuda_device)

# forward
output_features = conv0(x)
```

**Comment by hitpeterfeng** [comment]
same problem here, cuda implemention with randomness!

**Comment by thangvubk** [comment]
@lisongze, @hitpeterfeng, I meet same problem. However, i found that this problem happens when the ``indices`` of sparse tensor consists of some similar rows. If you make the ``indices`` tensor have unique rows, the output should be unique.

**Comment by jisoo0-0** [comment]
> rows

Do you mean values?? how can we make unique rows of the indices tensor?
