### ISSUE TITLE
Cuda Indicies Segmentation Fault

### ISSUE THREAD

**Issue by ErenBalatkan** [traveller59/spconv#193]
Greetings,

I am getting segmentation fault when i try to make a forward pass through model when indices are stored on GPU

Simply moving indices to CPU solves the problem

I can reproduce this issue on this code
https://github.com/traveller59/spconv/blob/master/test/fake_train.py

```
def dev():
    ds = FakeSparseDataset()
    for i in range(10):
        features, indices, label = ds[i]
        print(indices[:10])
    features_t = torch.from_numpy(features.astype(np.float32))
    indices_t = torch.from_numpy(indices.astype(np.int32))
    net = FakeClassifier().cuda()
    net(features_t.cuda(), indices_t.cuda())
```

Gives Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```
def dev():
    ds = FakeSparseDataset()
    for i in range(10):
        features, indices, label = ds[i]
        print(indices[:10])
    features_t = torch.from_numpy(features.astype(np.float32))
    indices_t = torch.from_numpy(indices.astype(np.int32))
    net = FakeClassifier().cuda()
    net(features_t.cuda(), indices_t.cpu())
```

Executes without any issues

Torch Version : 1.5.1
CudNN version : 7.6
Cuda version : 10.2

I havent encountered any issues during installation (Other than -Wall issue which is fixed simply by commenting flags)

**Comment by andrewcking** [comment]
Not sure if helpful but I've mostly encountered segmentation fault issues when the indices fall outside the stated spatial size of the sparse tensor. Is it possible for your `FakeSparseDataset` to generate indices outside your sparse tensor spatial size? If so the cpu/gpu difference could either be just chance or perhaps Spconv handles those errors differently on cpu vs gpu
