### ISSUE TITLE
PyTorch Version of the Voxel Generator

### ISSUE THREAD

**Issue by monghimng** [traveller59/spconv#194]
Hi, I am wondering if the author has any insight in implementing a PyTorch Voxel Generator. The current voxel generator uses C code to run extremely quickly, but this makes it indifferentiable.

- I could read the C code and figure out what it does, and then implement a PyTorch version that is not too slow. Yet there isn't too many code comments, so it would be extremely hard to understand what the code is doing. Is there any notes on how the voxelization method is done?
- Or, does the author know of any PyTorch differentiable voxelization on the web that `spconv` is compatible with?

Thanks!

**Comment by zyl1336110861** [comment]
Have you got any differentiable voxelization method?
