### ISSUE TITLE
what command should i use when i use a CENTOS system?

### ISSUE THREAD

**Issue by hughlee815** [traveller59/spconv#195]
when i run `sudo yum install libboost-all-dev` on a server which use centos system, it says: `no package libboost-all-dev is available`. i think there may be a other command?
does anyone know what should i do to fix it.
thanks in advance.

**Comment by cuge1995** [comment]
Did you succeed installed in CentOS system ? I'm always failed.

**Comment by cuge1995** [comment]
Did you succeed installed in CentOS system ? I'm always failed.

**Comment by hughlee815** [comment]
> Did you succeed installed in CentOS system ? I'm always failed.

no, and seemly never.
