### ISSUE TITLE
cudnn8 build failure

### ISSUE THREAD

**Issue by dawonn-haval** [traveller59/spconv#196]
cmake fails to identify cudnn version:
```
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v?  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at /home/haval/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:170 (message):
  PyTorch requires cuDNN 7 and above.
```

@ /home/haval/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:L148 
the version number is being extracted from cudnn.h, but this may have been moved to a separate file (cudnn_version):
```
/usr/include/x86_64-linux-gnu/cudnn_adv_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_adv_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_backend_v8.h
/usr/include/x86_64-linux-gnu/cudnn_cnn_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_cnn_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_ops_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_ops_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_v8.h
/usr/include/x86_64-linux-gnu/cudnn_version_v8.h
```
note that cudnn.h now appears to be a 'metapackage' file that includes the rest of the headers for backwards compatibility, but the cmake version regex fails because it doesn't load #include files...

**Comment by dawonn-haval** [comment]
It's possible that this is resolved in pytorch 1.6; The cuda.cmake file appears to be quite different. 

I'm unable to build pytorch from source, so I can't confirm if that's the case or not though. 

My guess is that there is nothing to be done here in spconv until pytorch 1.6 is released.

**Comment by eriche2016** [comment]
@dawonn-haval  I address this issue by modifying: 
/home/your_name/anaconda3/envs/your_env/lib/python3.6/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake
at line 137 from: 
file(READ $CUDNN_INCLUDE_DIR/cudnn.h CUDNN_HEADER_CONTENTS)
to:  
file(READ $CUDNN_INCLUDE_DIR/cudnn_version.h CUDNN_HEADER_CONTENTS)
and it works fine on my machine.

**Comment by Hao-HUST** [comment]
@dawonn-haval Did you solve the problem with cudnn 8?
