### ISSUE TITLE
how to "Set an environment variable LIBTORCH_ROOT to the root path of LibTorch"

### ISSUE THREAD

**Issue by mengmeng716** [traveller59/spconv#2]
thank you for your contribution!

in "setup.py“ line 12 There is a environment variable"LIBTORCH_ROOT", I don't know how do that, can you add the command to do that please? 

thanks

**Comment by traveller59** [comment]
example: ```export LIBTORCH_ROOT=/home/yy/library/libtorch```

**Comment by mengmeng716** [comment]
Thanks for your rapid answer!

I installed torch with pip, and i have added it in .bashrc
export LIBTORCH_ROOT="/home/qmm/anaconda3/lib/python3.6/site-packages/torch" 

I checked LIBTORCH_ROOT is already in the ens variable.
but i got: 
![screenshot from 2019-01-21 17-00-13](https://user-images.githubusercontent.com/46182967/51463382-0fe1b800-1d9e-11e9-81ea-fd3a7354e4d2.png)

**Comment by traveller59** [comment]
@mengmeng716 
use ```. ~/.bashrc``` to update environment.
the LibTorch is not pytorch, LibTorch is a c++ only library, you need to download it in pytorch official site.
