### ISSUE TITLE
setup with subprocess error

### ISSUE THREAD

**Issue by mengmeng716** [traveller59/spconv#20]
happy new year.
I have got the following problem: how should I resolve it please? I don't understand it .
my gcc is 5.4, and cuda is 9.0 
![1](https://user-images.githubusercontent.com/46182967/52828085-52c74f00-3102-11e9-9eb4-bcdbae414373.png)

**Comment by dhingratul** [comment]
+1 #22

**Comment by GIMPS** [comment]
same

**Comment by defypp** [comment]
+1

**Comment by venbalas** [comment]
+1

**Comment by YunjieYu** [comment]
I have the same problem too. Any idea to solve this problem?
