### ISSUE TITLE
how to install spconv=1.0

### ISSUE THREAD

**Issue by ChunmianLin** [traveller59/spconv#200]
Hi, I want to know how to pull and install spcnv-1.0.
Could you please provide the corresponding command to help me complete the installation?

Sorry for my trouble, I am newer to this area.
Thanks in advance!

**Comment by SternSu** [comment]
You can download it from https://github.com/traveller59/spconv/tree/8da6f967fb9a054d8870c3515b1b44eca2103634, as I know, its version is 1.0.
