### ISSUE TITLE
python setup.py bdist_wheel error. pls help. "Linking libspconv.so /usr/bin/ld: cannot find /usr/local/cuda/lib64: File format not recognized" FINALLY i use this "docker pull scrin/dev-spconv" ok

### ISSUE THREAD

**Issue by j2innet** [traveller59/spconv#202]
anyone can help... appreciate. 
i share the error faced after i build the checkout 8da6f96
thanks in advanced. 

environment used: 
ubuntu 16.04 
cuda10.0 
cudnn7.6.5 
py36 
torch1.1 
cmake3.14 gcc-5.4

$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130
CUDA Patch Version 10.0.130.1
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h"
$ nvidia-smi
Fri Jul 24 14:48:08 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 31%   38C    P5    29W / 250W |    756MiB / 11016MiB |     18%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1277      G   /usr/lib/xorg/Xorg                           396MiB |
|    0      2519      G   compiz                                       138MiB |
|    0      3372      G   /opt/teamviewer/tv_bin/TeamViewer             17MiB |
|    0      3501      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   200MiB |
+-----------------------------------------------------------------------------+
$ conda activate py36-torch11
(py36-torch11) $ python --version
Python 3.6.10
$ cmake --version
cmake version 3.14.0
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
/media/albert/1TB/home/albert/git/src/dl/spconv/build/lib.linux-x86_64-3.6
Release
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/include/  
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include/, library: /usr/local/cuda/lib64)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /home/albert/miniconda3/envs/py36-torch11/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Found PythonInterp: /home/albert/miniconda3/envs/py36-torch11/bin/python3.6 (found suitable version "3.6.10", minimum required is "3.6") 
-- Found PythonLibs: /home/albert/miniconda3/envs/py36-torch11/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Configuring done
CMake Warning at src/spconv/CMakeLists.txt:1 (add_library):
  Cannot generate a safe runtime search path for target spconv because there
  is a cycle in the constraint graph:

    dir 0 is [/usr/local/cuda/lib64]
      dir 2 must precede it due to runtime library [libnvrtc.so.10.0]
    dir 1 is [/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/site-packages/torch/lib]
    dir 2 is [/home/albert/miniconda3/envs/py36-torch11/lib]
      dir 0 must precede it due to runtime library [libcudart.so.10.0]

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /media/albert/1TB/home/albert/git/src/dl/spconv/build/temp.linux-x86_64-3.6
Scanning dependencies of target spconv_nms
Scanning dependencies of target spconv
[  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 14%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 21%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 28%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 35%] Linking CUDA device code CMakeFiles/spconv_nms.dir/cmake_device_link.o
[ 42%] Linking CUDA shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv_nms.so
[ 42%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 50%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 57%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 64%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 71%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 78%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
[ 85%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 85%] Built target spconv_utils
[ 92%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
[100%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
**/usr/bin/ld: cannot find /usr/local/cuda/lib64: File format not recognized**
collect2: error: ld returned 1 exit status
src/spconv/CMakeFiles/spconv.dir/build.make:238: recipe for target '../lib.linux-x86_64-3.6/spconv/libspconv.so' failed
make[2]: *** [../lib.linux-x86_64-3.6/spconv/libspconv.so] Error 1
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 104, in <module>
    zip_safe=False,
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 88, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/albert/miniconda3/envs/py36-torch11/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

![image](https://user-images.githubusercontent.com/14324410/88384992-19f3d500-cde0-11ea-8810-65cda0dad894.png)

**Comment by j2innet** [comment]
finally i use this "docker pull scrin/dev-spconv"
"python setup.py bdist_wheel" ok
"pip install *.whl" ok

**Comment by wolflion521** [comment]
> finally i use this "docker pull scrin/dev-spconv"
> "python setup.py bdist_wheel" ok
> "pip install *.whl" ok

I have already successfully run "docker pull scrin/dev-spconv". but the docker file seems to be downloaded to /var/lib/docker/ . so how did you run " python setpu.py bdist_wheel"? Should I cd to some folder before run"setup.py"?

**Comment by manonthegithub** [comment]
Have the same issue
