### ISSUE TITLE
cd: /dist: No such file or directory

### ISSUE THREAD

**Issue by AngYikHong** [traveller59/spconv#203]
I am not sure what this sentence means "Run cd ./dist, use pip to install generated whl file.". Can anybody help

**Comment by j2innet** [comment]
cd dist
pip install *

**Comment by AngYikHong** [comment]
(base) bryanang1010@bryanang1010-Inspiron-7447:~/second.pytorch/second/spconv$ cd dist
bash: cd: dist: No such file or directory

It shows this, I'm not sure where is the dist located.

**Comment by j2innet** [comment]
> (base) bryanang1010@bryanang1010-Inspiron-7447:~/second.pytorch/second/spconv$ cd dist
> bash: cd: dist: No such file or directory
> 
> It shows this, I'm not sure where is the dist located.

have you done this "python setup.py bdist_wheel" already? 

go to https://github.com/traveller59/spconv/tree/master#install-on-ubuntu-16041804

**Comment by AravindG1508** [comment]
Hi J2innet, were able to resolve this issue?. Even I'm facing the same issue.

**Comment by j2innet** [comment]
> Hi J2innet, were able to resolve this issue?. Even I'm facing the same issue. 

Run this first
python setup.py bdist_wheel
