### ISSUE TITLE
errors when python setup.py bdist_wheel

### ISSUE THREAD

**Issue by zsh4614** [traveller59/spconv#209]
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/dist.py:705: UserWarning: Module torch was already imported from /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/__init__.py, but /home/zedzhai/spconv/.eggs/torch-1.6.0-py3.6-linux-x86_64.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10200', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zedzhai/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.0
-- Caffe2: Header version is: 10.0
CMake Warning (dev) at /home/zedzhai/cmake-3.17.2/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (CUDNN) does
  not match the name of the calling package (Caffe2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:128 (find_package_handle_standard_args)
  /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found cuDNN: v7.3.1  (include: /usr/local/cuda-10.0/include, library: /usr/local/cuda-10.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at /home/zedzhai/cmake-3.17.2/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:103 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  6.1
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zedzhai/spconv/build/temp.linux-x86_64-3.6
[ 25%] Built target spconv_nms
[ 33%] Built target cuhash
[ 41%] Built target spconv_utils
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 58%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
In file included from /home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:20:0,
                 from /home/zedzhai/spconv/src/spconv/all.cc:15:
/home/zedzhai/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/zedzhai/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
In file included from /home/zedzhai/spconv/src/spconv/all.cc:15:0:
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h: In function ‘at::Tensor spconv::fusedIndiceConvBatchNorm(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t)’:
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:41:50: error: expected primary-expression before ‘int’
       std::max_element(indicePairNumCpu.data_ptr<int>(),
                                                  ^
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:42:50: error: expected primary-expression before ‘int’
                        indicePairNumCpu.data_ptr<int>() + kernelVolume);
                                                  ^
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:44:57: error: expected primary-expression before ‘int’
       indicePairMaxSizeIter - indicePairNumCpu.data_ptr<int>();
                                                         ^
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:77:43: error: expected primary-expression before ‘int’
     auto nHot = indicePairNumCpu.data_ptr<int>()[i];
                                           ^
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:83:75: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
                                              {nHot, numOutPlanes}, options);
                                                                           ^
In file included from /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                 from /home/zedzhai/spconv/include/spconv/indice.h:18,
                 from /home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/zedzhai/spconv/src/spconv/all.cc:15:
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note:   candidate expects 5 arguments, 3 provided
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/zedzhai/spconv/src/spconv/all.cc:15:0:
/home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:85:78: error: no matching function for call to ‘from_blob(void*, <brace-enclosed initializer list>, c10::TensorOptions&)’
         torch::from_blob(inputBuffer.data_ptr(), {nHot, numInPlanes}, options);
                                                                              ^
In file included from /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:7:0,
                 from /home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                 from /home/zedzhai/spconv/include/spconv/indice.h:18,
                 from /home/zedzhai/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /home/zedzhai/spconv/src/spconv/all.cc:15:
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:61:19: note:   candidate expects 5 arguments, 3 provided
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:79:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const Deleter&, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:98:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note: candidate: at::Tensor torch::from_blob(void*, c10::IntArrayRef, const c10::TensorOptions&)
 inline at::Tensor from_blob(
                   ^
/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:114:19: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
In file included from /home/zedzhai/spconv/src/spconv/all.cc:17:0:
/home/zedzhai/spconv/include/spconv/pillar_scatter_ops.h: In function ‘at::Tensor spconv::pointPillarScatter(at::Tensor, at::Tensor, at::Tensor)’:
/home/zedzhai/spconv/include/spconv/pillar_scatter_ops.h:40:35: error: expected primary-expression before ‘int’
   auto shapeData = shape.data_ptr<int>();
                                   ^
/home/zedzhai/spconv/include/spconv/pillar_scatter_ops.h:43:38: error: could not convert ‘{<expression error>, <expression error>, <expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
                    features.options());
                                      ^
In file included from /home/zedzhai/spconv/src/spconv/reordering.cc:17:0:
/home/zedzhai/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/zedzhai/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/zedzhai/spconv/src/spconv/reordering.cc: In lambda function:
/home/zedzhai/spconv/src/spconv/reordering.cc:32:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/zedzhai/spconv/src/spconv/reordering.cc:32:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/zedzhai/spconv/src/spconv/reordering.cc:33:41: error: expected primary-expression before ‘>’ token
       T *buffer_data = buffer.data_ptr<T>();
                                         ^
/home/zedzhai/spconv/src/spconv/reordering.cc:33:43: error: expected primary-expression before ‘)’ token
       T *buffer_data = buffer.data_ptr<T>();
                                           ^
/home/zedzhai/spconv/src/spconv/reordering.cc:34:51: error: expected primary-expression before ‘>’ token
       const T *features_data = features.data_ptr<T>();
                                                   ^
/home/zedzhai/spconv/src/spconv/reordering.cc:34:53: error: expected primary-expression before ‘)’ token
       const T *features_data = features.data_ptr<T>();
                                                     ^
/home/zedzhai/spconv/src/spconv/reordering.cc: In lambda function:
/home/zedzhai/spconv/src/spconv/reordering.cc:56:51: error: expected primary-expression before ‘>’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                   ^
/home/zedzhai/spconv/src/spconv/reordering.cc:56:53: error: expected primary-expression before ‘)’ token
       Index *indices_data = indices.data_ptr<Index>();
                                                     ^
/home/zedzhai/spconv/src/spconv/reordering.cc:57:47: error: expected primary-expression before ‘>’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                               ^
/home/zedzhai/spconv/src/spconv/reordering.cc:57:49: error: expected primary-expression before ‘)’ token
       const T *buffer_data = buffer.data_ptr<T>();
                                                 ^
/home/zedzhai/spconv/src/spconv/reordering.cc:58:48: error: expected primary-expression before ‘>’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                ^
/home/zedzhai/spconv/src/spconv/reordering.cc:58:50: error: expected primary-expression before ‘)’ token
       T *features_data = outFeatures.data_ptr<T>();
                                                  ^
/home/zedzhai/spconv/src/spconv/reordering.cc: In lambda function:
/home/zedzhai/spconv/src/spconv/reordering.cc:60:41: error: expected primary-expression before ‘>’ token
         const T *buf = buffer.data_ptr<T>();
                                         ^
/home/zedzhai/spconv/src/spconv/reordering.cc:60:43: error: expected primary-expression before ‘)’ token
         const T *buf = buffer.data_ptr<T>();
                                           ^
/home/zedzhai/spconv/src/spconv/reordering.cc:61:40: error: expected primary-expression before ‘>’ token
         T *out = outFeatures.data_ptr<T>();
                                        ^
/home/zedzhai/spconv/src/spconv/reordering.cc:61:42: error: expected primary-expression before ‘)’ token
         T *out = outFeatures.data_ptr<T>();
                                          ^
In file included from /home/zedzhai/spconv/include/spconv/maxpool.h:19:0,
                 from /home/zedzhai/spconv/src/spconv/maxpool.cc:15:
/home/zedzhai/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/zedzhai/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
/home/zedzhai/spconv/src/spconv/maxpool.cc: In lambda function:
/home/zedzhai/spconv/src/spconv/maxpool.cc:35:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:35:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:36:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:36:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:37:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:37:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:38:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:38:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
/home/zedzhai/spconv/src/spconv/maxpool.cc: In lambda function:
/home/zedzhai/spconv/src/spconv/maxpool.cc:64:52: error: expected primary-expression before ‘>’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:64:54: error: expected primary-expression before ‘)’ token
       auto outFeaturesData = outFeatures.data_ptr<T>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:65:50: error: expected primary-expression before ‘>’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                  ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:65:52: error: expected primary-expression before ‘)’ token
       auto inFeaturesData = inFeatures.data_ptr<T>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:66:38: error: expected primary-expression before ‘>’ token
       auto doutData = dout.data_ptr<T>();
                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:66:40: error: expected primary-expression before ‘)’ token
       auto doutData = dout.data_ptr<T>();
                                        ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:67:36: error: expected primary-expression before ‘>’ token
       auto dinData = din.data_ptr<T>();
                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:67:38: error: expected primary-expression before ‘)’ token
       auto dinData = din.data_ptr<T>();
                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:68:52: error: expected primary-expression before ‘>’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                    ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:68:54: error: expected primary-expression before ‘)’ token
       auto indicesInData = indicesIn.data_ptr<Index>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:69:54: error: expected primary-expression before ‘>’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                      ^
/home/zedzhai/spconv/src/spconv/maxpool.cc:69:56: error: expected primary-expression before ‘)’ token
       auto indicesOutData = indicesOut.data_ptr<Index>();
                                                        ^
In file included from /home/zedzhai/spconv/include/spconv/spconv_ops.h:20:0,
                 from /home/zedzhai/spconv/src/spconv/indice.cc:18:
/home/zedzhai/spconv/include/tensorview/torch_utils.h: In function ‘tv::TensorView<T, Rank, PtrTraits, Tindex> tv::torch2tv(const at::Tensor&)’:
/home/zedzhai/spconv/include/tensorview/torch_utils.h:125:52: error: expected primary-expression before ‘(’ token
   return tv::TensorView<T, Rank, PtrTraits, Tindex>(
                                                    ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:44: error: expected primary-expression before ‘>’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                            ^
/home/zedzhai/spconv/include/tensorview/torch_utils.h:126:47: error: expected primary-expression before ‘)’ token
       tensor.data_ptr<std::remove_const_t<T>>(), shape);
                                               ^
src/spconv/CMakeFiles/spconv.dir/build.make:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:121: recipe for target 'src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:95: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:82: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    zip_safe=False,
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/zedzhai/anaconda3/envs/pytorch/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

Please help me,thanks!

**Comment by psu1** [comment]
deleting the repo and recompiling solve my probelm.

**Comment by ll594282475** [comment]
Did you solve it as like as two peas?

**Comment by DeveshwarH1996** [comment]
I have gotten this problem too, but deleting and reinstalling didn't work for me.

**Comment by DeveshwarH1996** [comment]
This is another Github repo I found online that has solved this problem for me 
https://github.com/jinfagang/spconv

**Comment by oreo-lp** [comment]
> This is another Github repo I found online that has solved this problem for me
> https://github.com/jinfagang/spconv

tks!!

**Comment by TuttiChi** [comment]
> 

got it！
