### ISSUE TITLE
error: ‘RegisterOperators’ is not a member of ‘torch’

### ISSUE THREAD

**Issue by pandiii** [traveller59/spconv#217]

**Comment by hillegass** [comment]
I think I have the same problem: 
[ 61%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
/home/charmedliferaft/spconv/src/spconv/all.cc:20:91: error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
     torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)

$ conda list | grep torch
pytorch                   1.6.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch

**Comment by hillegass** [comment]
Sorry. I had checked out 5633f6.  This is fixed in the current version
