### ISSUE TITLE
Error occured running "setup.py " 

### ISSUE THREAD

**Issue by ayano721** [traveller59/spconv#220]
I have the compiling issue when I did "python setup.py"

My environment is folllowing.

----------------------------------------------------------------
CUDA detected: 11.0
cuDNN: v7.6.5  
Autodetected CUDA architecture(s):  7.5
CMake version : cmake-3.17.4
pybind11 v2.5.0
g++ 9.3.0
gcc 9.3.0
pytorch 1.5.0
python 3.6.9
and apt-get libbboost-dev-all

-------------------------

They looks like something error about  "auto" and not defined.
I found this kind of error a lot.

So if somebody know this answer, could you help me?

and I want to know which version you are using when you succusses. (Especially for ubuntu 20)

Thanks

**Comment by ZesongLee** [comment]
I met the same Problem...Do you have any idea for this? I think the version of nvcc(cuda) need change to 10.0...

**Comment by ayano721** [comment]
I changed cuda version  to 10....

**Comment by cattaneod** [comment]
I had the same problem, but i solve by simply deleting and cloning spconv again.

I successfully installed spconv with CUDA 11.1.1 and pytorch 1.8
