### ISSUE TITLE
What's the meaning of function "getValidOutPos"?

### ISSUE THREAD

**Issue by zzzxxxttt** [traveller59/spconv#224]
Hi @traveller59 , thanks for your remarkable project! I'm reading your code of subM convolution, could you tell me the meaning of function "getValidOutPos" in geometry.h? I really can't figure out what is it used for, especially the "lowers", "uppers" and "counter", what's the meaning of these variables?

**Comment by gopinath-r** [comment]
Hi @zzzxxxttt @traveller59  Did you figure out what getValidOutPos function does? If so can please share i am trying to re-implement sparseconv2d and i am not getting the meaning of 'lowers', 'uppers' etc.

**Comment by gopinath-r** [comment]
What is the meaning of following calculations

   lowers[i] = (input_pos[i] - (kernelSize[i] - 1) * dilation[i] - 1 +
                 stride[i] + padding[i]) /
                stride[i];
    uppers[i] = (input_pos[i] + padding[i]) / stride[i];

**Comment by zzzxxxttt** [comment]
hi @gopinath-r 
The uppers and lowers are the upper bounds and lower bounds of output points for a given input point.

for example, for a given point (5, 3) and kernel size 3, the output points which **use this point as input** are (4,2), (4,3), (4,4), (5,2), (5,3), (5,4), (6,2), (6,3), (6,4), thus the uppers of the input point is (6,3) and lowers is (4,2).

**Comment by gopinath-r** [comment]
Hi @zzzxxxttt 
Thanks for the reply. Can you please explain how did you calculate those output points corresponding to particular input and how is the formula for lower, upper bound has been derived?

**Comment by zzzxxxttt** [comment]
the output points for a given input point depends on the kernel size _k_, stride _s_, dilation _d_, and padding _p_

Let's use the 1-dim convolution as an example:

for an input position _x_, its distance to the featuremap border is _x+p_
suppose the minimum value of output point is _n_, which means we have the following relationship: _s*(n-1)+k'=x+p_
where _k'_ is the effective kernel size, it depends on kernel size and dilation: _k'=(k-1)*(d-1)+k_
thus the equation becomes: _s*(n-1)+(k-1)*(d-1)+k=x+p_
rearrange it and we get: _n=(x-d*(k-1)-1+s+p)/s_, which is the code for calculating ```lowers```

similarly, suppose the maximum value of output point is _n_, then we have the following relationship: _s*n=x+p_, thus _n=(x+p)/s_, which is the code for calculating ```uppers```.

**Comment by nerryINF** [comment]
Hi @zzzxxxttt , perfect explanation thank you!What about counter and pointCounter? Are they the relative indices of non empty points in grid with respect to the kernel position?
I'm not sure if this seems logical, I'm trying to make sense of getIndicePairsSubM function if you ever understood it, I'd be pleased to talk about it!

**Comment by ColdCodeCool** [comment]
@nerryINF  Hi, did you figure out the meaning of counter and pointCounter?

**Comment by Xiao-Hu-Z** [comment]
@nerryINF @zzzxxxttt Hi,Do you understand the meaning of counter clearly?
