### ISSUE TITLE
Tensorflow Implementation of spconv

### ISSUE THREAD

**Issue by arxidinakbar** [traveller59/spconv#228]
Hi, got so much inspiration from this work, appreciate！
And recently just working on sparse convolution in own project, just wondering is it implement on Tensorflow 2.X straightforward or there are example codes that i miss?
Expect for a proper answer from anybody, thank you.

Good luck

**Comment by xmyqsh** [comment]
@arxidinakbar

You can have a try with my [gpu_coords_map](https://github.com/xmyqsh/gpu_coords_map).

Best practice:
 https://github.com/NVIDIA/MinkowskiEngine/pull/220

What's news?
- Mapping as Indices
- Iteration as Query
- Iteration as Insertion
- Insertion as Query
In a word, minimize the memory allocate/copy/release.
And the sparse convolution kernel and pooling kernel could be optimized further in this paradium to get rid of(or reduce) random access in a wrap at input indices or output indices side(just one side).

What makes this possible?   The SlabHash based [gpu_coords_map](https://github.com/xmyqsh/gpu_coords_map) !

It is straightforward to implement it on tensorflow2.x. All the best tools have collected.
