### ISSUE TITLE
python setup.py bdist_wheel failed

### ISSUE THREAD

**Issue by hackkhai** [traveller59/spconv#229]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/hackkhai/anaconda3/lib/python3.8/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.8', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10501', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/hackkhai/spconv/build/lib.linux-x86_64-3.8/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 9.3.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/hackkhai/spconv/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/hackkhai/spconv/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    setup(
  File "/home/hackkhai/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hackkhai/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
    self.run_command('build')
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hackkhai/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 50, in run
    self.build_extension(ext)
  File "setup.py", line 93, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/hackkhai/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/hackkhai/spconv', '-DCMAKE_PREFIX_PATH=/home/hackkhai/anaconda3/lib/python3.8/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.8', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10501', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/hackkhai/spconv/build/lib.linux-x86_64-3.8/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by SiyuanHuang95** [comment]
have you solved this problem? I have met this problem, too

**Comment by hackkhai** [comment]
> have you solved this problem? I have met this problem, too

no, i haven't if you get a solution post it here, I will too.

**Comment by SiyuanHuang95** [comment]
The most strange thing for me is that the output of
```shell
nvida-smi
nvcc -V
```
are all correct, so really have no ideas about what happens.

**Comment by AravindG1508** [comment]
Hi, even I'm facing the same issue. I'm using a virtual machine(Ubuntu 16.04, cuda 10.0, cudnn 7.5, pytorch 1.3, latest cmake version). If you get solution to this issue please post it here. Thank you

**Comment by hedaniel7** [comment]
I am also facing the same issue

**Comment by SiyuanHuang95** [comment]
Later, I solved that problem when I update my Nvidia to 2080Ti, and re-install all the relevant dependencies, then all problems disappeared.

**Comment by triple-tam** [comment]
No CUDA is being found, probably because your current cmake installation did not install w.r.t. to your CUDA. I suggest installing another version of cmake (and you can specify a different path via $/.bootstrap --prefix=/your/path) while your desired CUDA is active (verify that via $nvcc --version or $which cuda). That way, when the cmake portion runs in the setup.py script, the cmake will find the desired CUDA.
