### ISSUE TITLE
 error: ‘kBool’ is not a member of ‘torch’

### ISSUE THREAD

**Issue by Looomo** [traveller59/spconv#232]
got  error  : ‘kBool’ is not a member of ‘torch’ when i run command sudo python setup.py bdist_wheel.
anyone plz help me ?
TKS!

![image](https://user-images.githubusercontent.com/29702226/94791352-15642200-040a-11eb-935d-c5cf786eecf8.png)

**Comment by ShiningDeadFishEyes** [comment]
current torch version: 1.3.1 , tried 1.0.0 1.4.x but didn't work
