### ISSUE TITLE
RuntimeError: CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by EthanZhangYi** [traveller59/spconv#233]
When the input voxel shape is [480 360 32], and the input feature shape is [36677, 32]. A SubMConv3d of kernel_size=5 will result in a error `RuntimeError: CUDA error: too many resources requested for launch`

**Comment by 0w0h0y** [comment]
I meet the same problem with SparseMaxPool3d of kernel_size=5 and subm=True. Have you solved the problem?
