### ISSUE TITLE
fatal: no submodule mapping found in .gitmodules for path 'third_party/cutlass' when git clone

### ISSUE THREAD

**Issue by cuge1995** [traveller59/spconv#237]

**Comment by Giofist** [comment]
Same issue with cuda 10 pytorch 36, fail the mapping.

**Comment by arxidinakbar** [comment]
Any solution here?  got same error when cloning, and checking the 'third_party/cutlass' found its a link file to another library..
PS: wondering what does that little badge means which showing [build failing], does it related to this error?

**Comment by Giofist** [comment]
i've just solved by cloning old commit by using:
```
git clone https://github.com/traveller59/spconv.git 
cd spconv 
git checkout 42d92ee
git submodule update --init --recursive
```

this works only if you need to run code without support for cuda 11.

**Comment by Giofist** [comment]
> Any solution here? got same error when cloning, and checking the 'third_party/cutlass' found its a link file to another library..
> PS: wondering what does that little badge means which showing [build failing], does it related to this error?

Yes that red badge is linked to code taht automatically build a Docker with the repo code, basically it fails due to this error. If you go back to the previous commit as i've done no problem arise.

**Comment by arxidinakbar** [comment]
@Giofist  Hi, thanks for the tip. I would try your solution.
And in my case was tried to install on ubuntu16.04 with CUDA 10.1 version.
I've installed spconv successfully the other day, somehow failed this time, might be the official problem it is.

**Comment by cuge1995** [comment]
the solution is `git clone -b develop https://github.com/traveller59/spconv.git --recursive`

**Comment by arxidinakbar** [comment]
@cuge1995  download was done with your solution, but the new problem encountered when runnig python seup.py bdist_wheel.
the main line as below:
`File "/home/omnisky/anaconda3/envs/second/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.` 

so could you please list your concrete installation steps, especially the CMAKE installation. I'm installed cmake directly with conda, I'm thinking something go wrong with CMAKE installation, thank!

**Comment by arxidinakbar** [comment]
Solve the error in my last commit with installing pytorch 1.3.0; 
The git clone problem solution as above disscussion;
### configurations:
python=3.7.0
pytorch=1.3.0          # the most important one, has to be 1.3.0 version
torchvision=0.4.0     # if you use conda install, it would install the version suits your pytorch.
CUDA 10.1
cmake=3.13.2  # I used conda install, NO need for PATH adding. And make sure it is the same version.

**Comment by Chuanbo-Yu** [comment]
> Solve the error in my last comment with installing pytorch 1.3.0;
> The git clone problem solution as above disscussion;
> ### configurations:
> 
> python=3.7.0
> pytorch=1.3.0 # the most important one, has to be 1.3.0 version
> torchvision=0.4.0 # if you use conda install, it would install the version suits your pytorch.
> CUDA 10.1
> cmake=3.13.2 # I used conda install, NO need for PATH adding. And make sure it is the same version.
  

Excuse me, I also havee installed spconv successfully the other day. But, it have errors as you, and I followed your configurations. However, there still have problems. Could you give me some suggestions
  File "setup.py", line 49, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/ycb/anaconda3/envs/PV-RCNN/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ycb/spconv', '-DCMAKE_PREFIX_PATH=/home/ycb/anaconda3/envs/PV-RCNN/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10300', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ycb/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by Chuanbo-Yu** [comment]
> @Giofist Hi, thanks for the tip. I would try your solution.
> And in my case was tried to install on ubuntu16.04 with CUDA 10.1 version.
> I've installed spconv successfully the other day, somehow failed this time, might be the official problem it is.

Like you, I successfully configured it a month ago, but there were various problems when I reconfigured the system two days ago. So far, they haven't been solved. Can you add me wechat（ycb2468）

**Comment by Chuanbo-Yu** [comment]
> the solution is `git clone -b develop https://github.com/traveller59/spconv.git --recursive`

I successfully configured it a month ago, but there were various problems when I reconfigured the system two days ago. So far, they haven't been solved. Can you add me wechat（ycb2468），I want to ask some questions.
