### ISSUE TITLE
#error This file requires compiler and library support  for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### ISSUE THREAD

**Issue by jihong111** [traveller59/spconv#24]

**Comment by defypp** [comment]
@traveller59 follow your install instrcutions, I got same error. And I guess its about c++11, so I add c++11 support in CMakeList file. But I got nvcc error , "redefination of std". so, could you tell us which version of gcc in your env ? Most of the problems may come from env.

**Comment by jihong111** [comment]
@defypp  I got the same result as you 、

**Comment by jiangzhengkai** [comment]
Any idea?

**Comment by jiangzhengkai** [comment]
@defypp @jihong111 only to upgrade gcc
