### ISSUE TITLE
cannot import name 'rbbox_intersection' from 'spconv.utils' 

### ISSUE THREAD

**Issue by GYE19970220** [traveller59/spconv#243]
After installing spconv, I test it in python interpreter.
The code is `from spconv.utils import rbbox_intersection`,but it report an error **cannot import name 'rbbox_intersection' from 'spconv.utils'** .I follow the instruction in #41 and #63 ,but they don't work for me.I use both spconv and spconv_8da6f96 (in #152)
to have a try,they report the same error.Any ideas would be appreciated

**Comment by GYE19970220** [comment]
The version of second.pytorch is wrong.When I change its version to 1.5.1,it was solved.

**Comment by urbansound8K** [comment]
i am having the same error? 
could you please help me? 


how did you change the version?
