### ISSUE TITLE
Sparse layers in the middle of the network? 

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [traveller59/spconv#244]
Thanks for the repo!

I am playing with the repo and try to only specify part of the layers to be sparse. For example, I want to have a network that looks like:

>                    dense_conv, 
>                    dense_relu, 
>                    (to_sparse layer), // call spconv.SparseConvTensor.from_dense()  
>                    sparse_conv, 
>                    sparse_relu,
>                    to_dense, 

When I try to run the above network, it shows derivative for to_sparse are not supported. Any suggestions for quick fix? Thanks in advance!

**Comment by charliememory** [comment]
In my case, I make it work by creating the sparse tensor manually instead of call from_dense().
`x = spconv.SparseConvTensor(sparse_feat_batch, sparse_coord_batch, (H,W), N)`

**Comment by caoyifeng001** [comment]
Has the problem been solved @LiuXiaoxuanPKU
