### ISSUE TITLE
Hi, a question about indice_key

### ISSUE THREAD

**Issue by Ultra11nstinct** [traveller59/spconv#246]
Hi, i wanna know whats the meaning of indice_key, such as "subm0", "subm1"......

**Comment by Chuanbo-Yu** [comment]
> Hi, i wanna know whats the meaning of indice_key, such as "subm0", "subm1"......
Hello, may I ask if you have successfully configured the environment. I successfully configured some time ago, but failed to be single these two days. I'd like to know how you configure it. Add a wechat（ycb2468） if it's convenient
