### ISSUE TITLE
python  setup.py  bdist_wheel  

### ISSUE THREAD

**Issue by luzonghao1** [traveller59/spconv#248]
**_ubuntu 18
Guest user install cuda10（success installed）cudnn
spconv1.0_**  

running bdist_wheel
running build
running build_py
running build_ext
/home/lzh/3dcode/spconv_8da6f96/build/lib.linux-x86_64-3.6
Release
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 9.1.85
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
**_-- Found CUDA: /usr (found version "9.1")
-- Caffe2: CUDA detected: 9.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc_**
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 9.1
-- Found CUDNN: /home/lzh/cudalib/cuda/include/
-- Found cuDNN: v7.4.2  (include: /home/lzh/cudalib/cuda/include/, library: /home/lzh/cudalib/cuda/lib64/)
-- Autodetected CUDA architecture(s):  7.5 7.5 7.5 7.5 7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /home/lzh/anaconda3/envs/spconv/lib/python3.6/site-packages/torch/lib/libtorch.so
-- Found PythonInterp: /home/lzh/anaconda3/envs/spconv/bin/python3.6 (found suitable version "3.6.12", minimum required is "3.6")
-- Found PythonLibs: /home/lzh/anaconda3/envs/spconv/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lzh/3dcode/spconv_8da6f96/build/temp.linux-x86_64-3.6
Scanning dependencies of target spconv_nms
Scanning dependencies of target spconv
[  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 14%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 21%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 28%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
Segmentation fault (core dumped)
src/utils/CMakeFiles/spconv_nms.dir/build.make:62: recipe for target 'src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o' failed
make[2]: *** [src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o] Error 139
CMakeFiles/Makefile2:165: recipe for target 'src/utils/CMakeFiles/spconv_nms.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_nms.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 42%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
Segmentation fault (core dumped)
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cu.o] Error 139
make[2]: *** Waiting for unfinished jobs....
Segmentation fault (core dumped)
src/spconv/CMakeFiles/spconv.dir/build.make:114: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cu.o] Error 139
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    zip_safe=False,
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 71, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lzh/anaconda3/envs/spconv/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by luzonghao1** [comment]
I have install cuda10.0 in my local directory，and hava the right config.when run which nvcc is /home/lzh/cudalib/cuda10/bin/nvcc。

**Comment by tojimahammatov** [comment]
Have you tried to set path of your cuda in ~/.bashrc? and your logs are saying that you have CUDA 9.1. Maybe you should try to remove the other.
