### ISSUE TITLE
Tensorrt Inference

### ISSUE THREAD

**Issue by Hyeokreal** [traveller59/spconv#250]
Thanks for your awesome repository.

Considering there are tensorrt inference cpp files in "include/tensorrt/inference.h", It seems that spconv is also available for tensorrt inference.

Could you share how did you make tensorrt engine file of spconv ?
Export spconv to onnx format seems not easy to me.

**Comment by tzhong518** [comment]
Same question here

**Comment by gutianchang** [comment]
臣附议。另外关于找工作的事情已经给您发了一封邮件，期待您的回复！

**Comment by roymerry** [comment]
Same question here...
