### ISSUE TITLE
spconv/include/spconv/box_iou.h:21:10: fatal error: boost/geometry.hpp: No such file or directory  #include <boost/geometry.hpp>

### ISSUE THREAD

**Issue by StiphyJay** [traveller59/spconv#251]
i follow your step and also install the boost library by the commond: sudo apt-get install libboost-all-dev. However, When i use python setup.py bdist_wheel qu build the spconv, i meet the following error.

-- Generating done
-- Build files have been written to: /home/sifan/slam-package/object_detection/OpenPCDet/third_party/spconv/build/temp.linux-x86_64-3.7
[  8%] Built target spconv_nms
[ 33%] Built target cuhash
[ 37%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 41%] Building CXX object src/spconv/CMakeFiles/spconv.dir/nms.cc.o
/home/sifan/slam-package/object_detection/OpenPCDet/third_party/spconv/src/spconv/nms.cc:15:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:115: src/spconv/CMakeFiles/spconv.dir/nms.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
In file included from /home/sifan/slam-package/object_detection/OpenPCDet/third_party/spconv/src/utils/all.cc:15:0:
/home/sifan/slam-package/object_detection/OpenPCDet/third_party/spconv/include/spconv/box_iou.h:21:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/build.make:63: src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:240: src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):

What should i do to solve this error. I would appreciate it if you could reply.

**Comment by yzheng97** [comment]
You should install libboost-dev

**Comment by g1910** [comment]
What to do when boost is setup locally? I don't have sudo on the university server.

**Comment by GunjanKholapure** [comment]
I installed boost with conda and added its path in setup.py file (last line argument -DCMAKE_CXX_FLAGS:STRING=-I) : 
def build_extension(self, ext):
        extdir = os.path.abspath(os.path.dirname(self.get_ext_fullpath(ext.name)))
        cmake_args = [# '-G "Visual Studio 15 2017 Win64"',
                      '-DCMAKE_PREFIX_PATH={}'.format(LIBTORCH_ROOT),
                      '-DPYBIND11_PYTHON_VERSION={}'.format(PYTHON_VERSION),
                      '-DSPCONV_BuildTests=OFF',
                      '-DPYTORCH_VERSION={}'.format(PYTORCH_VERSION_NUMBER),
                      '-DCMAKE_CXX_FLAGS:STRING=-I /path_to_anaconda3/envs/env_name/include',  
                      ]

This worked for me

**Comment by ajinkyakhoche** [comment]
Hi @GunjanKholapure , thanks a lot, your solution worked to compile spconv, but when I tried to build Det3d, I still get the error:

`Det3D/det3d/ops/nms/nms_cpu.h:9:10: fatal error: boost/geometry.hpp: No such file or directory
 #include <boost/geometry.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.`

is there a way to specify the same flags in [setup.py](https://github.com/poodarchu/Det3D/blob/master/setup.py) file of Det3D?
