### ISSUE TITLE
Segmentation fault on mnist_sparse.py

### ISSUE THREAD

**Issue by nicholasturner1** [traveller59/spconv#255]
I've successfully installed this package, but I immediately get a segfault when trying to run the example. I do NOT get a segfault when running the example on the CPU (--no-cuda). 

I've tried tracking down the point when the segfault happens, and it seems to be related to generating the index pairs (somewhere around `create_conv_indice_pair_p2_cuda`).
https://github.com/traveller59/spconv/blob/master/src/spconv/indice.cu#L94
Which is called from python here
https://github.com/traveller59/spconv/blob/f22dd9aee04e2fe8a9fe35866e52620d8d8b3779/spconv/ops.py#L91

I'll continue searching, but is this example working for other people?

For reference, I'm using:
python 3.8.3, pytorch 1.7, cmake 8.0.4

**Comment by nicholasturner1** [comment]
I also see the same behavior using pytorch 1.6 (the same version as the docker image)

**Comment by Jegp** [comment]
Similar to #245 I assume. So, no it's not working for me either.

**Comment by cattaneod** [comment]
What OS are you using?

spconv is working fine in 4 different PCs with ubuntu 18.04, but I'm getting seg fault on ubuntu 20.04, maybe it's related to that?

**Comment by nicholasturner1** [comment]
Interesting... I'm working with 16.04 at the moment. I'll try a docker image with 18.04 and see what happens.

**Comment by nicholasturner1** [comment]
That worked! This is actually tolerable for me since I was hoping to run this in a docker container anyway. Thanks @cattaneod and @Jegp!
