### ISSUE TITLE
python setup.py bdist_wheel

### ISSUE THREAD

**Issue by Cheng-11** [traveller59/spconv#258]
the environment is ubuntu 18.04, cuda10.2, python3.7.9, torch 1.4.0, cmake version 3.13.2 , gcc 7.5.0

The output was:

running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/user/anaconda3/envs/cen3d/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/user/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /opt/cmake-3.13.2/share/cmake-3.13/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_e8d70/fast"
    /usr/bin/make -f CMakeFiles/cmTC_e8d70.dir/build.make CMakeFiles/cmTC_e8d70.dir/build
    make[1]: 进入目录“/home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp”
    Building CUDA object CMakeFiles/cmTC_e8d70.dir/main.cu.o
    /usr/bin/nvcc    "--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__    -x cu -c /home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_e8d70.dir/main.cu.o
    fatbinary warning : option 'cuda' has been deprecated
    In file included from /tmp/tmpxft_000008fd_00000000-5_main.cudafe1.stub.c:6:0,
                     from tmpxft_000008fd_00000000-5_main.cudafe1.stub.c:1:
    /tmp/tmpxft_000008fd_00000000-2_main.fatbin.c:2:31: fatal error: fatbinary_section.h: 没有那个文件或目录
     #include "fatbinary_section.h"
                                   ^
    compilation terminated.
    CMakeFiles/cmTC_e8d70.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_e8d70.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_e8d70.dir/main.cu.o] Error 1
    make[1]: 离开目录“/home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp”
    Makefile:121: recipe for target 'cmTC_e8d70/fast' failed
    make: *** [cmTC_e8d70/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!
See also "/home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/user/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/user/anaconda3/envs/cen3d/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/user/spconv', '-DCMAKE_PREFIX_PATH=/home/user/anaconda3/envs/cen3d/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/user/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

What should i do to solve this error. I would appreciate it if you could reply.

**Comment by oreo-lp** [comment]
me too!

**Comment by hedaniel7** [comment]
me too!

**Comment by xjtu-www** [comment]
I also have this problem on sever(ubuntu16.04, v100 gpu), but there is no problem on my local machine(ubuntu18.04, 1080ti gpu). It is weird that the CUDA compiler is "/usr/bin/nvcc", because I installed my cuda on /usr/local/cuda-10.1. And I tried to link the /usr/bin/nvcc to /usr/local/cuda-10.1/bin/nvcc, it still didn't work. Any suggestions are welcome.

**Comment by xjtu-www** [comment]
I've solved this problem by adding `set(CMAKE_CUDA_COMPILER /usr/local/cuda-10.0/bin/nvcc)` to the CMakeLists.txt file. The path should be modified according to your own cuda path. Hope this could help you.

**Comment by triple-tam** [comment]
I had a similar issue. The program is likely finding `/usr/bin/nvcc` instead of a different cuda (like the one you want) because the cmake that you're using was built with respect to `/usr/bin/nvcc` instead of your different cuda. 

If you want the program to find a different cuda version:
- add that cuda version to the  necessary paths (like PATH, CUDA_HOME, etc)
- verify correct cuda via $nvcc --version and $which cuda
- download cmake.tar.gz from the cmake website
- unzip and install the cmake ($tar -xf cmake.tar.gz, $cd cmake, $./bootstrap --prefix=/your/path, $make, $make install)
- add /your/path/cmake/bin to PATH
- verify new cmake is active ($which cmake)
- $python setup.py bdistwheel should now be using a different cuda version
