### ISSUE TITLE
The CUDA compiler "/usr/bin/nvcc" is not able to compile a simple test program.

### ISSUE THREAD

**Issue by yustaub** [traveller59/spconv#259]
Hi , sir. the version of cmake of my server is 3.5.1, cuda9.0, and I have no root, I download cmake3.13.4 in my home directory and install it, when I type "cmake --version", it shows 3.13.4, but when I run `python setup.py bdist_wheel`, it still error.
## error info:
`Release
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /home/yuwentao/cmake/share/cmake-3.13/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_2641c/fast"
    /usr/bin/make -f CMakeFiles/cmTC_2641c.dir/build.make CMakeFiles/cmTC_2641c.dir/build
    make[1]: Entering directory '/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_2641c.dir/main.cu.o
    /usr/bin/nvcc    "--expt-relaxed-constexpr"    -x cu -c /home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_2641c.dir/main.cu.o
    Internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r384/r384_00/drivers/compiler/edg/EDG_4.12/src/cmd_line.c", line 10726

    1 catastrophic error detected in this compilation.
    Compilation aborted.
    Aborted (core dumped)
    CMakeFiles/cmTC_2641c.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_2641c.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_2641c.dir/main.cu.o] Error 134
    make[1]: Leaving directory '/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_2641c/fast' failed
    make: *** [cmTC_2641c/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/yuwentao/project/CenterPoint/spconv-8da6f967fb9a054d8870c3515b1b44eca2103634/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_PREFIX_PATH=/home/yuwentao/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`
Is there any suggestion about this? Very appreciate for your reply

**Comment by twn29004** [comment]
I have the same probelm, how did you slove it
