### ISSUE TITLE
compile error in aarch64 platform

### ISSUE THREAD

**Issue by muzi2045** [traveller59/spconv#26]
I am trying to compile spconv in Linux aarch64 platform, But the error occur when compileing
![image](https://user-images.githubusercontent.com/12984898/54598122-d57d5a00-4a72-11e9-89a6-3bca9667358d.png)

it looks like the pytorch lib is incomplete, 
Ubuntu 18.04 LTS + python3.6 + CUDA10.0 + cmake3.14.0
everything going fine in my x86 PC platform with the same code.
hopefully for any advice, thanks!

**Comment by traveller59** [comment]
What's your torch version? This project only support torch >= 1.0. I have test spconv in torch 1.0 and 1.0.1.

**Comment by muzi2045** [comment]
I install the torch == 1.0.0, but it was a prebuilt wheel file released by Nvidia, here is the link:
https://devtalk.nvidia.com/default/topic/1041716/jetson-agx-xavier/pytorch-install-problem-solved-/post/5284880/#5284880
I have tried to compile torch source code in the Jetson Xavier Platform, but it failed.
there seems like some problem in CUDA10 with torch.. @traveller59

**Comment by muzi2045** [comment]
I have tried to compile torch from source in aarch64 platform .
it worked.
