### ISSUE TITLE
Tensorrt plugin for get_indice_pairs

### ISSUE THREAD

**Issue by tzhong518** [traveller59/spconv#260]
@traveller59 Hi, thank you for your work!
I want to deploy a model using spconv.

1. I registered the custom ops(get_indice_pairs, SubMConv, SparseConv, SparseInverseConv) and exported the onnx model.
2. I'm trying to write Tensorrt plugins.
But Tensorrt plugin needs to predefine the output's dimension, while the output dimension of get_indice_pairs seems to be data-dependent, which is not supported by tensorrt yet.

Am I understanding it right? Is there any workround to deploy spconv? 
Thank you in advance.

**Comment by Swetap24** [comment]
Hey,

@tzhong518 Can you please help on how did you register all the custom ops and exported the onnx model?

Thanks

**Comment by gillbam** [comment]
> Hey,
> 
> @tzhong518 Can you please help on how did you register all the custom ops and exported the onnx model?
> 
> Thanks

Hey @Swetap24,

have you figured out how to register those custom ops for exporting onnx models?

Thanks

**Comment by zerollzeng** [comment]
I also stuck at export spconv to onnx, any hint? @tzhong518 

Appreciate your help, thanks in advance.

**Comment by xiaoxifuhongse** [comment]
@tzhong518 solved it now? need help

**Comment by sandeepnmenon** [comment]
@tzhong518 Were you able to do this? I am trying the same direction
