### ISSUE TITLE
RuntimeError:  .../spconv/src/spconv/indice.cu 274 cuda initialization error

### ISSUE THREAD

**Issue by AAArielo** [traveller59/spconv#262]
First,thank you for all contributions, the following are the problems I encountered

RuntimeError:  .../spconv/src/spconv/indice.cu 274
cuda execution failed with error 3 initialization error
prepareSubMGridKernel failed

Any ideas can help me improve this?

PyTorch Version : 1.7
CudNN version : 7.6
Cuda version : 10.2

**Comment by AdelAdham** [comment]
I had the same problem while running on GTX 1080ti with CUDA 10.2 & Driver 440.* & PyTorch 1.7 I tried million things but none worked, the issue finally disappeared when I tried on RTX 2080ti with CUDA 11.0 & driver 450.51.06 & PyTorch 1.7, so maybe you can try to upgrade your CUDA version and driver.

**Comment by tung-nd** [comment]
I got exactly the same problem. Is there any solution for this yet?

**Comment by wjj31767** [comment]
I've reinstalled spconv and it works
