### ISSUE TITLE
convert spconv pytorch to tensorRT use torch2trt

### ISSUE THREAD

**Issue by lunlun123** [traveller59/spconv#273]
i do tensorrt inference with python API.  only add plugin create. spconv main process(like getindicepairs，indconv...) have no change. when inference, tensorRT context execute_async spend more time than pytorch inference. Is this normal？？

2080ti，voxelnet of centerpoint network , pytorch time ： 60ms ;   tensorRT time :  65ms

thanks for your help!

**Comment by tzhong518** [comment]
Hi, could you share how you convert the plugin?
Are the results the same?

**Comment by xiaoxifuhongse** [comment]
Hi, could you share how you convert the plugin?
Are the results the same?

**Comment by PHaiJun** [comment]
wish your experience about spconv to tensorrt by torch2trt
