### ISSUE TITLE
CMake Generate step failed.  Build files cannot be regenerated correctly.

### ISSUE THREAD

**Issue by swetapriyadarshi** [traveller59/spconv#281]
I am getting the above error, when trying to run python setup.py bdist_wheel.

I am using Ubuntu 18.04, cuda 10.2 and cudnn 8.0.3.

![image](https://user-images.githubusercontent.com/37204536/107265253-0aea1280-6a12-11eb-8a41-124f969bc032.png)

**Comment by swetapriyadarshi** [comment]
I have also tried checking cudnn installation and cublas suggested on other pages but that doesn't seem to work.

**Comment by tianweiy** [comment]
what is your torch's cuda version. Is it 10.2? This needs to match with your local cuda version to build spconv

**Comment by swetapriyadarshi** [comment]
Yes my torch version is 10.2.

**Comment by RolandoAvides** [comment]
Hi there!

I'm also having this error. I'm using CUDA 11.0.

**Comment by lucky-fzy** [comment]
> I am getting the above error, when trying to run python setup.py bdist_wheel.
> 
> I am using Ubuntu 18.04, cuda 10.2 and cudnn 8.0.3.
> 
> ![image](https://user-images.githubusercontent.com/37204536/107265253-0aea1280-6a12-11eb-8a41-124f969bc032.png)

have you solved this problem? I have met this problem, too

**Comment by ReunionJ** [comment]
Have you solved this error? I face with same problem!

**Comment by RolandoAvides** [comment]
> Have you solved this error? I face with same problem!

What install steps did you follow?
