### ISSUE TITLE
spconv.tables usage for building UNet

### ISSUE THREAD

**Issue by vaibhavnayel** [traveller59/spconv#282]
Thanks for the great library!

How is one supposed to use the jointable function for building a 3D Unet? Currently I'm using SparseConv3d followed by SparseMaxPool3d in the encoder and SparseConvTranspose3d for upsampling followed by concatenation + SparseConv3d in the decoder. But when I try to use jointable to combine the encoder features with the upsampled features in the decoder, I get index errors. 

I suppose this is because different indices are occupied by the 2 feature maps, so jointable can't concatenate them along the feature axis. The README states that table functions are meant to be used to construct Unet and Resnet modules. Can you give a short example of the correct usage?

**Comment by FrancescoMandru** [comment]
Hey did you solve your issue? I'm also interested in what are you doing, can you share your code example?

**Comment by harry1576** [comment]
Did you have any luck? 
Would be interested to see your code.
Cheers
