### ISSUE TITLE
Is this library convertible with TensorRT?

### ISSUE THREAD

**Issue by timelapse3502** [traveller59/spconv#283]
I seem to get conflicting information from the discussions in this repo. Could someone give me a definitive answer?

**Comment by owoshch** [comment]
Hi @timelapse3502! Any updates on that?

**Comment by traveller59** [comment]
@owoshch spconv 2.0 with int8/tensor core and tensorrt support will be released before 10.1 2021

**Comment by PhoenVujih** [comment]
Can't wait to see spconv 2.0! Any change on the release date of it? @traveller59 

> spconv 2.0 with int8/tensor core and tensorrt support will be released before 10.1 2021

**Comment by YoushaaMurhij** [comment]
Any updates on tensorrt?

**Comment by FindDefinition** [comment]
@YoushaaMurhij 
TensorRT support need following prerequisites that aren't started yet:
* Convert all python code in ```spconv.pytorch.ops``` to c++
* pytorch int8 inference/QAT support (optional)
* torch.fx based converter
* C++-only spconv core build.
Still lots of engineering work to do.

**Comment by YoushaaMurhij** [comment]
@traveller59 Thanks for your answer!

**Comment by LexcaliburR** [comment]
I'm trying to deploying model with sparsconvlution3d. My method is that
1. convert torch.model to onnx
2. write tensorRT plugin
3. parser and infer

But when i export ONNX model, find that sparsConv is not convertable. Because unsupportable ops. In my opinon need i modify source code and register in "symbolic_function" in pytorch. I want to know is it the best way to deploy model in tensorRT, or do you have any other advices?

Thanks for lot

**Comment by sandeepnmenon** [comment]
> I'm trying to deploying model with sparsconvlution3d. My method is that
> 
> 1. convert torch.model to onnx
> 2. write tensorRT plugin
> 3. parser and infer
> 
> But when i export ONNX model, find that sparsConv is not convertable. Because unsupportable ops. In my opinon need i modify source code and register in "symbolic_function" in pytorch. I want to know is it the best way to deploy model in tensorRT, or do you have any other advices?
> 
> Thanks for lot

@LexcaliburR Did you manage to do this? I am looking for the TRT plugin to do the sparse convolutioin

**Comment by ArseniuML** [comment]
> torch.fx based converter

@FindDefinition do you mean that I need to use Torch-TensorRT (not ONNX)?
