### ISSUE TITLE
erro python setup.py bdist_whell   

### ISSUE THREAD

**Issue by twn29004** [traveller59/spconv#288]
### environment
CUDA 10.0
CMake == 3.18.4
python == 3.6.13
gcc == 7.3.0

I have trid all the instructions in the repo of issues. Anyone can help me.  plz

### log
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lyc/data/twn/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
-- Found cuDNN: v7.6.2  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
CMake Warning (dev) at /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  8.6
-- Found PythonInterp: /home/lyc/data/anaconda3/envs/twn/bin/python3.6 (found suitable version "3.6.13", minimum required is "3.6") 
-- Found PythonLibs: /home/lyc/data/anaconda3/envs/twn/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/cuhash/CMakeLists.txt:4 (add_library):
  Cannot generate a safe runtime search path for target cuhash because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/lyc/data/twn/spconv/build/temp.linux-x86_64-3.6
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_86'
make[2]: *** [src/utils/CMakeFiles/spconv_nms.dir/build.make:82：src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:259：src/utils/CMakeFiles/spconv_nms.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 12%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 16%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
nvcc fatal   : Unsupported gpu architecture 'compute_86'
nvcc fatal   : Unsupported gpu architecture 'compute_86'
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/build.make:82：src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/build.make:108：src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:178：src/cuhash/CMakeFiles/cuhash.dir/all] 错误 2
make: *** [Makefile:149：all] 错误 2
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    zip_safe=False,
  File "/home/lyc/data/anaconda3/envs/CenterNet/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lyc/data/anaconda3/envs/CenterNet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 104, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
`

**Comment by kely11** [comment]
> ### environment
> CUDA 10.0
> CMake == 3.18.4
> python == 3.6.13
> gcc == 7.3.0
> 
> I have trid all the instructions in the repo of issues. Anyone can help me. plz
> 
> ### log
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.6
> creating build/lib.linux-x86_64-3.6/spconv
> copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/**init**.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/tables.py -> build/lib.linux-x86_64-3.6/spconv
> copying spconv/identity.py -> build/lib.linux-x86_64-3.6/spconv
> creating build/lib.linux-x86_64-3.6/spconv/utils
> copying spconv/utils/**init**.py -> build/lib.linux-x86_64-3.6/spconv/utils
> running build_ext
> Release
> |||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10400', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lyc/data/twn/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
> -- The CXX compiler identification is GNU 7.5.0
> -- The CUDA compiler identification is NVIDIA 10.0.130
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting CUDA compiler ABI info
> -- Detecting CUDA compiler ABI info - done
> -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
> -- Detecting CUDA compile features
> -- Detecting CUDA compile features - done
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Found CUDA: /usr/local/cuda (found version "10.0")
> -- Caffe2: CUDA detected: 10.0
> -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda
> -- Caffe2: Header version is: 10.0
> -- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
> -- Found cuDNN: v7.6.2 (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
> -- Autodetected CUDA architecture(s): 8.6
> -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
> CMake Warning (dev) at /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
> The package name passed to `find_package_handle_standard_args` (torch) does
> not match the name of the calling package (Torch). This can lead to
> problems in calling code that expects `find_package` result variables
> (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
> /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:122 (find_package_handle_standard_args)
> CMakeLists.txt:22 (find_package)
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Found torch: /home/lyc/data/anaconda3/envs/twn/lib/python3.6/site-packages/torch/lib/libtorch.so
> -- Autodetected CUDA architecture(s): 8.6
> -- Found PythonInterp: /home/lyc/data/anaconda3/envs/twn/bin/python3.6 (found suitable version "3.6.13", minimum required is "3.6")
> -- Found PythonLibs: /home/lyc/data/anaconda3/envs/twn/lib/libpython3.6m.so
> -- Performing Test HAS_CPP14_FLAG
> -- Performing Test HAS_CPP14_FLAG - Success
> -- pybind11 v2.5.0
> -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> -- Found OpenMP: TRUE (found version "4.5")
> -- Configuring done
> CMake Warning (dev) in src/cuhash/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "cuhash".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/cuhash/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "cuhash".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning at src/cuhash/CMakeLists.txt:4 (add_library):
> Cannot generate a safe runtime search path for target cuhash because files
> in some directories may conflict with libraries in implicit directories:
> 
> ```
> runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>   /usr/local/cuda/lib64
> ```
> 
> Some of these libraries may not be found correctly.
> 
> CMake Warning (dev) in src/spconv/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "spconv".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/spconv/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "spconv".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
> Cannot generate a safe runtime search path for target spconv because files
> in some directories may conflict with libraries in implicit directories:
> 
> ```
> runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>   /usr/local/cuda/lib64
> ```
> 
> Some of these libraries may not be found correctly.
> 
> CMake Warning (dev) in src/utils/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "spconv_nms".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in src/utils/CMakeLists.txt:
> Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
> empty CUDA_ARCHITECTURES not allowed. Run "cmake --help-policy CMP0104"
> for policy details. Use the cmake_policy command to set the policy and
> suppress this warning.
> 
> CUDA_ARCHITECTURES is empty for target "spconv_nms".
> This warning is for project developers. Use -Wno-dev to suppress it.
> 
> -- Generating done
> -- Build files have been written to: /home/lyc/data/twn/spconv/build/temp.linux-x86_64-3.6
> Scanning dependencies of target cuhash
> Scanning dependencies of target spconv_nms
> [ 4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
> nvcc fatal : Unsupported gpu architecture 'compute_86'
> make[2]: *** [src/utils/CMakeFiles/spconv_nms.dir/build.make:82：src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o] 错误 1
> make[1]: *** [CMakeFiles/Makefile2:259：src/utils/CMakeFiles/spconv_nms.dir/all] 错误 2
> make[1]: *** 正在等待未完成的任务....
> [ 8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
> [ 12%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
> [ 16%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
> [ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
> nvcc fatal : Unsupported gpu architecture 'compute_86'
> nvcc fatal : Unsupported gpu architecture 'compute_86'
> make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/build.make:82：src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] 错误 1
> make[2]: *** 正在等待未完成的任务....
> make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/build.make:108：src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] 错误 1
> make[1]: *** [CMakeFiles/Makefile2:178：src/cuhash/CMakeFiles/cuhash.dir/all] 错误 2
> make: *** [Makefile:149：all] 错误 2
> Traceback (most recent call last):
> File "setup.py", line 120, in
> zip_safe=False,
> File "/home/lyc/data/anaconda3/envs/CenterNet/lib/python3.6/site-packages/setuptools/**init**.py", line 153, in setup
> return distutils.core.setup(**attrs)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 955, in run_commands
> self.run_command(cmd)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/home/lyc/data/anaconda3/envs/CenterNet/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
> self.run_command('build')
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/command/build.py", line 135, in run
> self.run_command(cmd_name)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "setup.py", line 48, in run
> self.build_extension(ext)
> File "setup.py", line 104, in build_extension
> subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
> File "/home/lyc/data/anaconda3/envs/twn/lib/python3.6/subprocess.py", line 311, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
> `

Has this problem been solved? How to solve it ?
