### ISSUE TITLE
Block meaning

### ISSUE THREAD

**Issue by FrancescoMandru** [traveller59/spconv#293]
I found so many different blocks here but no documentation explaining the differences:

https://github.com/traveller59/spconv/blob/master/spconv/conv.py

**Comment by viplix3** [comment]
@FrancescoMandru all the blocks are inheriting and calling the functions of the same class i.e. [SparseConvolution](https://github.com/traveller59/spconv/blob/fad3000249d27ca918f2655ff73c41f39b0f3127/spconv/conv.py#L52). The differentiating factor is the parameters being passed when invoking the ```__init__``` of the inherited class.

All the blocks are providing different parameters when invoking ```__init__``` of inherited class hence will be following a different layer execution flow depending on the parameters passed.
