### ISSUE TITLE
ImportError: cannot import name 'spconv_utils' from 'spconv' (/working_dir/spconv/__init__.py)

### ISSUE THREAD

**Issue by FrancescoMandru** [traveller59/spconv#294]
my working dir is my local directory mapped inside docker. Ehat is spcon_utils? it does not exist

**Comment by loinhahaha** [comment]
I met same issue.
Have you fixed that?

**Comment by loinhahaha** [comment]
I solved it by the following two steps:

python setup.py bdist_wheel
cd ./dist && pip install xxx.whl

**Comment by FrancescoMandru** [comment]
I solved (maybe) building everything again from scratch
