### ISSUE TITLE
compile error：namespace "std" has no member "conditional_t"

### ISSUE THREAD

**Issue by nyg2017** [traveller59/spconv#3]
Thanks for your job！
 I made an error when I compiling spconv lib.
The details about My env are as follow：

g++ version= 5.4.0
cmake version=3.13.3
torch=1.0
python=3.6

The error message is as follow
 
![1111111111111111111](https://user-images.githubusercontent.com/28552589/51466505-5555b380-1da5-11e9-9e85-4bdfdcbed957.png)

I tried to solve this problem, but still no results. And can you tell me your g++ version?
Thanks!

**Comment by traveller59** [comment]
you need cuda 9.0+, or change all ```std::xxx_t<T>``` to ```typename std::xxx<T>::type```. the std::xxx_t need c++ 14 support of nvcc.

**Comment by mengmeng716** [comment]
ello, I have a the same problem, I tried to change all std::xxx_t<T> to typename std::xxx<T>::type, but it didn't work. Is there any other solution for that please? the result of execution is as followed: sorry for the paste, it's too long~

qmm@qmm-B250-HD3:~/Documents/project/spconv$ python setup.py install
running install
running bdist_egg
running egg_info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing top-level names to spconv.egg-info/top_level.txt
reading manifest file 'spconv.egg-info/SOURCES.txt'
writing manifest file 'spconv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
/home/qmm/Documents/project/spconv/build/lib.linux-x86_64-3.6
Release
-- Caffe2: CUDA detected: 8.0.61
-- Caffe2: CUDA nvcc is: /usr/local/cuda-8.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-8.0
-- Caffe2: Header version is: 8.0
-- Found cuDNN: v6.0.21  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qmm/Documents/project/spconv/build/temp.linux-x86_64-3.6
[ 21%] Built target spconv_nms
[ 28%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 35%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 42%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(311): error: namespace "std" has no member "conditional_t"

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(311): error: expected a ";"

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(381): error: namespace "std" has no member "conditional_t"

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(381): error: expected a ";"

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(32): error: namespace "std" has no member "conditional_t"

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(32): error: expected a ";"

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(85): error: namespace "std" has no member "conditional_t"

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(85): error: expected a ";"

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(322): error: "auto" is not allowed here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(330): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, int)

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(329): error: no instance of function template "spconv::maxPoolFwdVecBlockKernel" matches the argument list
            argument types are: (float *, const float *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(459): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(340): error: no instance of function template "spconv::maxPoolFwdGenericKernel" matches the argument list
            argument types are: (float *, const float *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(459): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(393): error: "auto" is not allowed here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(401): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, int)

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(43): error: "auto" is not allowed here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(400): error: no instance of function template "spconv::maxPoolBwdVecBlockKernel" matches the argument list
            argument types are: (const float *, const float *, const float *, float *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(459): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(412): error: no instance of function template "spconv::maxPoolBwdGenericKernel" matches the argument list
            argument types are: (const float *, const float *, const float *, float *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(459): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(50): error: no instance of function template "spconv::gatherVecBlockKernel" matches the argument list
            argument types are: (float *, const float *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(144): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(59): error: no instance of function template "spconv::gatherVecKernel" matches the argument list
            argument types are: (float *, const float *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=float, Index=int]" 
(144): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(329): error: no instance of function template "spconv::maxPoolFwdVecBlockKernel" matches the argument list
            argument types are: (double *, const double *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(460): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(340): error: no instance of function template "spconv::maxPoolFwdGenericKernel" matches the argument list
            argument types are: (double *, const double *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(460): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(400): error: no instance of function template "spconv::maxPoolBwdVecBlockKernel" matches the argument list
            argument types are: (const double *, const double *, const double *, double *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(460): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(412): error: no instance of function template "spconv::maxPoolBwdGenericKernel" matches the argument list
            argument types are: (const double *, const double *, const double *, double *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(460): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(329): error: no instance of function template "spconv::maxPoolFwdVecBlockKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(461): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(340): error: no instance of function template "spconv::maxPoolFwdGenericKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(461): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(97): error: "auto" is not allowed here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(104): error: no instance of function template "spconv::scatterAddVecBlockKernel" matches the argument list
            argument types are: (float *, const float *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=float, Index=int]" 
(144): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(113): error: no instance of function template "spconv::scatterAddGenericKernel" matches the argument list
            argument types are: (float *, const float *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=float, Index=int]" 
(144): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(400): error: no instance of function template "spconv::maxPoolBwdVecBlockKernel" matches the argument list
            argument types are: (const c10::Half *, const c10::Half *, const c10::Half *, c10::Half *, const int *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(461): here

/home/qmm/Documents/project/spconv/src/spconv/maxpool.cu(412): error: no instance of function template "spconv::maxPoolBwdGenericKernel" matches the argument list
            argument types are: (const c10::Half *, const c10::Half *, const c10::Half *, c10::Half *, const int *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseMaxPoolBackwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const T, -1>, tv::TensorView<T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(461): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(50): error: no instance of function template "spconv::gatherVecBlockKernel" matches the argument list
            argument types are: (double *, const double *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(145): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(59): error: no instance of function template "spconv::gatherVecKernel" matches the argument list
            argument types are: (double *, const double *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=double, Index=int]" 
(145): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(104): error: no instance of function template "spconv::scatterAddVecBlockKernel" matches the argument list
            argument types are: (double *, const double *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=double, Index=int]" 
(145): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(113): error: no instance of function template "spconv::scatterAddGenericKernel" matches the argument list
            argument types are: (double *, const double *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=double, Index=int]" 
(145): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(50): error: no instance of function template "spconv::gatherVecBlockKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(146): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(59): error: no instance of function template "spconv::gatherVecKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseGatherFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]" 
(146): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(104): error: no instance of function template "spconv::scatterAddVecBlockKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, int, int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=c10::Half, Index=int]" 
(146): here

/home/qmm/Documents/project/spconv/src/spconv/reordering.cu(113): error: no instance of function template "spconv::scatterAddGenericKernel" matches the argument list
            argument types are: (c10::Half *, const c10::Half *, const int *, int, const int)
          detected during instantiation of "void spconv::functor::SparseScatterAddFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int, __nv_bool) [with T=c10::Half, Index=int]" 
(146): here

20 errors detected in the compilation of "/tmp/tmpxft_0000113a_00000000-7_maxpool.cpp1.ii".
18 errors detected in the compilation of "/tmp/tmpxft_00001139_00000000-7_reordering.cpp1.ii".
src/spconv/CMakeFiles/spconv.dir/build.make:140: recipe for target 'src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o] Error 2
make[2]: *** Waiting for unfinished jobs....
src/spconv/CMakeFiles/spconv.dir/build.make:114: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cu.o] Error 2
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/qmm/Documents/project/spconv/include/spconv/nms.h:21:0,
                 from /home/qmm/Documents/project/spconv/src/utils/all.cc:15:
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:288:5: error: ‘is_trivially_copyable’ is not a member of ‘std’
     std::is_trivially_copyable<T>,
     ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:288:5: error: ‘is_trivially_copyable’ is not a member of ‘std’
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:288:33: error: template argument 2 is invalid
     std::is_trivially_copyable<T>,
                                 ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:920:49: error: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                 ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:920:49: error: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:920:72: error: template argument 1 is invalid
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                        ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:920:75: error: template argument 2 is invalid
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                           ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:920:80: error: expected unqualified-id before ‘>’ token
 struct format_descriptor<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                                ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:969:51: error: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
 struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                   ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:969:51: error: ‘is_pod_struct’ is not a member of ‘pybind11::detail’
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:969:74: error: template argument 1 is invalid
 struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                          ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:969:77: error: template argument 2 is invalid
 struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                             ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:969:82: error: expected unqualified-id before ‘>’ token
 struct compare_buffer_info<T, detail::enable_if_t<detail::is_pod_struct<T>::value>> {
                                                                                  ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:1121:19: error: ‘is_pod_struct’ was not declared in this scope
     static_assert(is_pod_struct<T>::value, "Attempt to use a non-POD or unimplemented POD type as a numpy dtype");
                   ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:1121:34: error: expected primary-expression before ‘>’ token
     static_assert(is_pod_struct<T>::value, "Attempt to use a non-POD or unimplemented POD type as a numpy dtype");
                                  ^
/home/qmm/Documents/project/spconv/third_party/pybind11/include/pybind11/numpy.h:1121:35: error: ‘::value’ has not been declared
     static_assert(is_pod_struct<T>::value, "Attempt to use a non-POD or unimplemented POD type as a numpy dtype");
                                   ^
src/utils/CMakeFiles/spconv_utils.dir/build.make:62: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all.cc.o' failed
make[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    zip_safe=False,
  File "/home/qmm/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/qmm/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/qmm/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/qmm/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/qmm/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/qmm/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/qmm/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/qmm/anaconda3/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 169, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/qmm/anaconda3/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command
    self.run_command(cmdname)
  File "/home/qmm/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/qmm/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/qmm/anaconda3/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/qmm/anaconda3/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/qmm/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/qmm/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 34, in run
    self.build_extension(ext)
  File "setup.py", line 65, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/qmm/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
