### ISSUE TITLE
How to add two SparseConvTensor?

### ISSUE THREAD

**Issue by godspeed1989** [traveller59/spconv#30]
Thanks for your great work !

I want to create ResNet style structure using spconv.
But it seems that i can't add two SparseConvTensor directly.
Is there any solution?

**Comment by godspeed1989** [comment]
Thanks a lot

**Comment by godspeed1989** [comment]
Sorry to borther you again.

Is seems that spconv operate on `x.features` using a inplace manner.
Should i use
```
from copy import deepcopy
identity = deepcopy(x)
```
instead of
```
identity = x
```
?

**Comment by traveller59** [comment]
The original resnet code use inplace operation too, don't need to worry about it.

**Comment by godspeed1989** [comment]
Sorry, but i don't think the original resnet code is the same as the code here.
In original resnet code, the inplace operation on `x` would not effect `identity`.
```
In [17]: class res(nn.Module): 
    ...:     def __init__(self): 
    ...:         super(res, self).__init__() 
    ...:         self.conv = nn.Conv1d(1,1,1) 
    ...:     def forward(self, x): 
    ...:         identity = x 
    ...:         out = self.conv(x) 
    ...:         print(identity) 
    ...:         print(out) 
    ...:         return out + identity 
    ...:                                                                        

In [18]: a = res()                                                              

In [19]: a(t)                                                                   
tensor([[[0.]]])
tensor([[[-0.2773]]], grad_fn=<SqueezeBackward1>)
```
But if x is a `SparseConvTensor`,  it seems that the operation on `x` will affect `identity` at the same time.
My experiment also show that the modification does improve network performance.
I think this may relate to pytorch's computional graph implementation.

**Comment by traveller59** [comment]
It's a bug but should only exists when you use 1x1 conv. fixed in newest commit. could you provide a runable reproduce example if the bug still exists for 3x3 conv?

**Comment by godspeed1989** [comment]
I think the bug is fixed.
Thank you

**Comment by jialeli1** [comment]
> Sorry to borther you again.
> 
> Is seems that spconv operate on `x.features` using a inplace manner.
> Should i use
> 
> ```
> identity_features = x.features.clone()
> ...
> out.features += identity_features
> ```
> 
> instead of
> 
> ```
> identity = x
> ```
> 
> ?
> But deepcopy will cause training error

Hi! I hope my comment will not be too late.
How did you discover "spconv operate on x.features using a inplace manner"?
Where should I find documentation on SparseConvTensor? I also found that the changes modified by myself are always worse than that without changes.
Can you @traveller59 @godspeed1989 give me some hints?
Thanks.
