### ISSUE TITLE
Is there any method for GlobalAvgPooling?

### ISSUE THREAD

**Issue by xiaodongww** [traveller59/spconv#300]
Hi @traveller59 , thanks for your great work!

 I am wondering if spconv supports `Global Average Pooling`.  I noticed that in [issue146](https://github.com/traveller59/spconv/issues/146), you implement `SparseGlobalMaxPool ` using `ops. indice_maxpool `. Is there any similar function like `indice_avgpool`?

Thansk a lot!

**Comment by erinchen824** [comment]
> Hi @traveller59 , thanks for your great work!
> 
> I am wondering if spconv supports `Global Average Pooling`. I noticed that in [issue146](https://github.com/traveller59/spconv/issues/146), you implement `SparseGlobalMaxPool ` using `ops. indice_maxpool `. Is there any similar function like `indice_avgpool`?
> 
> Thansk a lot!

Have you solved this?

**Comment by Gofinge** [comment]
Hi @traveller59, thanks for your great work!

I am also wondering whether Global Average Pooling will be available like ops.indice_maxpool?
