### ISSUE TITLE
python setup.py bdist_wheel error

### ISSUE THREAD

**Issue by dwchen-tech** [traveller59/spconv#303]
My env: ubuntu16.04/cuda10.1/pytorch1.3.1/cudatoolkit10.0.130/cudnn7.6.5/python3.7.7/gcc5.3.1
Error info like below:
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/MLDL/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.1 (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/local/cuda-10.1/lib64/libcudnn.so  
-- Found cuDNN: v7.6.1  (include: /usr/local/cuda-10.1/include, library: /usr/local/cuda-10.1/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:103 (find_package_handle_standard_args)
  CMakeLists.txt:24 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.1
-- Found PythonInterp: /home/emg/anaconda3/envs/pcdet/bin/python3.7 (found suitable version "3.7.7", minimum required is "3.7") 
-- Found PythonLibs: /home/emg/anaconda3/envs/pcdet/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CUDA_COMPILER= /usr/bin/nvcc

-- The CXX compiler identification is GNU 5.3.1
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/data/MLDL/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CUDA_COMPILER= /usr/bin/nvcc

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/data/MLDL/spconv', '-DCMAKE_PREFIX_PATH=/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/MLDL/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
(pcdet) emg@emg:/data/MLDL/spconv$ rm -rf build/
(pcdet) emg@emg:/data/MLDL/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10301', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/MLDL/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 5.3.1
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-10.1 (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/local/cuda-10.1/lib64/libcudnn.so  
-- Found cuDNN: v7.6.1  (include: /usr/local/cuda-10.1/include, library: /usr/local/cuda-10.1/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:103 (find_package_handle_standard_args)
  CMakeLists.txt:24 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.1
-- Found PythonInterp: /home/emg/anaconda3/envs/pcdet/bin/python3.7 (found suitable version "3.7.7", minimum required is "3.7") 
-- Found PythonLibs: /home/emg/anaconda3/envs/pcdet/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/cuhash/CMakeLists.txt:4 (add_library):
  Cannot generate a safe runtime search path for target cuhash because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda-10.1/lib64
      /home/emg/anaconda3/envs/pcdet/lib
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

CMake Warning at src/cuhash/CMakeLists.txt:4 (add_library):
  Cannot generate a safe runtime search path for target cuhash because there
  is a cycle in the constraint graph:

    dir 0 is [/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/lib]
    dir 1 is [/usr/local/cuda-10.1/lib64/stubs]
    dir 2 is [/usr/local/cuda-10.1/lib64]
      dir 3 must precede it due to runtime library [libnvToolsExt.so.1]
    dir 3 is [/home/emg/anaconda3/envs/pcdet/lib]
      dir 2 must precede it due to runtime library [libcudnn.so.7]
    dir 4 is [/usr/local/cuda/lib64]
      dir 3 must precede it due to runtime library [libnvToolsExt.so.1]

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda-10.1/lib64
      /home/emg/anaconda3/envs/pcdet/lib
      /usr/local/cuda/lib64
    runtime library [libgomp.so.1] in /usr/lib/gcc/x86_64-linux-gnu/5 may be hidden by files in:
      /home/emg/anaconda3/envs/pcdet/lib

  Some of these libraries may not be found correctly.

CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because there
  is a cycle in the constraint graph:

    dir 0 is [/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/lib]
    dir 1 is [/usr/local/cuda-10.1/lib64/stubs]
    dir 2 is [/usr/local/cuda-10.1/lib64]
      dir 4 must precede it due to runtime library [libnvToolsExt.so.1]
    dir 3 is [/data/MLDL/spconv/build/lib.linux-x86_64-3.7/spconv]
    dir 4 is [/home/emg/anaconda3/envs/pcdet/lib]
      dir 2 must precede it due to runtime library [libcudnn.so.7]
    dir 5 is [/usr/local/cuda/lib64]
      dir 4 must precede it due to runtime library [libnvToolsExt.so.1]

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /data/MLDL/spconv/build/temp.linux-x86_64-3.7
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  4%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[  8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 12%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 16%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 25%] Linking CUDA static library libspconv_nms.a
[ 25%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 29%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 33%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 37%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/libcuhash.so
[ 37%] Built target cuhash
Scanning dependencies of target spconv
[ 41%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 45%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/ScalarType.h:6:0,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/Scalar.h:9,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:7,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:2,
                 from /data/MLDL/spconv/src/spconv/indice.cc:15:
/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/util/typeid.h:349:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
In file included from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/ScalarType.h:6:0,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/Scalar.h:9,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:7,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:2,
                 from /data/MLDL/spconv/src/spconv/reordering.cc:15:
/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/util/typeid.h:349:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
In file included from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/ScalarType.h:6:0,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/core/Scalar.h:9,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:7,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/torch/script.h:3,
                 from /data/MLDL/spconv/include/spconv/indice.h:18,
                 from /data/MLDL/spconv/include/spconv/fused_spconv_ops.h:18,
                 from /data/MLDL/spconv/src/spconv/all.cc:15:
/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/torch/include/c10/util/typeid.h:349:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:108: src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:95: src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:82: src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:205: src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX shared library ../../../lib.linux-x86_64-3.7/spconv/spconv_utils.cpython-37m-x86_64-linux-gnu.so
[ 54%] Built target spconv_utils
make: *** [Makefile:149: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/emg/anaconda3/envs/pcdet/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by yangchandler** [comment]
Have you solved this problem？

**Comment by dwchen-tech** [comment]
> Have you solved this problem？

upgrade pytorch to 1.6, i finally installed spconv
