### ISSUE TITLE
python setup.py bdist_wheel error

### ISSUE THREAD

**Issue by wxz0918** [traveller59/spconv#305]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/wxz/spconv-master/spconv-master/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 8.1.0
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "10.1")
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so
-- Found cuDNN: v?  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Error at /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/wxz/spconv-master/spconv-master/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/wxz/spconv-master/spconv-master/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 82, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/wxz/anaconda3/envs/py37/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/wxz/spconv-master/spconv-master', '-DCMAKE_PREFIX_PATH=/home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/wxz/spconv-master/spconv-master/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by arsalan311** [comment]
@wxz0918 Having the same problem...were u able to solve it?

**Comment by WangChen100** [comment]
the same problem

**Comment by DipDipPotatoChips** [comment]
same quesition，I use a conda environment with cuda 11.1 and my cuda11.1 has cudnn8,but it reported 
"Caffe2: CUDA detected: 10.1
……
Found cuDNN: v? (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Error at /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
PyTorch requires cuDNN 7 and above."
I have spent more than one day trying to solve this problem

**Comment by DipDipPotatoChips** [comment]
same quesition，I use a conda environment with cuda 11.1 and my cuda11.1 has cudnn8,but it reported
"Caffe2: CUDA detected: 9.1
……
Found cuDNN: v? (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Error at /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
PyTorch requires cuDNN 7 and above."
I have spent more than one day trying to solve this problem

**Comment by sissini** [comment]
> same quesition，I use a conda environment with cuda 11.1 and my cuda11.1 has cudnn8,but it reported "Caffe2: CUDA detected: 9.1 …… Found cuDNN: v? (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so) CMake Error at /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message): PyTorch requires cuDNN 7 and above." I have spent more than one day trying to solve this problem

same problem, have u sloved it ?

**Comment by DipDipPotatoChips** [comment]
I‘m sorry。
The file just sent only recorded the intermediate process, the file sent this time is complete


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "traveller59/spconv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [traveller59/spconv] python setup.py bdist_wheel error (#305)





  
same quesition，I use a conda environment with cuda 11.1 and my cuda11.1 has cudnn8,but it reported "Caffe2: CUDA detected: 9.1 …… Found cuDNN: v? (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so) CMake Error at /home/wxz/anaconda3/envs/py37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message): PyTorch requires cuDNN 7 and above." I have spent more than one day trying to solve this problem
  
same problem, have u sloved it ?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DipDipPotatoChips** [comment]
> Thanks for your reply, I habe solved my Problem by adding cuda/include/cudnn_version.h, "sudo cp cuda/include/cudnn_version.h /usr/local/cuda/include". my cuda version is 11.1, cudnn 8.0.5, for high Level cudnn, the version information is included in cudnn_version.h, so if u only copy cudnn.h to your local path, it will show the Problem of "found cudnn: v1". I hope my experience can help anyone else.

Glad to hear that and I 'll record your experience in my reference document，thank you
