### ISSUE TITLE
set.py problem

### ISSUE THREAD

**Issue by siyuan9607** [traveller59/spconv#310]
Hi, when I try to run "python setup.py bdist_wheel" It give me the following error:

running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/sxs14473/anaconda3/lib/python3.8/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.8', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10500', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/sxs14473/spconv/build/lib.linux-x86_64-3.8/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /home/sxs14473/anaconda3/pkgs/cudnn-7.6.5-cuda10.1_0/lib/libcudnn.so
-- Found cuDNN: v7.6.5  (include: /home/sxs14473/anaconda3/pkgs/cudnn-7.6.5-cuda10.1_0/include/, library: /home/sxs14473/anaconda3/pkgs/cudnn-7.6.5-cuda10.1_0/lib/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found torch: /home/sxs14473/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch.so
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Found PythonInterp: /usr/bin/python3.8 (found suitable version "3.8.5", minimum required is "3.8")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.0
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sxs14473/spconv/build/temp.linux-x86_64-3.8
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  8%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[  8%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 16%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 12%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libnvToolsExt.so', needed by 'src/cuhash/CMakeFiles/cuhash.dir/cmake_device_link.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 20%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 25%] Linking CUDA static library libspconv_nms.a
[ 25%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 29%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
make[1]: *** [CMakeFiles/Makefile2:159: src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Linking CXX shared library ../../../lib.linux-x86_64-3.8/spconv/spconv_utils.cpython-38-x86_64-linux-gnu.so
[ 33%] Built target spconv_utils
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    setup(
  File "/home/sxs14473/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/sxs14473/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/sxs14473/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/sxs14473/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

Can anyone take a look and give me some hint how to solve the problem? My Pytorch is 1.5.0, cuda is 10.1.

**Comment by Root-9527** [comment]
same with you; solved?

**Comment by siyuan9607** [comment]
Yes, I reinstall the torch and problem solved. It is most likely a path problem. So it may help to check your installation path.
