### ISSUE TITLE
How to install spconv in ubuntu20.04?

### ISSUE THREAD

**Issue by ZihaoLian** [traveller59/spconv#314]
The server environment is as follows:

- Ubuntu 20.04
- Driver Version: 460.73.01
- CUDA Version: 11.2

Looking forward to your help.

**Comment by gav1n-cheung** [comment]
Hey,dude. I have installed scponv in ubuntu20.04. 

My sever environment is as follows:

- Ubuntu 20.04
- nvidia driver Version: 470.57.02
- CUDA Version: 11.1

The step of mine is as follows:

`cd`
`git clone https://github.com/traveller59/spconv --recursive`
`cd spconv`
`export CUDA_HOME="/usr/local/cuda-11.1"`
`python setup.py bdist_wheel`
`cd dist`
`pip install spconv-1.2.1-cp38-cp38-linux_x86_64.whl`

Maybe the step 5 runs wrong, everyone has diffierent problem. My problem is about the cudnn version. If you also has the same problem, maybe I can help you.

**Comment by owoshch** [comment]
Hi @gav1n-cheung! I have the same environment, however, I'm facing the issue with my CuDNN "PyTorch requires cuDNN 7 and above". What version of CuDNN and Pytorch are you using?
Thank you!

**Comment by gav1n-cheung** [comment]
> Hi @gav1n-cheung! I have the same environment, however, I'm facing the issue with my CuDNN "PyTorch requires cuDNN 7 and above". What version of CuDNN and Pytorch are you using?
> Thank you!

Hey,sir. I get this question too. The question is not because of your cudnn or python. You have to revise the document that in your environment.
Like this:
