### ISSUE TITLE
debug the points_to_voxel_3d_np source code

### ISSUE THREAD

**Issue by Willforcv** [traveller59/spconv#317]
hello everyone~
i need to know some details about the voxel code. 
how to build the package and debug the python code, and jump into the cpp source code? thanks~

**Comment by quan-dao** [comment]
Hi Willforcv,
The function you are looking for is defined in `spconv/include/spconv/point2voxel.h`.

**Comment by Willforcv** [comment]
i see it ,   i just want to debug it step by step with breakpoint~

________________________________
发件人: Minh-Quan Dao ***@***.***>
发送时间: 2021年7月6日 7:36
收件人: traveller59/spconv ***@***.***>
抄送: Willforcv ***@***.***>; Author ***@***.***>
主题: Re: [traveller59/spconv] debug the points_to_voxel_3d_np source code (#317)


Hi Willforcv,
The function you are looking for is defined in spconv/include/spconv/point2voxel.h.

―
