### ISSUE TITLE
Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH)

### ISSUE THREAD

**Issue by heesungsung** [traveller59/spconv#319]
My Environment: Using Anaconda. python 3.8.8, PyTorch 1.8.1, cmake 3.21.0, cuda 11.2 (11.1 in Anaconda).
I don't know how to check the version of CUDNN... :(

Error occurs after running python setup.py bdist_wheel.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/heeseong/anaconda3/lib/python3.8/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.8', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10801', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/heeseong/second.pytorch/second/spconv/build/lib.linux-x86_64-3.8/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CUDA compiler identification is NVIDIA 11.2.152
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-11.2 (found version "11.2") 
-- Caffe2: CUDA detected: 11.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.2
-- Caffe2: Header version is: 11.2
-- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH) 
CMake Warning at /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:25 (find_package)

CMake Warning at /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:25 (find_package)

-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Error at /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/heeseong/anaconda3/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:25 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/heeseong/second.pytorch/second/spconv/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/heeseong/second.pytorch/second/spconv/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
...

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

How can I solve it?

**Comment by Darayavaus** [comment]
For the purposes of example, I'll assume you have cuda-11.0. 
Try setting all these environment variables(it might be an overkill, but it doesn't harm):
```
export CUDAPATH=/your/path/cuda-11.0
export CUDA_HOME=/your/path/cuda-11.0
export LD_LIBRARY_PATH=/your/path/cuda-11.0/lib64:$LD_LIBRARY_PATH
export PATH=/your/path/cuda-11.0/bin:$PATH
```
`/your/path/ `is usually `/usr/local/`, but you should check it on your machine.

**Comment by ldaowen** [comment]
Can you check the output of : nvcc --version, as well as if your cuda and cudNN are installed correctly.

**Comment by heesungsung** [comment]
@ldaowen I have solved the problem!! Thank you for reply.

**Comment by curiousboy20** [comment]
> @ldaowen I have solved the problem!! Thank you for reply.

Hi, how did you solve the problem?

**Comment by ldaowen** [comment]
> > @ldaowen I have solved the problem!! Thank you for reply.
> 
> Hi, how did you solve the problem?

@curiousboy20 Please check your CUDA and CUDNN installation versions:

echo $CUDNN_LIBRARY_PATH to check if the paths are linked as well
