### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by rockywind** [traveller59/spconv#327]
When I use SubMConv3d, the error is below.
>    input_sp_tensor = spconv.SparseConvTensor(
            features=voxel_features,#[201109, 64])
            indices=voxel_coords.int(), # [201109, 4])
            spatial_shape=sparse_shape,
            batch_size=batch_size
        )
sparse conv:
self.conv_input = spconv.SparseSequential(
            spconv.SubMConv3d(input_channels, output_channels, 3, padding=1, bias=False, indice_key='subm0'))

**Comment by derkaczda** [comment]
I have a similar error, any fix yet?

**Comment by wangfudong** [comment]
@rockywind 
Hi, I have a similar error, any fix yet? Tks~

**Comment by superdocker** [comment]
Hi, I have the same issue, and I fix it by adding a simple dummy operation, such as `indices = indices[indices[:,0]!=-1] `
This makes no functionality change, but I think that this re-allocates the data address and helps to fix the GPU backend error. (Additionally, I tried indices.clone() or indices.detach().clone(), but these methods did not work.)

**Comment by harry1576** [comment]
Has a fix been released yet? 
Cheers,
Harry
