### ISSUE TITLE
c++ internal compiler error: Segmentation fault (program cc1plus)

### ISSUE THREAD

**Issue by giaguar96** [traveller59/spconv#328]
Hi everyone,
i'm working on a Jetson xavier AGX and when i try to run the command `python3 setup.py bdist_wheel` the following error arises:

running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/nvidia/.local/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10801', '-DSPCONV_BuildCUDA=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/media/nvidia/641e8c5e-2a55-4cd8-882e-2836f81dd9d1/nvidia/radio-ws/spconv/build/lib.linux-aarch64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /media/nvidia/641e8c5e-2a55-4cd8-882e-2836f81dd9d1/nvidia/radio-ws/spconv/build/temp.linux-aarch64-3.7
Consolidate compiler generated dependencies of target spconv
[ 20%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 20%] Building CXX object src/spconv/CMakeFiles/spconv.dir/nms.cc.o
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
src/utils/CMakeFiles/spconv_utils.dir/build.make:75: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all.cc.o' failed
make[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 4
CMakeFiles/Makefile2:159: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
src/spconv/CMakeFiles/spconv.dir/build.make:131: recipe for target 'src/spconv/CMakeFiles/spconv.dir/nms.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/nms.cc.o] Error 4
CMakeFiles/Makefile2:133: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/nvidia/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

Someone knows how to face this issue?
I'm working on ubuntu 18.04, python3.7, cmake 3.21.2, CUDA 10.2 and torch 1.8.1
Thanks for any response

**Comment by Zoe-Yan123** [comment]
same error, please help

**Comment by RXWein** [comment]
Same error, can anyone help solve it

**Comment by efthimia145** [comment]
Did anyone manage to solve this?
