### ISSUE TITLE
Error when setup, what configuration can install successfully?

### ISSUE THREAD

**Issue by Miles629** [traveller59/spconv#335]
I have tried these config:
python3.7
cmake3.21/cmake3.17.3/cmake3.6.3
torch1.4/torch1.9.1
gcc7.3/gcc5.3
but all failed when setup.  The reason are very different. I don't know what kind of configuration can complete the installation. Can you specify a configuration to install?

**Comment by Miles629** [comment]
solved by chage the boost header

**Comment by linjie-yang** [comment]
Hello, I meet a problem about installing boost header: is the "include path" the include path inside the spconv package? Looking forward to your reply！
