### ISSUE TITLE
[Question] Use cudatoolkit in conda?

### ISSUE THREAD

**Issue by tianweiy** [traveller59/spconv#338]
Hi SpConv author,

As we now have pip support, I wonder if it is possible to also use the cudatoolkits in conda instead of local cuda for spconv (like pytorch's way)? This will even simplify the pipeline (basically, there are some servers that we can't control the local cuda version).

**Comment by FindDefinition** [comment]
If you extract the spconv 2.x wheel, you can find that the c++ library only link to libcudart which is shipped in wheel too, that library only require suitable nvidia driver installed in your server (>=450.82 for CUDA 11.x). so it's safe to use spconv 2.x without cuda installed in OS. 
I will add this note to readme.
