### ISSUE TITLE
No matching distribution found for cumm-cu100

### ISSUE THREAD

**Issue by wuyangniubi** [traveller59/spconv#341]
Dear author,thanks for your great job!I tried to install spconv v1 but when I tried to pip install the generated whl file ,I met this error:
_pip install spconv_cu100-2.0.1-py3-none-any.whl -i https://pypi.python.org/simple_
`Looking in indexes: https://pypi.python.org/simple
Processing ./spconv_cu100-2.0.1-py3-none-any.whl
Requirement already satisfied: fire in /opt/conda/lib/python3.7/site-packages (from spconv-cu100==2.0.1) (0.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from spconv-cu100==2.0.1) (1.19.2)
ERROR: Could not find a version that satisfies the requirement cumm-cu100 (from spconv-cu100)
ERROR: No matching distribution found for cumm-cu100
`
I'm looking forward to any suggestion.

**Comment by qiaoli96** [comment]
I have the same problem. Must cuda be updated to version 11?

**Comment by wuyangniubi** [comment]
Yes.Must update it.Old version is not accepted for now.



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 3, 2021 16:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [traveller59/spconv] No matching distribution found forcumm-cu100 (Issue #341)




 
I have the same problem. Must cuda be updated to version 11?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiaoli96** [comment]
But I cannot install the new version of CUDA on the server of the laboratory I use. Can I solve it by other means? I plan to install spconv1.0.

**Comment by FindDefinition** [comment]
@qiaoli96 spconv 2.1 will bring CUDA 10.2 support. cuda < 10.2 requires many weird changes, so no plan to support them.

**Comment by qiaoli96** [comment]
我已收到您的邮件，谢谢！--李悄（^_^）
