### ISSUE TITLE
VoxelGenerator

### ISSUE THREAD

**Issue by Uthman-o** [traveller59/spconv#343]
Thanks for the repo and update.
What's the replacement for the generate method in the VoxelGenerator class in version 2.0?
I don't know what to replace it with in the Point2VoxelGPU3d class.
Thanks

**Comment by Uthman-o** [comment]
Hello. I'm trying to pass point cloud data "(x,y,z,intensity)" through the

 "voxel_output = voxel_generator.point_to_voxel(pc_tv)" method and I keep getting this error.

"num_features == voxels.dim(2) assert faild. your points num features doesn't equal to voxel."

How do I fix this? Please
Thanks

**Comment by FindDefinition** [comment]
you provide a pc with intensity, so ```your pc.shape[1] == 1```, then the argument ```num_point_features``` in voxel generator need to be 4.

**Comment by Uthman-o** [comment]
Thank you again.
