### ISSUE TITLE
换gpu测试出现问题

### ISSUE THREAD

**Issue by wangjingbo1219** [traveller59/spconv#35]
HI 抱歉打扰了
是这样 我在改second的多卡版本的时候 发现spconv在使用多gpu的时候有illegal的memory
然后我在尝试使用你的代码中提供的test脚本测试spconv在不同gpu上的表现 发现我把device从cuda:0改成cuda:1的时候报了如下错误
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/17522043/55484815-c5ad6a80-565b-11e9-8e7d-bd24bf23e086.png">
请问你们在写kernel的时候有在kernel内指定好强制使用0号gpu而不适用其他gpu吗

**Comment by kagecom** [comment]
Have you solve this issue?

**Comment by traveller59** [comment]
Sorry for late reply, the github didn't send me an email about this issue.
I use at::cuda::getCurrentCUDAStream() to get current stream and use it to launch kernels. so I suspect that the problem is torch._unique, but I don't have multi-gpu environment to debug this problem.

**Comment by kagecom** [comment]
> Sorry for late reply, the github didn't send me an email about this issue.
> I use at::cuda::getCurrentCUDAStream() to get current stream and use it to launch kernels. so I suspect that the problem is torch._unique, but I don't have multi-gpu environment to debug this problem.

Thanks for you reply.

I can show what i learn from debuging to see whether you know the solutions.

when i specify cuda:1 in test/test_conv.py, it causes problem CUDA kernel launch blocks n = 0, 

the reason is that the function getIndicePairFtorP1 actually runs in GPU 0, not in GPU 1,
 it may be cased by at::cuda::getCurrentCUDAStream() .

However, i manually set the device 1 for the stream, but it cause segmentation core in spconv_ops.h:322 (line number may be different),
where  the code is : 
     auto inputBufferBlob =
          torch::from_blob(inputBuffer.data<T>(), {nHot, numInPlanes}, options); 

Do you have any clue?

**Comment by traveller59** [comment]
"inputBufferBlob" bug may due to debug mode, torch c++ lib don't support debug build.
Could you add following code to test_conv.py and test it again? In addition, you shouldn't set stream manually.
```Python
with torch.cuda.device("cuda:1"):
    # spconv ops...
```

**Comment by zhixinwang** [comment]
@traveller59  I found the problem is from the torch::_unique.  Adding torch.cuda.device(1) will  avoid this problem. So how to fix it?

**Comment by sshaoshuai** [comment]
Hi @traveller59 ,
Thanks for your great spconv!
I have also met this problem when using Dataparallel of pytorch, do you have any advice to fix this problem?

**Comment by traveller59** [comment]
@sshaoshuai Best way to solve this is use distributed training. I don't have debug environment to solve this problem.

**Comment by sshaoshuai** [comment]
@traveller59  Great, I am going to try the distributed training these days. Thank you very much!
