### ISSUE TITLE
Cannot pickle Point2VoxelCPU object

### ISSUE THREAD

**Issue by tdzdog** [traveller59/spconv#351]
Currently, I am trying to apply spconv 2.0 in OpenPCDet ( a famous object detection repo that supports only spconv 1.0 right now). However, I met a error that _TypeError: cannot pickle 'spconv.core_cc.csrc.sparse.all.ops_cpu3d.Point2VoxelCPU' object_ for distributed training. Such error hinders the usage of Point2Voxel in multiprocessing. Hence, I hope such bug can be fixed.

**Comment by FindDefinition** [comment]
you can create voxel generator after distributed process spawn for now.
This will be fixed in spconv 2.1.0

**Comment by rubbish001** [comment]
my environment spconv version is 2.1.7 ,but I get the same problem ,how to solve this ?

**Comment by FindDefinition** [comment]
@rubbish001 use PointToVoxel instead of Point2VoxelCPUXd, see [example](https://github.com/traveller59/spconv/blob/master/example/voxel_gen.py).

**Comment by Kemo-Huang** [comment]
spconv-cu114, version 2.1.21, still has this bug on Windows.

When I use pytorch dataloader, I get this error:
TypeError: cannot pickle 'spconv.core_cc.csrc.sparse.all.ops_cpu3d.Point2VoxelCPU' object

**Comment by eriche2016** [comment]
is there a solution to this problem

**Comment by eriche2016** [comment]
I have solved this problem by putting the construction of this function in forward method.
