### ISSUE TITLE
No module Named pccm

### ISSUE THREAD

**Issue by prithusuresh** [traveller59/spconv#352]
When I try to install spconv by running setup.py I get the following error

Traceback (most recent call last):
  File "/home/ubuntu/spconv/setup.py", line 15, in <module>
    import pccm
ModuleNotFoundError: No module named 'pccm'

I'm running python 3.9.5

**Comment by FindDefinition** [comment]
install from source isn't recommended, just use pip.
Or just use pip to install module if encounter No module named xxx.
