### ISSUE TITLE
How to install spconv 1.x now ?

### ISSUE THREAD

**Issue by chaytonmin** [traveller59/spconv#355]
Spconv 2.x is great. However, my codes are based on spconv1.x, how can I install spconv 1.x now?

**Comment by FindDefinition** [comment]
[here](https://github.com/traveller59/spconv/tree/v1.2.1)

**Comment by chaytonmin** [comment]
> [here](https://github.com/traveller59/spconv/tree/v1.2.1)

how to use the 1.x branch with --recusive?

**Comment by FindDefinition** [comment]
just ```git clone https://github.com/traveller59/spconv.git -b v1.2.1 --recursive```

**Comment by chaytonmin** [comment]
> just `git clone https://github.com/traveller59/spconv.git -b v1.2.1 --recursive` We won't provide any support for spconv 1.x since it's deprecated. use spconv 2.x if possible.

Thanks！
