### ISSUE TITLE
python setuo.py bdist_wheel error (spconv1.2.1)

### ISSUE THREAD

**Issue by Liyan943** [traveller59/spconv#360]
i got  error when i use "python setuo.py bdist_wheel "

[ 50%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a'
gmake[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:293：src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:180：src/spconv/CMakeFiles/spconv.dir/all] 错误 2

anyone know how to slove this problem? the following are complet information, thanks .

$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10701', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lijunda/桌面/env_learing/spconv-1.2.1/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.1
-- Found cuDNN: v8.0.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
-- Autodetected CUDA architecture(s):  8.6
-- pybind11 v2.5.0
-- Configuring done
CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/cuhash/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cuhash".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/cuhash/CMakeLists.txt:4 (add_library):
  Cannot generate a safe runtime search path for target cuhash because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at src/spconv/CMakeLists.txt:5 (add_library):
  Cannot generate a safe runtime search path for target spconv because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.8] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/lijunda/桌面/env_learing/spconv-1.2.1/build/temp.linux-x86_64-3.7
Consolidate compiler generated dependencies of target spconv_nms
Consolidate compiler generated dependencies of target cuhash
[  8%] Built target spconv_nms
[ 33%] Built target cuhash
Consolidate compiler generated dependencies of target spconv_utils
Consolidate compiler generated dependencies of target spconv
[ 41%] Built target spconv_utils
[ 45%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 50%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
nvlink fatal   : Could not open input file '/usr/lib/x86_64-linux-gnu/libpthread.a'
gmake[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:293：src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o] 错误 1
gmake[1]: *** [CMakeFiles/Makefile2:180：src/spconv/CMakeFiles/spconv.dir/all] 错误 2
gmake: *** [Makefile:136：all] 错误 2
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 92, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/lijunda/anaconda3/envs/openpcdet_lijunda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by FindDefinition** [comment]
I have no idea about this error...
please use spconv 2.x, it provide pip prebuilts, you can install it by ```pip install spconv-cu111``` without build manually.

**Comment by Liyan943** [comment]
> I have no idea about this error... please use spconv 2.x, it provide pip prebuilts, you can install it by `pip install spconv-cu111` without build manually.

thanks

**Comment by guanglei-maker** [comment]
i have the same problem
