### ISSUE TITLE
CUDA10.2 import spconv error

### ISSUE THREAD

**Issue by dangerous-xu** [traveller59/spconv#364]
@traveller59 hi, i install prebuild spconv-cuda102 in docker, and test the import, but meet error. 
docker environment
- ubuntu18.04
- python:3.7.10
- cuda:10.2
- cudnnn:7
- pytorch:1.9.0

```
>>> import spconv.pytorch as spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/spconv/pytorch/__init__.py", line 8, in <module>
    from spconv.pytorch.conv import (SparseConv2d, SparseConv3d, SparseConvTranspose2d,
  File "/opt/conda/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 27, in <module>
    import spconv.pytorch.functional as Fsp
  File "/opt/conda/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 148
    return input_bp, filters_bp, *None_9
                                 ^
SyntaxError: invalid syntax
```

**Comment by FindDefinition** [comment]
I don't know unpack in return stmt is a new feature in python 3.8 before...
for now you can change code in /opt/conda/lib/python3.7/site-packages/spconv/pytorch/functional.py L148 to 
```return input_bp, filters_bp, None, None, None, None, None, None, None, None, None, None```. this will be fixed in spconv 2.1.2.

**Comment by dangerous-xu** [comment]
> I don't know unpack in return stmt is a new feature in python 3.8 before... for now you can change code in /opt/conda/lib/python3.7/site-packages/spconv/pytorch/functional.py L148 to `return input_bp, filters_bp, None, None, None, None, None, None, None, None, None, None`. this will be fixed in spconv 2.1.2.

it works, thanks

**Comment by dangerous-xu** [comment]
@FindDefinition Hi, thanks for your work, there still have a import issue after you fix the 3.7 import bug
```
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spconv.pytorch as spconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/boden/Dev/ws/xujihai/BoostAI/spconv-2.1.2/spconv/__init__.py", line 19, in <module>
    from .__version__ import __version__
ModuleNotFoundError: No module named 'spconv.__version__'
```

**Comment by koraykoca** [comment]
@dangerous-xu hi, could you help me how can I use docker for this library? I am very new to docker and I think I messed up things

**Comment by dangerous-xu** [comment]
@koraykoca sorry for getting back to you late
it is easy to install spconv in docker environment , you just need to add blew code in the Dockerfile, the author already prebuild the installation package
```
RUN pip install spconv-cu102==2.1.X
```

**Comment by koraykoca** [comment]
@dangerous-xu thank you for your answer. [From here](docker pull scrin/dev-spconv), I used the pull command and ran it. Then I used the docker run command with the Image ID. But then nothing happens. I mean I couldn't use spconv library. My system doesn't see it. I looked on the internet but couldn't find information about how I can use a library using docker. What should I do to use spconv library from their docker in my project? or do you know a useful guide for this?

**Comment by dangerous-xu** [comment]
@koraykoca I don't know what you want to do, 
1. spconv usage please follow the readme
2. if you want to build a image and install spconv in the image, just add **RUN pip install spconv-cu102==2.1.X** into the Dockerfile
3. if you already have a image, then you can ** docker run -it  imagename:tag /bin/bash** to create a container, when you enter the container, you just need run code ** pip install spconv-cu102==2.1.X**, next you can write a python script to test spconv.
4. if you already have a container, then you can run
```
docker start container_id
docker attach container_id
pip install spconv-cu102==2.1.X
```
 last step need you to write a python script to test spconv.

 I hope it will help you
