### ISSUE TITLE
Error after setup.py bdist_wheel 

### ISSUE THREAD

**Issue by melodytr** [traveller59/spconv#365]
Hello,
Thank you for this great work. I am trying to install this work. When I write  `python setup.py bdist_wheel`, it gives this error which I am not able to solve for few days:

**
running bdist_wheel
running build
running build_py
running build_ext
/data/Ezgi/CenterPoint-KITTI/spconv/build/lib.linux-x86_64-3.6
Release
-- The CUDA compiler identification is unknown
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc - broken
CMake Error at /home/chandanyeshwanth/packages/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/CMakeTestCUDACompiler.cmake:52 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_3e15e/fast && /usr/bin/make  -f CMakeFiles/cmTC_3e15e.dir/build.make CMakeFiles/cmTC_3e15e.dir/build
    make[1]: Entering directory '/data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_3e15e.dir/main.cu.o
    /usr/bin/nvcc    "--expt-relaxed-constexpr"   -c /data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_3e15e.dir/main.cu.o
    fatbinary warning : option 'cuda' has been deprecated
    In file included from /tmp/tmpxft_00000965_00000000-5_main.cudafe1.stub.c:6:0,
                     from tmpxft_00000965_00000000-5_main.cudafe1.stub.c:1:
    /tmp/tmpxft_00000965_00000000-2_main.fatbin.c:2:31: fatal error: fatbinary_section.h: No such file or directory
    compilation terminated.
    CMakeFiles/cmTC_3e15e.dir/build.make:84: recipe for target 'CMakeFiles/cmTC_3e15e.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_3e15e.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp'
    Makefile:140: recipe for target 'cmTC_3e15e/fast' failed
    make: *** [cmTC_3e15e/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/data/Ezgi/CenterPoint-KITTI/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/data/Ezgi/CenterPoint-KITTI/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/Ezgi/CenterPoint-KITTI/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_PREFIX_PATH=/home/ezgicakir/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
** 

Could you help me? Thanks in advance.
nvcc --version yields 10.2.

**Comment by FindDefinition** [comment]
```fatal error: fatbinary_section.h: No such file or directory```
I haven't seen this before, no idea.
please upgrade your spconv to 2.1 which has official prebuilts for python >= 3.7 and CUDA 10.2/11.1/11.3/11.4, no build problem anymore.

**Comment by melodytr** [comment]
Hello, I figured that the problem is with nvcc and cuda version unmatching. 
`nvcc --version` yields 10.2 but `/usr/local/nvcc --version` yields 9.1. I wanted to work with 10.2. So, I add a cmake argument to the variable cmake_args  in build-extension() in order to point nvcc with cuda version 10.2 in setup.py in v1.1, which is `'-DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc'` . Then the problem is solved.
