### ISSUE TITLE
import error  (with pip install )

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#367]
import spconv.pytorch as spconv
  File "D:\pythoncoder\Anaconda3\lib\site-packages\spconv\__init__.py", line 17, in <module>
    from .core import ConvAlgo, AlgoHint
  File "D:\pythoncoder\Anaconda3\lib\site-packages\spconv\core.py", line 21, in <module>
    from cumm.conv.main import gen_gemm_params as gen_conv_params, ConvFwdAndBwdInput, ConvBwdWeight, ConvIterAlgo, GemmAlgo
ImportError: cannot import name 'ConvFwdAndBwdInput' from 'cumm.conv.main'

![image](https://user-images.githubusercontent.com/88700988/140758494-6bcb4d14-3f29-43ff-8808-749eaf490269.png)

cuda:11.4, spconv:2.1.2

Dear author
I just install the spconv today,but when I import it, I met the error,how can I deal with it? thanks

**Comment by FindDefinition** [comment]
your cumm need to be upgraded too.
```pip install -U cumm-cu114```

**Comment by mengshiyu0109** [comment]
oh thanks for your kind reply!
