### ISSUE TITLE
Can you provide python 3.6 prebuilt binaries?

### ISSUE THREAD

**Issue by JanaldoChen** [traveller59/spconv#368]
My runtime environment is python 3.6.9 and cuda11.1 on ubuntu16.04, I try to install spconv from the source but failed. For some reason I cannot change the runtime environment, so Can you provide the version for python3.6?

**Comment by FindDefinition** [comment]
add python 3.6 need some python change and rebuild, you need to wait for the tag in README change to 2.1.4, may need one day. 
I will remove python 3.6 again when [pytorch 1.11 released](https://github.com/pytorch/pytorch/issues/66462) because python 3.6 reach EOL (end of life) in 12.23.2021.

**Comment by JanaldoChen** [comment]
> add python 3.6 need some python change and rebuild, you need to wait for the `pypi package` badge in README change to 2.1.4, may need one day. I will remove python 3.6 again when [pytorch 1.11 released](https://github.com/pytorch/pytorch/issues/66462) because python 3.6 reach EOL (end of life) in 12.23.2021.

Thank you very much for your quick reply! I am looking forward to spconv 2.1.4.

**Comment by FindDefinition** [comment]
There are some problems encountered in python 3.6, I still need several hours to release 3.6 package.

**Comment by FindDefinition** [comment]
Closed because python 3.6 prebuilts are available.
