### ISSUE TITLE
.features  , does it mean that it is not be supported?(spconv2.1.2)

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#369]
self.conv1=spconv.SubMConv3d(in_planes, out_planes, kernel_size=(1, 3, 3), stride=stride,
                             padding=(0, 1, 1), bias=False, indice_key=indice_key)

shortcut = self.conv1(x)
shortcut.features = self.act1(shortcut.features)

  File "D:\pythoncoder\Anaconda3\lib\site-packages\spconv\pytorch\core.py", line 159, in features
    raise ValueError(msg)
ValueError: you can't set feature directly, use 'x = x.replace_feature(your_new_feature)' to generate new SparseConvTensor instead.
![image](https://user-images.githubusercontent.com/88700988/140895885-86b0a635-5bf1-41b9-88da-1602de9977fa.png)

Dear author,  
”.features “  can not  be used?  then, how can I get the features ?
thanks

**Comment by FindDefinition** [comment]
You can read, but can't modify the ```features``` attribute of a ```SparseConvTensor```.
change ```shortcut.features = self.act1(shortcut.features)``` to ```shortcut = shortcut.replace_feature(self.act1(shortcut.features))```.
