### ISSUE TITLE
rbbox_iou_loss in spconv.utils

### ISSUE THREAD

**Issue by mc171819** [traveller59/spconv#371]
when i run from spconv.utils import rbbox_iou, rbbox_iou_loss, it shows an error: ImportError: cannot import name 'rbbox_iou_loss', my spconv is 1.2.1. Is this rbbox_iou_loss in your newest spconv2.x?

**Comment by FindDefinition** [comment]
there is no rbbox_iou_loss in any version of spconv.
the rbbox_iou is removed in spconv 2.x.
you can find a iou loss implementation in [this](https://github.com/lilanxiao/Rotated_IoU), and rbbox iou in [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/box_iou_rotated.py)
