### ISSUE TITLE
Using spconv in SECOND

### ISSUE THREAD

**Issue by u1095279221321** [traveller59/spconv#372]
We have learned that spconv2. X has modified the position of the channel. Do we need to make synchronous changes to our data reading part. We can't get the right results.

**Comment by FindDefinition** [comment]
Do you load old model from spconv 1.2.1 to spconv 2.1? if so, you need to train from scratch again.
You can use spconv 2.0.2 first and set ```export SPCONV_FILTER_HWIO="1"``` to check result, spconv 2.0.2 + SPCONV_FILTER_HWIO can load old model.

**Comment by u1095279221321** [comment]
we can load  old model in spconv 2.0.2. but the effect is weaker than spconv 1.2.1. We checked the parameters and found that when the max voxel is 20000, spconv 1.2.1 is better. When the number of voxels is increased, the effect of spconv 2.0.2 becomes better。

**Comment by FindDefinition** [comment]
@u1095279221321 what do you mean about "effect"? speed or detection mAP? the mAP should be completely same between spconv 1.x and spconv 2.0.2.
