### ISSUE TITLE
inquiry about  sparseInversrConv---> spatial shape (differences between in 1.2 & 2.1)

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#373]
Dear author,
sorry to bother you.

When I use the spconv.sparseInversrConv3d with kernel size 3 in version 2.1, I found that the features become to larger but the spatial shape become smaller, even to zero .

Is there any change? or is there some mistakes in my operation? I got confusing.

**Comment by FindDefinition** [comment]
that's a bug, fixed in spconv >= 2.1.4. you can upgrade spconv first.

**Comment by mengshiyu0109** [comment]
thanks a lot.
now ,it runs well!
