### ISSUE TITLE
VoxelGenerator or may call it Point2VoxelGPU[1-4]d does not work

### ISSUE THREAD

**Issue by yrh2526** [traveller59/spconv#376]
Model :pvrcnn. 
spconv cu114 installed 
here is my problem
the author notes VoxelGenerator has been replaced by Point2VoxelGPU[1-4]d/Point2VoxelCPU[1-4]d.
but when I tried to use Point2VoxelGPU1d and I changed the parameters name
error always occurs
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. spconv.core_cc.csrc.sparse.all.ops1d.Point2Voxel(vsize_xyz: List[float[1]], coors_range_xyz: List[float[2]], num_point_features: int, max_num_voxels: int, max_num_points_per_voxel: int)

Invoked with: kwargs: vsize_xyz=[0.05, 0.05, 0.1], coors_range_xyz=array([  0. , -40. ,  -3. ,  70.4,  40. ,   1. ], dtype=float32), num_point_features=4, max_num_voxels=5, max_num_points_per_voxel=16000

**Comment by FindDefinition** [comment]
1. the generator only accept ```List[float]```, but your argument is ```np.ndarray```.
2. I forget to update doc, users should use PointToVoxel (pytorch api) instead of Point2VoxelGPU[1-4]d. see [this example](https://github.com/traveller59/spconv/blob/master/example/voxel_gen.py).

**Comment by yrh2526** [comment]
>     1. the generator only accept `List[float]`, but your argument is `np.ndarray`.
> 
>     2. I forget to update doc, users should use PointToVoxel (pytorch api) instead of Point2VoxelGPU[1-4]d. see [this example](https://github.com/traveller59/spconv/blob/master/example/voxel_gen.py).
> 
> 
> wait, you are using Point2VoxelGPU **1** d, but you provide 3d arguments...

thanks for your answer.
I didn't notice that para x in Point2VoxelGPUxd represent the dim of arguments.
I use PointToVoxel instead of Point2VoxelGPUxd,but it seems that PointToVoxel  does not have the function like VoxelGenerator.
here is source coedes:

voxel_generator = PointToVoxel(args*)
voxel_output = voxel_generator.generate(points)
so is there any function can replace the generate() in VoxelGenerator?
