### ISSUE TITLE
error  in  pip install spconv-cu102,pytorch1.9 ,python3.6, 

### ISSUE THREAD

**Issue by emilypython** [traveller59/spconv#379]
![M(JY`B(BN3LR}X610K@XZA5](https://user-images.githubusercontent.com/34471918/141961173-43b27572-4aef-48b3-aef8-aebdf603fa0f.png)
Dear author,
I met the error when  installing. 

how can I do?
thanks a lot!

**Comment by FindDefinition** [comment]
this is a ccimport bug, fixed in new ccimport version, use ```pip install "ccimport>=0.3.3" -i https://pypi.python.org/simple``` to install new version.
