### ISSUE TITLE
subprocess error

### ISSUE THREAD

**Issue by He-Yunqian** [traveller59/spconv#38]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/he/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.0.176
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/he/spconv/build/temp.linux-x86_64-3.6
[ 14%] Built target spconv_nms
[ 35%] Built target spconv_utils
[ 42%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 57%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 64%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/ScalarType.h:5:0,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/Scalar.h:10,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/core/Type.h:8,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Type.h:2,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Context.h:4,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:5,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/script.h:3,
                 from /home/he/spconv/src/spconv/reordering.cc:16:
/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/util/typeid.h:345:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
In file included from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/ScalarType.h:5:0,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/Scalar.h:10,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/core/Type.h:8,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Type.h:2,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Context.h:4,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:5,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/script.h:3,
                 from /home/he/spconv/include/spconv/pool_ops.h:20,
                 from /home/he/spconv/src/spconv/all.cc:16:
/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/util/typeid.h:345:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
In file included from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/ScalarType.h:5:0,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/core/Scalar.h:10,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/core/Type.h:8,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Type.h:2,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/Context.h:4,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:5,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/torch/script.h:3,
                 from /home/he/spconv/include/spconv/spconv_ops.h:21,
                 from /home/he/spconv/src/spconv/indice.cc:17:
/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/util/typeid.h:345:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^
src/spconv/CMakeFiles/spconv.dir/build.make:101: recipe for target 'src/spconv/CMakeFiles/spconv.dir/reordering.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/reordering.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
src/spconv/CMakeFiles/spconv.dir/build.make:75: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/include/c10/util/typeid.h:345:21: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot be declared as constexpr because the implicit declaration is not constexpr:
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                     ^
src/spconv/CMakeFiles/spconv.dir/build.make:88: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cu.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cu.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/he/anaconda3/envs/python36/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/he/anaconda3/envs/python36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

I have tried by the steps on both win10 and ubuntu16.04 , neither could work
and the error is above 
I cant find out which step i did wrong  
thank you

**Comment by traveller59** [comment]
Why your log miss some information? could you please use ```python setup.py bdist_wheel``` instead of ```python setup.py install```?
I have no idea about this error. google tell me this is a gcc problem which can be solved by update gcc version. I am using ubuntu 18.04 with gcc 7.3 and cuda 10, I don't have ubuntu 16.04 environment to test code for now.

**Comment by He-Yunqian** [comment]
I have tried again on ubuntu18.04 and gcc and cuda are all the same as yours  but it still like above 
I would like to run the SECOND  but miss the spconv part is there another way to get the py file？

**Comment by He-Yunqian** [comment]
it is solved by install gcc5 which my used to be 7
