### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by FeliciaRu** [traveller59/spconv#381]
Hi,
I got the error in the title when using the new Voxelgenerator, although I was not using it on GPU.

I found that this line is the cause:
https://github.com/traveller59/spconv/blob/ab5e2e8e59603d56b035ecc3d939c0447405232c/spconv/pytorch/utils.py#L107

The stream should not be needed in cpu mode.

Thank you for your amazing work!

**Comment by FindDefinition** [comment]
Thanks for reporting this bug! will be fixed in spconv >= 2.1.10. we need 3 hours for prebuilts ready.
