### ISSUE TITLE
Question about grad_output

### ISSUE THREAD

**Issue by thangvubk** [traveller59/spconv#384]
Hi, 
I have a question related to ``grad_output``. In some indoor segmentation methods (such as PointGroup) they need to make ``grad_output`` as ``contiguous()`` to perform model training. Otherwise, there will be some optimization problem.

https://github.com/llijiang/spconv/blob/740a5b717fc576b222abc169ae6047ff1e95363f/spconv/functional.py#L41

However, in the official repo, the i don't see the ``contiguous()`` in ``grad_output``. 

https://github.com/traveller59/spconv/blob/b0ff62f37cd7cf4836ae18248ab674a0a13db11f/spconv/pytorch/functional.py#L74

I am quite confused here and I don't know why in segmentation methods they need to make ``grad_output`` as ``contiguous()``

**Comment by FindDefinition** [comment]
that's not a optimization problem, spconv 1.x ops can't accept non-contiguous tensor (for example, permuted tensors), non-contiguous tensor will cause wrong result.
In spconv 2.x, we will convert all tensor to contiguous if its non-contiguous tensor, see [this](https://github.com/traveller59/spconv/blob/b0ff62f37cd7cf4836ae18248ab674a0a13db11f/spconv/pytorch/ops.py#L793) and [this](https://github.com/traveller59/spconv/blob/b0ff62f37cd7cf4836ae18248ab674a0a13db11f/spconv/pytorch/ops.py#L1202).

**Comment by thangvubk** [comment]
Thank you for a quick response. It is now clear to me.
