### ISSUE TITLE
feel so bad mood with the question : cannot import name 'non_max_suppression_cpu' from 'spconv.utils

### ISSUE THREAD

**Issue by Baser-Bai** [traveller59/spconv#389]
need help please

**Comment by FindDefinition** [comment]
The "non_max_suppression_cpu" only exists in [spconv 1.x](https://github.com/traveller59/spconv/tree/v1.2.1), removed in spconv 2.x and we won't add it again, I recommend to use nms in [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py) or [torchvision](https://pytorch.org/vision/stable/ops.html#torchvision.ops.nms)

**Comment by Baser-Bai** [comment]
> The "non_max_suppression_cpu" only exists in [spconv 1.x](https://github.com/traveller59/spconv/tree/v1.2.1), removed in spconv 2.x and we won't add it again, I recommend to use nms in [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py) or [torchvision](https://pytorch.org/vision/stable/ops.html#torchvision.ops.nms)

Thank You. I got it.
