### ISSUE TITLE
cannot import name 'rbbox_iou_loss'

### ISSUE THREAD

**Issue by RickOnEarth** [traveller59/spconv#391]
@traveller59 Hi, thank you for your outstanding work. I am running some code from github and the spconv is needed. I face the problem  
 ` from spconv.utils import rbbox_iou, rbbox_iou_loss
ImportError: cannot import name 'rbbox_iou_loss'`.   
I am not sure which version of spconv was used in the code.
Could you tell me which version of spconv provides 'rbbox_iou_loss'?

**Comment by FindDefinition** [comment]
looks like [this repo](https://github.com/idenovix/bu_spconv) have that op.
since several user want this op, I will add it in next bug-fix release, may need several days.

**Comment by RickOnEarth** [comment]
> looks like [this repo](https://github.com/idenovix/bu_spconv) have that op. since several user want this op, I will add it in next bug-fix release, may need several days.

Thank you very much! It works.
