### ISSUE TITLE
1d function? Dear author? thanks 

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#394]
Dear author, it there any Conv1d api ?
I only find api for 2d and 3d

Thanks!

**Comment by FindDefinition** [comment]
They are added in spconv >= 2.1.8.
For now you can use spconv 2.1.11, 2.1.12 brings #381 back, and will be fixed in spconv 2.1.14.

**Comment by mengshiyu0109** [comment]
> They are added in spconv >= 2.1.8. For now you can use spconv 2.1.11, 2.1.12 brings #381 back, and will be fixed in spconv 2.1.14.

Dear author , could you give an example name of 1d api?   like  spconv.conv1d? 

thanks

**Comment by FindDefinition** [comment]
see [this line](https://github.com/traveller59/spconv/blob/master/spconv/pytorch/__init__.py#L7).
