### ISSUE TITLE
 x = x.replace_feature(F.relu(x.features))  dose not work

### ISSUE THREAD

**Issue by coallar** [traveller59/spconv#396]
In I follow "the Breaking changes in Spconv 2.x for spconv 1.x users" which recommends:
x.features = F.relu(x.features) now raise error. use x = x.replace_feature(F.relu(x.features)) instead.

details could be seen in the figure:
![image](https://user-images.githubusercontent.com/66529823/143725326-cd8a42de-1d1f-40f6-9230-5d62b910cbf6.png)

where self.act1 -> nn.LeaktyReLU()

while error still happens!

how could I solve this issue？thank you

**Comment by qsisi** [comment]
```
shortcut = shortcut.replace_feature(self.act1(shortcut.features))
```

**Comment by coallar** [comment]
> 

yes, fool am I, 
while another issue:
![image](https://user-images.githubusercontent.com/66529823/143725842-c46c84f0-ac57-4250-b6d2-a2d833843158.png)

similar solutions has tried, while error still breaks

**Comment by qsisi** [comment]
resA = resA.replace_feature(resA.features + shortcut.features)

**Comment by coallar** [comment]
the problem above has solved, while shape error breaks out.
details could be seen below:

![image](https://user-images.githubusercontent.com/66529823/143728033-3a843934-d071-41d4-b9b0-e855a44b4b91.png)

could you help me ?

**Comment by FindDefinition** [comment]
@coallar the indice_key of your subm layer is wrong, that layer use a previous indice with 3x3 = 9 ksize, but weight of this layer is 3x3x3 = 27.

**Comment by coallar** [comment]
> @coallar the indice_key of your subm layer is wrong, that layer use a previous indice with 3x3 = 9 ksize, but weight of this layer is 3x3x3 = 27.

thank you for your reply. it is the office code of the cylinder3D. I don`t know its input setting.

**Comment by FindDefinition** [comment]
@coallar this [cylinder module](https://github.com/xinge008/Cylinder3D/blob/master/network/segmentator_3d_asymm_spconv.py#L174) is definitely ill-formed sparse convolution. the reason that works well in spconv 1.x is that spconv 1.x doesn't check kernel size of layers that shared indice key. if subm layers share same key, they must have same spatial structure (indices), same kernel size and same dilation.
If two subm layers have different kernel size or dilation or spatial structure, you must assign a different indice key.

**Comment by coallar** [comment]
> 

well, thanks, i try to fix it  ^0^

**Comment by JohanBergius** [comment]
> @coallar the indice_key of your subm layer is wrong, that layer use a previous indice with 3x3 = 9 ksize, but weight of this layer is 3x3x3 = 27.



> @coallar this [cylinder module](https://github.com/xinge008/Cylinder3D/blob/master/network/segmentator_3d_asymm_spconv.py#L174) is definitely ill-formed sparse convolution. the reason that works well in spconv 1.x is that spconv 1.x doesn't check kernel size of layers that shared indice key. if subm layers share same key, they must have same spatial structure (indices), same kernel size and same dilation. If two subm layers have different kernel size or dilation or spatial structure, you must assign a different indice key.

Did you find any solution?

**Comment by MasterHow** [comment]
Same questions，any solution？

**Comment by JohanBergius** [comment]
> Same questions， any solution？
Take a look at:
https://github.com/xinge008/Cylinder3D/pull/113/commits/df586da89e6275b21370d46619409c42340e1401

**Comment by JohanBergius** [comment]
> Same questions，any solution？

https://github.com/xinge008/Cylinder3D/pull/113/commits/df586da89e6275b21370d46619409c42340e1401

**Comment by nakatomo8899** [comment]
how could I solve this issue？
![Screenshot from 2023-06-20 15-53-50](https://github.com/traveller59/spconv/assets/101164962/b9c1a8af-8b8c-4c2b-9778-99b1a8f25931)

**Comment by lyysl** [comment]
> how could I solve this issue？ ![Screenshot from 2023-06-20 15-53-50](https://private-user-images.githubusercontent.com/101164962/247030151-b9c1a8af-8b8c-4c2b-9778-99b1a8f25931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjU1NzMsIm5iZiI6MTcxODM2NTI3MywicGF0aCI6Ii8xMDExNjQ5NjIvMjQ3MDMwMTUxLWI5YzFhOGFmLThiOGMtNGMyYi05Nzc4LTk5YjFhOGYyNTkzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMTQxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTg2ODA2MTg2ZmIzZThlZTc0Nzk2N2QzNjY2MTViMjU4ZTBmZGQxMWU4ZWU5Y2Y4YzAxZGQxMDJkYTQ5OGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K0UoZYGbSjPIEDim-LeGQ0MXZjmbDwSpDUGFyNj6ZN4)

have you solved this?

**Comment by lyysl** [comment]
It works for me to change the script network/segmentator_3d_asymm_spconv.py using https://github.com/xinge008/Cylinder3D/issues/107
