### ISSUE TITLE
To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by gp1234567** [traveller59/spconv#397]
![image](https://user-images.githubusercontent.com/95198402/143799896-cf505736-53e8-426c-b812-d25194687052.png)

**Comment by FindDefinition** [comment]
you can't use cuda operations in forked process, this is a limit of CUDA, not spconv or pytorch. to use CUDA, you need to use spawn mode to start dataloader.
It's recommend to use CPU-only operations in dataloader, don't use CUDA in loader.

**Comment by gp1234567** [comment]
> you can't use cuda operations in forked process, this is a limit of CUDA, not spconv or pytorch. to use CUDA, you need to use spawn mode to start dataloader. It's recommend to use CPU-only operations in dataloader, don't use CUDA in loader.

but, i upgrade 2.1.16, the bug is fixed,why?

**Comment by FindDefinition** [comment]
v2.1.10 fix this bug, v2.1.12 add it again due to merge mistake, v2.1.16 fix it again.
