### ISSUE TITLE
ModuleNotFoundError: No module named 'spconv.utils'

### ISSUE THREAD

**Issue by chowkamlee81** [traveller59/spconv#40]
I followed the procedure and build exactly exactly the lib 
a) python setup.py bdist_wheel
b) cd ./dist
c) pip install spconv*.whl

but iam getting an error below:
from spconv.utils import rbbox_iou

Also iam unable to run python test/test_conv.py: Error below 
ModuleNotFoundError: No module named 'spconv.test_utils'

Kindly help

**Comment by yeliang2258** [comment]
I also encountered the same problem, have you solved it?

**Comment by simaker** [comment]
same here, any solutions?
