### ISSUE TITLE
1d function about definition

### ISSUE THREAD

**Issue by emilypython** [traveller59/spconv#402]
Dear author, 
If I have (npoint ,3)data, 
so I need to use xxconv1d function ,like SparseConv1d.

Could I get an example about using them?  I got a lot confused.
I dont know how to let an shape(npoint,3) data to the sparse one. 
thanks !

**Comment by FindDefinition** [comment]
your point cloud is 3d, so it's incorrect to apply 1d convolution.
conv1d in spconv need coords with shape [N, 2], ```coords[:, 0]``` is batch index, ```coords[:, 1]``` is 1d coord.
by the way, you may want 1d kernel instead of 1d data, just use (1, 1, 3)/(1, 3, 1)/(3 1, 1) as kernel size
example convert 3d point to sparse conv tensor:
```Python
from spconv.pytorch.utils import PointToVoxel
gen = PointToVoxel(vsize_xyz=[0.1, 0.1, 0.1],
                   coors_range_xyz=[-80, -80, -6, 80, 80, 6],
                   num_point_features=3,
                   max_num_voxels=5000,
                   max_num_points_per_voxel=5)
pc = np.random.uniform(-4, 4, size=[1000, 3])
pc_th = torch.from_numpy(pc)
voxels_th, indices_th, num_p_in_vx_th = gen(pc_th, empty_mean=True)
indices_th_batch_idx = torch.zeros((indices_th.shape[0], 1), dtype=indices_th.dtype, device=indices_th.device)
indices_with_batch = torch.cat([indices_th_batch_idx, indices_th], dim=1)
# here voxels_th is voxel that contains multiple point features, you need to do some operation and convert them to single point feature, for example, mean
voxel_single_feature = voxels_th.mean(dim=1)
sptensor = SparseConvTensor(voxel_single_feature, indices_with_batch, gen.grid_size)
```
