### ISSUE TITLE
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

### ISSUE THREAD

**Issue by SienChen1997** [traveller59/spconv#406]
Hi there, i run my code works well on spconv-cu111 2.0.2, after updating to 2.1.21,i get the error below:

> [Exception|implicit_gemm_pair]indices=torch.Size([1077968, 4]),bs=2,ss=[128, 128, 128],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[2, 2, 2],dilation=[2, 2, 2],subm=False,transpose=False
> SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
> Traceback (most recent call last):
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 192, in <module>
>     train(opt)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 122, in train
>     res, error = netG.forward(input, labels=label_tensor)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/HGPIFuNet.py", line 179, in forward
>     self.filter(filter_input)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/HGPIFuNet.py", line 89, in filter
>     self.vol_feat = self.volume_filter(heatmap)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/VolumeEncoder.py", line 30, in forward
>     out = self.net(x)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/modules.py", line 137, in forward
>     input = module(input)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 404, in forward
>     raise e
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 395, in forward
>     timer=input._timer)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 465, in get_indice_pairs_implicit_gemm
>     stream_int=stream)
> RuntimeError: /tmp/pip-build-env-k9ls5crx/overlay/lib/python3.7/site-packages/cumm/include/tensorview/cuda/launch.h(53)
> N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0
> (PIFu) cse@4-way-2080Ti-Server:/home/8T/cse/tocsn/PIFu_v2$ python -m apps.FQtrain_shape --name test_with_heatmap_test --use_heatmap --mini_dataset --freq_plot 20 --gpu_id 0 --num_threads 2 --batch_size 2 --num_gen_mesh_test 0
> cuda:0
> train data size:  7200
> test data size:  648
> initialize network with normal
> Using Network:  hgpifu
> set to train mode.
> ^CTraceback (most recent call last):
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 192, in <module>
>     train(opt)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 113, in train
>     heatmap_tensor = gen_heatmap(opt, joints_tensor_r)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/geometry.py", line 148, in gen_heatmap
>     heatmap_batch =torch.from_numpy(np.array(heatmap_batch))
> KeyboardInterrupt
> ^[[A(PIFu) cse@4-way-2080Ti-Server:/home/8T/cse/tocsn/PIFu_v2$ python -m apps.FQtrain_shape --name test_with_heatmap_test --use_heatmap --mini_dataset --freq_plot 20 --gpu_id 1 --num_threads 2 --batch_size 2 --num_gen_mesh_test 0
> cuda:1
> train data size:  7200
> test data size:  648
> initialize network with normal
> Using Network:  hgpifu
> set to train mode.
> [Exception|implicit_gemm_pair]indices=torch.Size([1213648, 4]),bs=2,ss=[128, 128, 128],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[2, 2, 2],dilation=[2, 2, 2],subm=False,transpose=False
> SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
> Traceback (most recent call last):
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 192, in <module>
>     train(opt)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/apps/FQtrain_shape.py", line 122, in train
>     res, error = netG.forward(input, labels=label_tensor)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/HGPIFuNet.py", line 179, in forward
>     self.filter(filter_input)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/HGPIFuNet.py", line 89, in filter
>     self.vol_feat = self.volume_filter(heatmap)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/mnt/8T/cse/tocsn/PIFu_v2/lib/model/VolumeEncoder.py", line 30, in forward
>     out = self.net(x)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/modules.py", line 137, in forward
>     input = module(input)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 404, in forward
>     raise e
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 395, in forward
>     timer=input._timer)
>   File "/home/cse/anaconda3/envs/PIFu/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 465, in get_indice_pairs_implicit_gemm
>     stream_int=stream)
> RuntimeError: /tmp/pip-build-env-k9ls5crx/overlay/lib/python3.7/site-packages/cumm/include/tensorview/cuda/launch.h(53)
> N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0
>

**Comment by FindDefinition** [comment]
could you specify env variable ```SPCONV_DEBUG_SAVE_PATH``` and run program again? this env will save a pickle file that contains some debug data, I can use it to debug.

**Comment by dhlrd** [comment]
> 

I encounter this problem too. my spconv version is 2.1.21, cuda 10.2. using SPCONV_DEBUG_SAVE_PATH does not save any file.

**Comment by dhlrd** [comment]
I have found the reason, my points are all out of range, so the valid number of points is zero, which causes the error.

**Comment by abhinavagarwalla** [comment]
I encountered the same error.
@FindDefinition  I was able to create the pickle file with debug data. It would be great if you could help me debug this! [debug.zip](https://github.com/traveller59/spconv/files/7975697/debug.zip)

@dhlrd How did you identify if the points were out of range or not.

**Comment by OrangeSodahub** [comment]
> I encountered the same error. For me, the ordering of indices and the spatial shape were messed up. The error disappeared after fixing that.



> I have found the reason, my points are all out of range, so the valid number of points is zero, which causes the error.

Hello, I occured this problem now. Could you say something more in detail how to solve this? Is there any trouble with my dataset? What is `points are all out of range` and `the ordering of indices and the spatial shape were messed up` mean?

**Comment by GostInShell** [comment]
> > I encountered the same error. For me, the ordering of indices and the spatial shape were messed up. The error disappeared after fixing that.
> 
> > I have found the reason, my points are all out of range, so the valid number of points is zero, which causes the error.
> 
> Hello, I occured this problem now. Could you say something more in detail how to solve this? Is there any trouble with my dataset? What is `points are all out of range` and `the ordering of indices and the spatial shape were messed up` mean?

I also encountered the same problem, and just solved it. The reasons are the same as @dhlrd @abhinavagarwalla. But I think a further explaination would avoid potential misunderstanding.  

So, the `points are all out of range` means the the coordinates `[x, y, z]` in the `indices` should be in the range of `[0, size]`, where `size` means the size of the voxel in x, y or z dimension.

**Comment by xiaotiancai899** [comment]
> 
Could you please give me your email address so that I can talk with you in detail about this issue?

**Comment by Lsmisl** [comment]
> I have found the reason, my points are all out of range, so the valid number of points is zero, which causes the error.

Could you elaborate on how you solved the problem? I had the same problem.   

SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.

**Comment by GostInShell** [comment]
Maybe just check the max value of `indices` along `xyz` , and make sure they are not bigger than the `size` of the voxel (meaning the number of voxels along corresponding axis).
