### ISSUE TITLE
No matching distribution found for spconv

### ISSUE THREAD

**Issue by blinnassime** [traveller59/spconv#409]
Hello, 

I wanted to install SpConv on my computer. I did pip install spconv but got this message :
$ pip3 install spconv
Collecting spconv
  Could not find a version that satisfies the requirement spconv (from versions: )
No matching distribution found for spconv

Could you please help ?

Thanks

**Comment by FindDefinition** [comment]
spconv only support python >= 3.6 in linux and python >= 3.7 in windows. python 3.5 isn't supported.
note: you need to use ```pip install spconv-cu102```/```pip install spconv-cu113```/... to install spconv with cuda, use ```pip install spconv``` only install cpu-only package.

**Comment by FindDefinition** [comment]
1. check your pip version, the system pip may be pip2, not pip3
2. you can try ```python3 -m pip install spconv-cu114```
3. you can try virtual environments such as venv and [anaconda](https://www.anaconda.com/products/individual)
