### ISSUE TITLE
Different result when changing parameters in spconv/core.py

### ISSUE THREAD

**Issue by gillbam** [traveller59/spconv#410]
I'm conducting experiments with spconv and cumm on an Ampere GPU. I removed most of the parameter groups in IMPLGEMM_TURING_PARAMS within spconv/core.py  and making only one parameter left:
`
IMPLGEMM_TURING_PARAMS = [
    *gen_conv_params(ConvFwdAndBwdInput, (32, 64, 32), (32, 32, 16),
                     NDIM_DONT_CARE,
                     ConvIterAlgo.Optimized,
                     2, ["f16,f16,f16,f16,f16"],
                     NHWC,
                     NHWC,
                     NHWC,
                     GemmAlgo.Turing,
                     TensorOpParams((16, 8, 8)),
                     mask_sparse=True,
                     increment_k_first=True,
                     access_per_vector=0)]
`
This led to a different result than before with test/benchmark.py, where nearly 90 % of resulting feature values are different from the original  IMPLGEMM_TURING_PARAMS. What I actually want to do is use only one fixed parameter group as above for all layers, I suppose different parameter groups(tile shape, warp tile shape) should only lead to different runtime efficiency. Is access_per_vector=0 inapplicable in some cases and it causes wrong results? Is there a parameter group that can handle all cases?

Many thanks.

**Comment by FindDefinition** [comment]
please use develop branch and this [test file](https://github.com/traveller59/spconv/blob/develop/test/test_all_algo.py), the ```branchmark.py``` isn't suitable for develop.

**Comment by gillbam** [comment]
> 1. please use develop branch and this [test file](https://github.com/traveller59/spconv/blob/develop/test/test_all_algo.py), the `branchmark.py` isn't suitable for develop.
> 2. don''t use access_per_vector=0, it's used to generate non-vector-load kernels for corner case, it's slow.

Thanks for the reply. For the 'corner case', do you mean something like the input layer whose input channel number is not a multiple of `element_per_acc `? Because when I use access_per_vector=1, the `supported_ldx_conv method` in `class ConvAlgoDesp` returns false due to incompatible ldx-element_per_accx combi.
