### ISSUE TITLE
Error when I import spconv.pytorch

### ISSUE THREAD

**Issue by qiaozhijian** [traveller59/spconv#413]
Hi~My problem is like this:

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spconv.pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.8/site-packages/spconv/pytorch/__init__.py", line 6, in <module>
    from spconv.pytorch.core import SparseConvTensor
  File "/root/anaconda3/lib/python3.8/site-packages/spconv/pytorch/core.py", line 21, in <module>
    from spconv.tools import CUDAKernelTimer
  File "/root/anaconda3/lib/python3.8/site-packages/spconv/tools.py", line 16, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/root/anaconda3/lib/python3.8/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
**ImportError: arg(): could not convert default argument 'timer: tv::CUDAKernelTimer' in method '<class 'spconv.core_cc.cumm.gemm.main.GemmParams'>.__init__' into a Python object (type not registered yet?)**

**My environment:**
Python: 3.8.5
Pytorch: 1.9.0
CUDA: 11.1
Ubuntu18.04
**spconv: installed by "pip install -U spconv-cu111"**

**By the way, I also have a similar issue as #324**

**Comment by qiaozhijian** [comment]
Merry Christmas🥳

**Comment by qiaozhijian** [comment]
I solved this problem by #405 !

**Comment by SaMeEr9597** [comment]
> I solved this problem by #405 !

> pip install -U cumm-cuxxx

I am getting the same error even after doing this, 

This is my cuda version and I used pip install -U cumm-cu114
<img width="535" alt="image" src="https://user-images.githubusercontent.com/96261162/158077388-bbb25aef-8b3a-46c3-9793-d602fd041466.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/96261162/158077494-e7defc9f-ee13-43b4-8020-25b469fd8d5e.png">
