### ISSUE TITLE
module 'spconv' has no attribute 'SparseSequential'

### ISSUE THREAD

**Issue by derrick-xwp** [traveller59/spconv#417]
'spconv' has no attribute 'SparseSequential'

**Comment by alakhag** [comment]
Any solution yet?

**Comment by rttariverdi67** [comment]
@derrick-xwp , @rulewan , @alakhag 
try 
from spconv.pytorch import SparseSequential

**Comment by msmekala** [comment]
try
from spconv.pytorch import SparseSequential

Replace spconv.SparseSequential => spconv.pytorch.SparseSequential in cmm.py

The above error solved
