### ISSUE TITLE
Question about the example code voxel_gen.py

### ISSUE THREAD

**Issue by YS-Kuang** [traveller59/spconv#419]
I have tested the "voxel_gen.py" in Colab, the functions without cuda runs well. But when I test the function with cuda for example  the "main_cuda()", I always get this error:

--> 106     voxels_tv, indices_tv, num_p_in_vx_tv = gen.point_to_voxel_hash(pc_tv)
    107     voxels_np = voxels_tv.cpu().numpy()
    108     indices_np = indices_tv.cpu().numpy()

RuntimeError: /tmp/pip-build-env-k9ls5crx/overlay/lib/python3.7/site-packages/cumm/include/tensorview/cuda/launch.h(53)
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

I didn't change anything in the code. The cuda version of colab is 11.1. Can anyone give some advice? Thank you so much.

**Comment by FindDefinition** [comment]
only spconv-cu102 support colab gpu (K80), spconv-cu111 don't support that.

**Comment by YS-Kuang** [comment]
Thanks a lot! I will try it. By the way happy new year!
