### ISSUE TITLE
ValueError: /io/include/tensorview/tensor.h(171) don't compiled with cuda

### ISSUE THREAD

**Issue by mengshiyu0109** [traveller59/spconv#423]
File "/usr/local/lib/python3.8/dist-packages/spconv/algo.py", line 618, in tune_and_cache
    inp = inp.clone()
ValueError: /io/include/tensorview/tensor.h(171)
don't compiled with cuda

**Comment by abreu4** [comment]
I'm getting the same error. Can you provide some more details like the full error message?

I'm running this with `spconv-cu114==2.1.21`

is the default `spcon` package required in parallel?

**Comment by Song-Jingyu** [comment]
I have the same error. It seems to be caused by using spconv.pytorch to replace spconv Ver 1. Waiting for a possible solution.

**Comment by mengshiyu0109** [comment]
> you need to install cumm-cuxxx instead of cumm. Unstall cumm first, then install cumm-cuxxx

Dear author,

I have installed  cumm & cumm-cu111
Do I need to  uninstall cumm, just keep cumm-cu111 ? thanks!
And I also met the error below：
![image](https://user-images.githubusercontent.com/88700988/149699786-144f4892-5c53-4639-99b0-a2b106585471.png)

**Comment by XGL-github** [comment]
i have the same problem. and I solve it by uninstall spconv-cu114 and install spconv-cu113. because my pytorch is torch1.10-cu113（my cuda is 11.4）. so i think spconv have to consistent with your torch not your cuda

**Comment by Dowe-dong** [comment]
Another soultion is change your version of spconv-cu11, that is helpful.
