### ISSUE TITLE
Load model between different version (spconv 1.x, spconv 2.x)

### ISSUE THREAD

**Issue by weihaosky** [traveller59/spconv#428]
Hi, my spconv version is 1.2 but I am loading a model trained with spconv-2.1. I note that the weight layout is different between spconv-1.2 and spconv-2.1, so I change the weight of the model from KRSC (spconv-2.x) to RSCK (spconv-1.x) with weights.permute([1,2,3,4,0]), but the result is still a mess. 
May I ask what else I need do? Many thanks!

**Comment by HelloRicky123** [comment]
Hi. 
I do not know whether you have solved the problem. I use the following function to transform models trained in spconv 1.x into spconv 2.x format.

```
def transform_spconv1_spconv2(pretrained_model):
    for key in pretrained_model['net'].keys():
        if 'xyzc_net' in key and 'weight' in key and pretrained_model['net'][key].dim() ==5:
            # print(key)
            # print(pretrained_model['net'][key].shape)
            pretrained_model['net'][key] = pretrained_model['net'][key].permute([4,0,1,2,3])

    for key in pretrained_model['optim']['state'].keys():
        if pretrained_model['optim']['state'][key]['exp_avg'].dim()==5:
            pretrained_model['optim']['state'][key]['exp_avg'] = pretrained_model['optim']['state'][key]['exp_avg'].permute([4,0,1,2,3])
            pretrained_model['optim']['state'][key]['exp_avg_sq'] = pretrained_model['optim']['state'][key]['exp_avg_sq'].permute([4,0,1,2,3])
    return pretrained_model
```

**Comment by Dipankar1997161** [comment]
> Hi. I do not know whether you have solved the problem. I use the following function to transform models trained in spconv 1.x into spconv 2.x format.
> 
> ```
> def transform_spconv1_spconv2(pretrained_model):
>     for key in pretrained_model['net'].keys():
>         if 'xyzc_net' in key and 'weight' in key and pretrained_model['net'][key].dim() ==5:
>             # print(key)
>             # print(pretrained_model['net'][key].shape)
>             pretrained_model['net'][key] = pretrained_model['net'][key].permute([4,0,1,2,3])
> 
>     for key in pretrained_model['optim']['state'].keys():
>         if pretrained_model['optim']['state'][key]['exp_avg'].dim()==5:
>             pretrained_model['optim']['state'][key]['exp_avg'] = pretrained_model['optim']['state'][key]['exp_avg'].permute([4,0,1,2,3])
>             pretrained_model['optim']['state'][key]['exp_avg_sq'] = pretrained_model['optim']['state'][key]['exp_avg_sq'].permute([4,0,1,2,3])
>     return pretrained_model
> ```

Could you tell me, where is this set of function residing in the code, like in which python file? I also have to transform from 1.x to 2.x.

I am new into this field so I am wondering.
Your help will be grateful

**Comment by Tony-syr** [comment]
> > Hi. I do not know whether you have solved the problem. I use the following function to transform models trained in spconv 1.x into spconv 2.x format.
> > ```
> > def transform_spconv1_spconv2(pretrained_model):
> >     for key in pretrained_model['net'].keys():
> >         if 'xyzc_net' in key and 'weight' in key and pretrained_model['net'][key].dim() ==5:
> >             # print(key)
> >             # print(pretrained_model['net'][key].shape)
> >             pretrained_model['net'][key] = pretrained_model['net'][key].permute([4,0,1,2,3])
> > 
> >     for key in pretrained_model['optim']['state'].keys():
> >         if pretrained_model['optim']['state'][key]['exp_avg'].dim()==5:
> >             pretrained_model['optim']['state'][key]['exp_avg'] = pretrained_model['optim']['state'][key]['exp_avg'].permute([4,0,1,2,3])
> >             pretrained_model['optim']['state'][key]['exp_avg_sq'] = pretrained_model['optim']['state'][key]['exp_avg_sq'].permute([4,0,1,2,3])
> >     return pretrained_model
> > ```
> 
> Could you tell me, where is this set of function residing in the code, like in which python file? I also have to transform from 1.x to 2.x. Or where to make the changes?
> 
> I am new into this field so I am wondering. Your help will be grateful

I don't know anything about your code, but I can imagine that when you read the pre-trained parameters from the stored pkl file into a variable called "pretrained_model" then pass it to this function
