### ISSUE TITLE
Assertion Error: inverse conv can only be used with standard conv and pool ops

### ISSUE THREAD

**Issue by abhinavagarwalla** [traveller59/spconv#430]
Thank you for your work!
I encountered this error while trying to upsample using `spconv.SparseInverseConv3d`. The error message isn't really clear to me.
What does this indicate, and how can one go about resolving this?

**Comment by ZXP-S-works** [comment]
The problem seems related to the corresponding SubMConv3d's index. Replace SubMConv3d to SparseConv3d and use it index worked for me.

This works:
'
class ExampleNet(nn.Module):
    def __init__(self):
        super().__init__()
        # when use submanifold convolutions, their indices can be shared to save indices generation time.
        self.conv1 = spconv.SparseConv3d(10, 64, 3, padding=1, indice_key="sp0")
        self.pool = spconv.SparseMaxPool3d(2, 2)
        self.conv2 = spconv.SparseConv3d(64, 64, 3, padding=1, indice_key="sp1")
        # self.conv3 = spconv.SparseConvTranspose3d(64, 64, 3, padding=1)
        self.up1 = spconv.SparseInverseConv3d(64, 64, 3, indice_key="sp1", bias=False)
        self.up0 = spconv.SparseInverseConv3d(64, 64, 3, indice_key="sp0", bias=False)
        self.todense = spconv.ToDense()  # convert spconv tensor to dense and convert it to NCHW format.
        self.conv4 = nn.Conv3d(64, 64, 3, padding=1)

    def forward(self, x):
        out = self.conv1(x)
        out = self.pool(out)
        out = self.conv2(out)
        out = self.up1(out)
        out = self.up0(out)
        out = self.todense(out)
        out = self.conv4(out)
        return out
'

This raises error:

`
class ExampleNet(nn.Module):
    def __init__(self):
        super().__init__()
        # when use submanifold convolutions, their indices can be shared to save indices generation time.
        self.conv1 = spconv.SubMConv3d(10, 64, 3, padding=1, indice_key="sp0")
        self.pool = spconv.SparseMaxPool3d(2, 2)
        self.conv2 = spconv.SparseConv3d(64, 64, 3, padding=1, indice_key="sp1")
        # self.conv3 = spconv.SparseConvTranspose3d(64, 64, 3, padding=1)
        self.up1 = spconv.SparseInverseConv3d(64, 64, 3, indice_key="sp1", bias=False)
        self.up0 = spconv.SparseInverseConv3d(64, 64, 3, indice_key="sp0", bias=False)
        self.todense = spconv.ToDense()  # convert spconv tensor to dense and convert it to NCHW format.
        self.conv4 = nn.Conv3d(64, 64, 3, padding=1)

    def forward(self, x):
        out = self.conv1(x)
        out = self.pool(out)
        out = self.conv2(out)
        out = self.up1(out)
        out = self.up0(out)
        out = self.todense(out)
        out = self.conv4(out)
        return out
`

**Comment by YilmazKadir** [comment]
I get the same error. I do not understand why we cannot use SparseInverseConv3d with SubMConv3d. Any solution to this?

**Comment by Kin-Zhang** [comment]
I also meet this error, and according to serveral open-source code using spconv, it's true that only `SparseConv3d` and `` together.

Here are some references:
[open-mmlab/mmdetection3d/blob/main/mmdet3d/models/backbones/minkunet_backbone.py#L94-L99](https://githubs.com/open-mmlab/mmdetection3d/blob/main/mmdet3d/models/backbones/minkunet_backbone.py#L94-L99)

```python
            input_conv = partial(
                make_sparse_convmodule, conv_type='SubMConv3d')
            encoder_conv = partial(
                make_sparse_convmodule, conv_type='SparseConv3d')
            decoder_conv = partial(
                make_sparse_convmodule, conv_type='SparseInverseConv3d')
```
As you can see even input_conv with similar model setup but they choose conv type to make afterward encoder (SparseConv3d) and decoder (SparseInverseConv3d)  works.
