### ISSUE TITLE
ImportError: cannot import name 'non_max_suppression' from 'spconv.pytorch.utils'

### ISSUE THREAD

**Issue by ZhuXiyue** [traveller59/spconv#431]
running second using spconv2.

**Comment by schmida736** [comment]
I had the same issue: 
`File "/home/user/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>`

`from spconv.utils import non_max_suppression`

`ImportError: cannot import name 'non_max_suppression' from 'spconv.pytorch.utils' (/home/user/.local/lib/python3.8/site-packages/spconv/pytorch/utils.py)`

I found a (probably temporary) fix: 
The file spconv/utils/__init__.py does not define a "non_max_suppression" function, but it **does** define a function called "non_max_suppression_cpu"
So I changed the import in the "nms_gpu.py" file to point to that function instead.

**Comment by InnocentYang1** [comment]
Is there any solutions?

**Comment by zzqjh** [comment]
> I had the same issue: `File "/home/user/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>`
> 
> `from spconv.utils import non_max_suppression`
> 
> `ImportError: cannot import name 'non_max_suppression' from 'spconv.pytorch.utils' (/home/user/.local/lib/python3.8/site-packages/spconv/pytorch/utils.py)`
> 
> I found a (probably temporary) fix: The file spconv/utils/**init**.py does not define a "non_max_suppression" function, but it **does** define a function called "non_max_suppression_cpu" So I changed the import in the "nms_gpu.py" file to point to that function instead.

does it works well in your training？
