### ISSUE TITLE
Distributed Data Parallel

### ISSUE THREAD

**Issue by min2209** [traveller59/spconv#432]
Hi, 

first, fantastic work! spconv is a gift to the ML/CV community. 

I'm having some issues using distributed data parallel with the package however. My environment is CUDA11.1, using spconv 2.1, installed using pip. 

I'm observing that certain pieces of data aren't being moved to the correct GPUs that are not rank 0. For example, to my understanding, the `torch_tensor_to_tv` function in `spconv/pytorch/cppcore.py` seems to be hardcoded to move data to GPU `0` in all cases: 

```
def torch_tensor_to_tv(ten: torch.Tensor,
                       dtype: Optional[int] = None,
                       shape: Optional[List[int]] = None):
    assert ten.is_contiguous(), "must be contiguous tensor"
    ptr = ten.data_ptr()
    device = ten.device
    if device.type == "cpu":
        tv_device = -1
    elif device.type == "cuda":
        tv_device = 0
    else:
        raise NotImplementedError
    if shape is None:
        shape = list(ten.shape)
    if dtype is None:
        dtype = _TORCH_DTYPE_TO_TV[ten.dtype]
    return tv.from_blob(ptr, shape, dtype, tv_device)
```

Are these limitations expected in the current version or am I misunderstanding something? 

Thanks!

**Comment by simo23** [comment]
Any updates on the use of spconv with multiple GPUs?
