### ISSUE TITLE
cuda error 700

### ISSUE THREAD

**Issue by Asthestarsfalll** [traveller59/spconv#437]
Environment：
Python: 3.8.8
torch: 1.10.0
cuda: 11.1
windows10
cumm: 0.3.0
pcmm: 0.3.4

![image](https://user-images.githubusercontent.com/72954905/154084193-3e992091-d49d-4a0a-a1a8-f8ceb709f585.png)
![image](https://user-images.githubusercontent.com/72954905/154082201-5e1d9109-5f11-4fd9-bc25-bd0df9456944.png)

**Comment by Divadi** [comment]
How did you resolve this?

**Comment by Divadi** [comment]
🤦 
If anyone else has the same issue, first my spatial_shape ordering was backwards. Then, my batch index was at the back when it should have been at the front of indices. Then, I forgot to put the actual sparse convolutional layer on cuda.

**Comment by Asthestarsfalll** [comment]
> 🤦 If anyone else has the same issue, first my spatial_shape ordering was backwards. Then, my batch index was at the back when it should have been at the front of indices. Then, I forgot to put the actual sparse convolutional layer on cuda.

yes, i made the same mistake, the input tensor and model was't simultaneous on cuda.
