### ISSUE TITLE
ImportError: cannot import name 'TensorOpParams' from 'cumm.gemm.algospec.core' 

### ISSUE THREAD

**Issue by SmBito** [traveller59/spconv#438]
Hi, I built **cumm** from source on Nvidia Jetson nano board, when I import **cumm** inside python, no errors appear.
But when import **TensorOpParams** as following: `from cumm.gemm.algospec.core import TensorOpParams` I got the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jetson/build_spconv/spconv3/spconv/spconv/__init__.py", line 15, in <module>
>     from . import build as _build
>   File "/home/jetson/build_spconv/spconv3/spconv/spconv/build.py", line 24, in <module>
>     from spconv.core import SHUFFLE_SIMT_PARAMS, SHUFFLE_VOLTA_PARAMS, SHUFFLE_TURING_PARAMS
>   File "/home/jetson/build_spconv/spconv3/spconv/spconv/core.py", line 18, in <module>
>     from cumm.gemm.algospec.core import TensorOpParams
> ImportError: cannot import name 'TensorOpParams' from 'cumm.gemm.algospec.core' (/home/jetson/build_spconv/spconv3/cumm/cumm/gemm/algospec/core.py)

Environment：
NVIDIA Jetson Nano Developer Kit  (aarch64)
Python: 3.7.5
cumm: 0.3.0
cuda: 10.2

Please help me!!! Thank you!

**Comment by superdocker** [comment]
Hi, I found that TensorOpParams is deleted in 0.3.0, but it exists in the prior version, 0.2.x 
So I change the version with the command, `git reset --hard bc8714d` of cumm repository, and install by following https://github.com/FindDefinition/cumm/tree/v0.2.8#build-in-your-environment.
