### ISSUE TITLE
Inconsistent results of SubMConv3d

### ISSUE THREAD

**Issue by ChaimBlau** [traveller59/spconv#442]
Hello,

I get different results when I run SubMConv3d for big point cloud (doesn't reproduce for smaller ones). It is pretty simple to reproduce:

````
import numpy as np
import spconv.pytorch as spconv 
from spconv.pytorch import SparseConv3d, SubMConv3d
import torch
co = np.stack((np.zeros(100_000), np.random.randint(0, 50, 100_000), np.random.randint(0, 2000, 100_000), np.random.randint(0, 2000, 100_000)), -1).astype(np.int32) 
unq = np.unique(co, axis=0)
features = np.random.rand(unq.shape[0], 5).astype(np.float32)
layer = SubMConv3d(5, 16, 3, bias=False).eval()
ten = spconv.SparseConvTensor(torch.tensor(features), torch.tensor(unq), [50, 2000, 2000], 1)
layer(ten).features.sum() == layer(ten).features.sum()
>> tensor(False)
````

I verified this on CPU only and GPU installation. Is this an expected behavior? 

Thanks!!

**Comment by oshrout** [comment]
Hey,
I have the same problem. It seems like there is a precision overflow when using float32, making inconsistent results.
I saw that for float16 there is an 'fp32_accum' flag that use float32 for the necessary part in the algorithm and return the result in float32 format. Perhaps a 'fp64_accum' flag is needed to alleviate this phenomena.
There is no support to float64 in the repository from what i've seen, @traveller59 will there be a support in the future?
