### ISSUE TITLE
spconv 1.0 - commit 8da6f96 ERROR

### ISSUE THREAD

**Issue by mreece813** [traveller59/spconv#448]
I am trying to run python setup.py bdist_wheel for the spconv 1.0. I am coming across an error and wondering if you could explain how to get past this or the reason for this error.
cmake verison = 3.22.3
torch version = 1.10.1+cu11
cuda version = 11.2
![image](https://user-images.githubusercontent.com/29603698/159021419-e6ce6a53-ca13-4f9a-82be-611afde5d64d.png)
![image](https://user-images.githubusercontent.com/29603698/159021484-664f88d0-1286-4d58-b28f-4ba4ba6a8716.png)

Any help is greatly appreciated!

**Comment by BitandPoly** [comment]
It seems like you need to download pybind11 by yourself and put it into the third_party direction.  Download link is here: https://github.com/pybind/pybind11/tree/3b1dbebabc801c9cf6f0953a4c20b904d444f879
