### ISSUE TITLE
Some issues after run "import spconv" during "Build from source for development "

### ISSUE THREAD

**Issue by Frank-DA** [traveller59/spconv#449]
At first, “from cumm.xx   import xxx " in spconv file was missing or named incorrectly.
 After the code is modified, new problems are encountered ：“subprocess.CalledProcessError: Command '['ninja']' returned non-zero exit status 1.”
My CUDA version is 10.2.I tried to reduce the pytorch version from 1.7 to 1.5, but I still haven't solved this problem.And 1.5 is the limit supported by cuda102.
So ,Can you give me some advice for this issue.

**Comment by Eddieeee-Liu** [comment]
I also get stack in this problem. Did you solve it?

**Comment by baiwuchang** [comment]
I also face the same problem, so what should I do?
