### ISSUE TITLE
Module 'VoxelGenerator', 'VoxelGenerator2 ' not found in spconv 2.1.21

### ISSUE THREAD

**Issue by jankin1024** [traveller59/spconv#452]
I am going to run the code which uses the spconv.util.VoxelGenerator, but it seems doesn't exist in spconv-cu113 2.1.21. And I find `Point2VoxelGPUxd` and `Point2VoxelCPUxd` in spconv.util and `Point2Voxel` in spconv.pytorch.util, so I am confused about them. Which method should I choose and how? Is there any example?  
Thanks.

**Comment by zyl1336110861** [comment]
Same question. At the same time, I failed to import spconv.utils.VoxelGeneratorV2.

**Comment by jankin1024** [comment]
> Same question. At the same time, I failed to import spconv.utils.VoxelGeneratorV2.
> 

I use the spconv 1 at last. It works now.

**Comment by zyl1336110861** [comment]
OK！ Can you tell me about your environment version? Such as cuda, python, pytorch?

**Comment by jankin1024** [comment]
> OK！ Can you tell me about your environment version? Such as cuda, python, pytorch?

cuda11.3 python3.7 torch1.11

**Comment by QiXueZhong** [comment]
Maybe you can find what you want. VoxelGeneratorV2 only in V1.2.1.
https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md

**Comment by wanzghen0123** [comment]
对于spconv-cu111/spconv-cu113(2.x版本):
  替换如下:
import spconv.pytorch as spconv
from spconv.utils import Point2VoxelCPU3d as VoxelGenerator

**Comment by ding1007** [comment]
spconv2.1  i use this:
from spconv.pytorch.utils import PointToVoxel as VoxelGenerator
