### ISSUE TITLE
No module named 'spconv.core_cc'

### ISSUE THREAD

**Issue by wdf19961118** [traveller59/spconv#454]
Traceback (most recent call last):
  File "./opencood/data_utils/pre_processor/sp_voxel_preprocessor.py", line 22, in __init__
    from spconv.utils import VoxelGeneratorV2 as VoxelGenerator
  File "/home/wangdanfeng/.pyenv/versions/pytorch-3.6.5/lib/python3.6/site-packages/spconv/utils/__init__.py", line 18, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "/home/wangdanfeng/.pyenv/versions/pytorch-3.6.5/lib/python3.6/site-packages/spconv/cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ModuleNotFoundError: No module named 'spconv.core_cc'

**Comment by Mud-B** [comment]
same problem.

**Comment by WangYibucea** [comment]
Also the Same Problem.

**Comment by WangHeng1021** [comment]
same problem.

**Comment by WangHeng1021** [comment]
Guys, I may have installed the wrong version of spconv. I uninstalled it and installed a different version by "pip install spconv-cu113" then problem solved!

**Comment by Xavier-wa** [comment]
> Guys, I may have installed the wrong version of spconv. I uninstalled it and installed a different version by "pip install spconv-cu113" then problem solved!

i have use pip3 install spconv-cu114 and my cuda is v11.4, but the problem still is not solved.

**Comment by xuldor** [comment]
same question，how to solve it？ @Xavier-wa

**Comment by Xavier-wa** [comment]
> same question，how to solve it？ @Xavier-wa

I change the version of spconv,and use source code to build the wheel file instead of download by pip3
