### ISSUE TITLE
How I use the state_dict from spconv1.X in spconv2.X 

### ISSUE THREAD

**Issue by Young98CN** [traveller59/spconv#456]
I have a model from spconv1.X training,and I have saved the weight dictionary(model.state_dict)  . But I want to use it in spconv2.X.How will I change my code?

```python
for k, v in checkpoint.items():
    if len(v.shape) == 5:
        pretrained_dict[k] = v.permute(4, 0, 1, 2, 3)
```

I tried to modify the code to change the weight dimension of spconv1.X, but the feature is **nan**  in **SparseInverseConv3d** 

Looking forward to your reply. Thank you

**Comment by hmax233** [comment]
@Young98CN hello,I have the same question, did you fix this problem? Can you share with me your way?
I will be very appreciated if you can share with me!

**Comment by YuQiao0303** [comment]
Hi，I just found a solution here:
https://github.com/thangvubk/SoftGroup/issues/105

This project provides a 'tools/convert_checkpoint.py'.

**Comment by Young98CN** [comment]
sorry, I haven't solved this yet. Maybe this method can solve your problem.https://github.com/traveller59/spconv/issues/456#issuecomment-1258886637

**Comment by Young98CN** [comment]
@hmax233 Sorry, I haven't solved this yet. Maybe this method can solve your problem.https://github.com/traveller59/spconv/issues/456#issuecomment-1258886637
