### ISSUE TITLE
RuntimeError:    N == input.dim(0) assert faild. error

### ISSUE THREAD

**Issue by MissShihongHowRU** [traveller59/spconv#460]
Hi, Thank you for the awesome work!  

When I tried to run my code which uses the spconv-cu102 == 2.1.4, I encountered the following error. The forwarding propagation is all well, this error occurs during the backward propagation.  I cannot understand the error message. Can you please give me some clue?  

============================================================================================
  
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/torch/autograd/function.py", line 87, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/torch/autograd/function.py", line 204, in wrapper
    outputs = fn(ctx, *args)
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 236, in decorate_bwd
    return bwd(*args, **kwargs)
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/spconv/pytorch/functional.py", line 146, in backward
    is_subm=is_subm)
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/spconv/pytorch/ops.py", line 1312, in implicit_gemm_backward
    stream=stream)
  File "/home/boden/miniconda3/envs/boostai-cylin3d/lib/python3.7/site-packages/spconv/algo.py", line 716, in run_with_tuned_result
    ConvMainUnitTest.implicit_gemm2(params)
RuntimeError: /io/build/temp.linux-x86_64-3.7/spconv/build/src/cumm/conv/main/ConvMainUnitTest/ConvMainUnitTest_implicit_gemm2.cu(2867)
N == input.dim(0) assert faild. error

============================================================================================

**Comment by harry1576** [comment]
Getting the same error - did you manage to find a solution?
Cheers,
Harry

**Comment by JoyboyWang** [comment]
Alright. I think my codes are different but similar issues cause the bug.  Thanks for your answer!

**Comment by Christic9** [comment]
Actually，I‘m **totally don't use the decoder blocks** and I still get this error.The purpose of using spconv is to encode my 
discrete 3d point feature vector to 3d space.Here is my code:

```
class SparseConvNet(nn.Module):
    def __init__(self,num_channels):
        super(SparseConvNet, self).__init__()

        self.conv0 = double_conv(num_channels, 16, 'subm0')
        self.down0 = stride_conv(16, 32, 'down0')

        self.conv1 = double_conv(32, 32, 'subm1')
        self.down1 = stride_conv(32, 64, 'down1')

        self.conv2 = triple_conv(64, 64, 'subm2')
        self.down2 = stride_conv(64, 128, 'down2')

        self.conv3 = triple_conv(128, 128, 'subm3')
        self.down3 = stride_conv(128, 128, 'down3')

        self.conv4 = triple_conv(128, 128, 'subm4')

    def forward(self, x):
        net = self.conv0(x)
        net = self.down0(net)

        net = self.conv1(net)
        net1 = net.dense()
        net = self.down1(net)

        net = self.conv2(net)
        net2 = net.dense()
        net = self.down2(net)

        net = self.conv3(net)
        net3 = net.dense()
        net = self.down3(net)

        net = self.conv4(net)
        net4 = net.dense()

        volumes = [net1, net2, net3, net4]

        return volumes


def single_conv(in_channels, out_channels, indice_key=None):
    return spconv.SparseSequential(
        spconv.SubMConv3d(in_channels,
                          out_channels,
                          1,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
    )


def double_conv(in_channels, out_channels, indice_key=None):
    return spconv.SparseSequential(
        spconv.SubMConv3d(in_channels,
                          out_channels,
                          3,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
        spconv.SubMConv3d(out_channels,
                          out_channels,
                          3,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
    )


def triple_conv(in_channels, out_channels, indice_key=None):
    return spconv.SparseSequential(
        spconv.SubMConv3d(in_channels,
                          out_channels,
                          3,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
        spconv.SubMConv3d(out_channels,
                          out_channels,
                          3,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
        spconv.SubMConv3d(out_channels,
                          out_channels,
                          3,
                          bias=False,
                          indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01),
        nn.ReLU(),
    )


def stride_conv(in_channels, out_channels, indice_key=None):
    return spconv.SparseSequential(
        spconv.SparseConv3d(in_channels,
                            out_channels,
                            3,
                            2,
                            padding=1,
                            bias=False,
                            indice_key=indice_key),
        nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.01), nn.ReLU())
```
So how to solve this error?Appreciate your time!
