### ISSUE TITLE
fatal error:THC/THCNumerics.cuh:No such file or directory

### ISSUE THREAD

**Issue by JiangSio** [traveller59/spconv#464]
while i install spconv 1.2.1 version ,i follow its manual but when i run
python setup.py bdist_wheel
this error occured, what should i do?

**Comment by RikaKagurasaka** [comment]
did you solve this? same error

**Comment by tommaoer** [comment]
Hi, I have tried this: comment on this line in that file. I pass the compile.

**Comment by ajinkyakhoche** [comment]
@tommaoer Sorry, which line in what file?

**Comment by airalcorn2** [comment]
@ajinkyakhoche - [this one](https://github.com/traveller59/spconv/blob/fad3000249d27ca918f2655ff73c41f39b0f3127/include/spconv/reordering.cu.h#L18).
