### ISSUE TITLE
How to copy boost headers to include path?

### ISSUE THREAD

**Issue by thom966** [traveller59/spconv#466]
Since I cannot use `sudo apt-get` command I choose to download compressed files from boost official website and copy headers to include path.
So, I have downloaded `libboost-all-dev_1.65.1.0ubuntu1_amd64.deb` file but I have no idea how to copy headers to include path.
Any help would be highly appreciated.

**Comment by linjie-yang** [comment]
I meet the same problem ！Have you solved it?
