### ISSUE TITLE
how to configure the skip connection layer of resnet architecture using the SparseConv3d?

### ISSUE THREAD

**Issue by poodarchu** [traveller59/spconv#478]
self.shortcut = SparseConv3d(64, 128, kernel_size=[1, 1, 1], stride=[2, 2, 2], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)

out = self.conv(x)
shortcut = self.shortcut(x)
out = replace_feature(out, out.features + shortcut.features)

this will raise an error:
 out.features != shortcut.features

**Comment by lyhsieh** [comment]
Same question
