### ISSUE TITLE
CUDA error 700 

### ISSUE THREAD

**Issue by antoniosilva9116** [traveller59/spconv#482]
I'm trying to implement SparseConvUNet for the PartA2 model similar or practically the same code as can be found in https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/models/backbones_3d/spconv_unet.py. For some reason I'm getting an error in this line: 
```
        input_sp_tensor = spconv.SparseConvTensor(
            features=voxel_features,
            indices=voxel_coords.int(),
            spatial_shape=self.sparse_shape,
            batch_size=batch_size
        )
        
        x = self.conv_input(input_sp_tensor) # this line
```
Running on the original OpenPCDet it works fine in my implementation I'm getting the following error:
```
- [Exception|implicit_gemm]feat=torch.Size([16000, 4]),w=torch.Size([16, 3, 3, 3, 4]),pair=torch.Size([27, 16000]),act=16000,issubm=True,istrain=True
- RuntimeError: /io/build/temp.linux-x86_64-3.9/spconv/build/src/cumm/gemm/main/GemmMainUnitTest/GemmMainUnitTest_stream_synchronize.cc(11)
```
The shape of voxel coords, voxel features and input sparse tensor are the following:
- INFO - 2022-06-01 17:10:34,201 - sparce_conv_unet - voxel_features shape: torch.Size([16000, 4])
- INFO - 2022-06-01 17:10:34,201 - sparce_conv_unet - voxel_coords shape: torch.Size([16000, 4]), type <class 'torch.Tensor'>
- INFO - 2022-06-01 17:10:34,201 - sparce_conv_unet - self.sparse_shape: [  41 1600 1408]
- INFO - 2022-06-01 17:10:34,201 - sparce_conv_unet - input_sp_tensor shape: [41, 1600, 1408]

I'm using batch size 1 to test if this value causes this. The shape of before mentioned parameters is the same as OpenPCDet. Can you help me solve this problem?

**Comment by hh-xiaohu** [comment]
same problem

**Comment by antoniosilva9116** [comment]
I'm literally stuck in this problem and don't know why! I have checked the input points, the voxels, and coordinates and all seem correct. @FindDefinition could you please help us to try to figure out what could trigger this error. My setup is as follows:
- Operating system: Ubuntu 20.04
- Python version: Python 3.9.12
- Open3D version: 0.15.2
- System type: x64 
- Is this remote workstation?: no
- How did you install Open3D?: pip with conda, pytorch installed via requirements-torch-cuda.txt
- Compiler version (if built from source): gcc 9.4.0

**Comment by antoniosilva9116** [comment]
I have finally a solution to this problem. The problem is that some layer in our network is CPU optimised instead of GPU (or vice versa). The spconv devs state the following on this page (https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md):
- test spconv 1.x model in spconv 2.x: Firstly set environment variable before run program, Then set all algo in conv/pool to ConvAlgo.Native. Linux: export SPCONV_FILTER_HWIO="1", Windows powershell: $Env:SPCONV_FILTER_HWIO = "1". WARNING test spconv 1.x model don't support implicit gemm algorithm.

Example:
```
self.conv_input = spconv.SparseSequential(
            spconv.SubMConv3d(input_channels, 16, 3, padding=1, bias=False,
                              algo=spconv.ConvAlgo.Native,  # CHANGE HERE
                              indice_key='subm1').to(device), # HERE
            norm_fn(16).to(device), # AND HERE
            nn.ReLU(),
        )
```
I hope that with this I helped people.
