### ISSUE TITLE
modes of deployment?

### ISSUE THREAD

**Issue by akshay-antony** [traveller59/spconv#489]
Does spconv support jit, onnx, or tensorrt? Or can we make it compatible with tensorrt? If not what method of inference is suggested?

**Comment by Bitfultea** [comment]
Hi @akshay-antony 
have u managed to find a solution for deploying spconv?

**Comment by sandeepnmenon** [comment]
Same question. Looking to deploy spconv models in tensorrt

**Comment by Byte247** [comment]
Any update here? Without deployment it becomes way less use full.
