### ISSUE TITLE
A question about SparseConvTensor dense()

### ISSUE THREAD

**Issue by YunjieYu** [traveller59/spconv#49]
Hi, Yan. Thanks for your great works! 

I have a question about SparseConvTensor.dense(). Specifically, what's the function of dense() and when should we use it? 

I'm looking forward to your reply.

Thanks in advance.

**Comment by traveller59** [comment]
that function convert a sparse tensor to channel last dense tensor. you should use it when you need to convert sparse tensor to dense.

**Comment by YunjieYu** [comment]
OK, thanks for your reply!
