### ISSUE TITLE
About spconv.SparseConv2d speed in FP32 and FP16.

### ISSUE THREAD

**Issue by StiphyJay** [traveller59/spconv#495]
Hello!

Thanks for your contribution! 
I have a problem when I use spconv2.x to measure speed. My backbone contains spconv.SparseConv2d , FP32 is faster than FP16, but when I test it according to your test sample, FP16 is faster. What is the reason?

Looking for your reply.

**Comment by yigetan0909** [comment]
hello, I have encountered the same problem as you. Have you found the solution?
Looking for your reply.
