### ISSUE TITLE
Error  compiling the code

### ISSUE THREAD

**Issue by ZeWang95** [traveller59/spconv#5]
Thank you so much for you excellent work!
When I was trying to compile the code, I got the following errors:
![image](https://user-images.githubusercontent.com/41649297/51498074-46660580-1d93-11e9-8bb7-d06072bf0647.png)
I'm using:
CUDA 9.0
Python 3.7
torch 1.0
gcc 5.5.0
Any idea how I can solve this?
Thank you so much!

**Comment by ZeWang95** [comment]
I tried update gcc to 6.5, and got some other wired errors.
Then I tried update my cuda from 9.0 to 9.2, now things work fine.
Thanks!

**Comment by bigsheep2018** [comment]
Hello @traveller59 ,

I got exact the same error in the same environment as @ZeWang95. I am planing to do as what @ZeWang95 say. May I know what is your environment (gcc/g++ 6.5 and cuda 9.2)?

Thanks.

**Comment by ZeWang95** [comment]
I used gcc 6.5 + cuda 9.2 to compile the code, and the code is compiled with no error but other errors occurred in my case when I was using the package.
I tried to compile everything on another machine with gcc 5.4 + cuda 9.2, and everything is perfect.

**Comment by bigsheep2018** [comment]
I see. I will try gcc  5.4 + cuda 9.2 first. Thanks.

**Comment by bigsheep2018** [comment]
Update:
Ubuntu 16.04 + gcc 6.5 + cuda 9.2 + cudnn 7.4.2 + nvidia driver 396.57 + pytorch 1.0 + python 3.7
I can compile the spconv and train secondv1.5 successfully. 
I tried to use gcc 7, a non-support error occur. 

Hope this might help.

**Comment by MadhavEsDios** [comment]
Can confirm @bigsheep2018 , I used the same config as yours but with python 3.6 and it works.
@traveller59 , it didnt compile with cuda 9 for me too !

**Comment by dhingratul** [comment]
The above setup also works with py 3.5
