### ISSUE TITLE
Could not find cudnn directory

### ISSUE THREAD

**Issue by sam6134** [traveller59/spconv#51]
while running setup.py my terminal gives the following ouput.
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/samarth/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/samarth/second.pytorch/second/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY) 
CMake Warning at /home/samarth/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:110 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/samarth/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/samarth/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:23 (find_package)

**Could anyone help me with this?**

**Comment by cmpute** [comment]
The reason could be that you haven't installed cudnn correctly

**Comment by M0LLYDAYU** [comment]
Have you solved this problem? 
Thx

**Comment by iris0329** [comment]
The reason could be that you haven't installed cudnn correctly
