### ISSUE TITLE
"No module named spconv.gencode" when get libspconv.so 

### ISSUE THREAD

**Issue by Q-wenny** [traveller59/spconv#516]
When I run run_build.sh to get libspconv.so, I met the issue "**No module named spconv.gencode**"
 
Can anybody help me resolve the issue? Thank you very much!

**Comment by FindDefinition** [comment]
You need to install spconv 2.2 first. Cpu version is enough for libspconv, use ```pip install spconv==2.2```.

**Comment by Q-wenny** [comment]
> You need to uninstall cumm/spconv/cumm-cuxxx/spconv-cuxxx first, then install spconv 2.2. Cpu version is enough for libspconv, use `pip install spconv==2.2`.

Thank you!
But I can‘t install spconv2.2.
```
ERROR: Could not find a version that satisfies the requirement spconv==2.2 (from versions: 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.1.18, 2.1.19, 2.1.20, 2.1.21, 2.1.22, 2.1.23, 2.1.24, 2.1.25)
ERROR: No matching distribution found for spconv==2.2
```
Do you know why?

**Comment by FindDefinition** [comment]
two possible reasons:
1. you are using python 3.6. python 3.6 reach EOL in 2021 so we drop support for it. you need to install python >= 3.7 to use spconv 2.2.
2. You are using a pypi mirror instead of download package from official pypi, mirrors need some time to sync new package.
If you live in china, you can use this command: ```pip install spconv==2.2 -i https://mirror.sjtu.edu.cn/pypi/web/simple```

**Comment by Q-wenny** [comment]
> two possible reasons:
> 
>     1. you are using python 3.6. python 3.6 reach EOL in 2021 so we drop support for it. you need to install python >= 3.7 to use spconv 2.2.
> 
>     2. You are using a pypi mirror instead of download package from official pypi, mirrors need some time to sync new package.
>        If you live in china, you can use this command: `pip install spconv==2.2 -i https://mirror.sjtu.edu.cn/pypi/web/simple`

I reinstalled python3.7 and solved it. Thank you!
