### ISSUE TITLE
From cumm: AttributeError: 'BuildMeta' object has no attribute 'add_public_includes'

### ISSUE THREAD

**Issue by NLCharles** [traveller59/spconv#517]
Running into this problem when importing spconv

**Comment by FindDefinition** [comment]
your pccm/ccimport version is too old, just update them to newest version if you want to use spconv 2.2.

**Comment by BigFishLi** [comment]
我也遇到了这个问题：
pip install pccm==0.3.4
pip install ccimport==0.3.7
就可以解决。
