### ISSUE TITLE
The generation method of input and output hash table on GPU

### ISSUE THREAD

**Issue by erwangccc** [traveller59/spconv#518]
Hi, @traveller59 

I'm interested in generation method of input and output hash table on GPU, and looking for the source cuda code at this repo, but it looks like there is no source cuda code about how to generate hash table at GPU. So could you send me some code or docs about that.

Thanks in advance.

**Comment by FindDefinition** [comment]
[here](https://github.com/FindDefinition/cumm/tree/main/include/tensorview/hash) is a simple gpu hash implementation based on [this](https://nosferalatu.com/SimpleGPUHashTable.html).
why not cuckoo hashing:  cuckoo hashing may fail to build, which isn't acceptable.
why not slab hashing (implemented in open3d): if number of items is small, slab is slower than simple hash.

**Comment by erwangccc** [comment]
Hi,@FindDefinition

Thank you for your reply. 

I found cuckoo hashing used at spconv-1.2.1 version, i can find some implementation at `src/cuhash` But it is not used anymore after spconv2.0, is it right?  
And i wonder to know that where is the cuda source code of hash table at master branch. Thank you~

**Comment by FindDefinition** [comment]
[this folder](https://github.com/FindDefinition/cumm/tree/main/include/tensorview/hash) contains all hash kernels used in spconv. the ```cumm``` is a core dependency of ```spconv```.
cuckoo is deprecated.
the implementation is based on [SimpleGPUHashTable](https://nosferalatu.com/SimpleGPUHashTable.html), that website is enough for description.

**Comment by erwangccc** [comment]
@FindDefinition 
Thank you very much~ It's enough for me
