### ISSUE TITLE
hash error

### ISSUE THREAD

**Issue by zhangcheng999** [traveller59/spconv#52]
collect2: error: ld returned 1 exit status
src/hash/CMakeFiles/cudahash_test.dir/build.make:102: recipe for target 'src/hash/cudahash_test' failed
make[2]: *** [src/hash/cudahash_test] Error 1
CMakeFiles/Makefile2:296: recipe for target 'src/hash/CMakeFiles/cudahash_test.dir/all' failed
make[1]: *** [src/hash/CMakeFiles/cudahash_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

执行python setup.py bdist_wheel报这个错，cuda9/cuda10都会，之前的版本没有这个问题

**Comment by traveller59** [comment]
could you provide full log? I can't get any useful information from your log.

**Comment by zhangcheng999** [comment]
抱歉，我那天估计没有clone完全代码，今天重新安装没有问题，谢谢
