### ISSUE TITLE
Where is the cuda code of generating rulebook and matrix multiplication on GPU

### ISSUE THREAD

**Issue by erwangccc** [traveller59/spconv#520]
Hi, @FindDefinition 

Sorry to bother you.
I want to learn the cuda code of how to generate rulebook and do matrix multiplication on GPU, but i didn't find where the code is at spconv2.x. So could you give some code path and some brief explanation. Thank you~

**Comment by FindDefinition** [comment]
[here](https://github.com/traveller59/spconv/blob/master/spconv/csrc/sparse/indices.py) is pairs (rulebook) generation code. You should check [python code](https://github.com/traveller59/spconv/blob/master/spconv/pytorch/ops.py#L132) first, you can check python code first and search c++ bind name when you encounter a c++ function in python code. c++ bind function in ```ops.py``` is [here](https://github.com/traveller59/spconv/blob/master/spconv/csrc/sparse/all.py),
gemm code base is maintained in another repo [cumm](https://github.com/FindDefinition/cumm.git).
all application c++ code is written in [PCCM](https://github.com/FindDefinition/PCCM.git) code generation framework. You can check real c++ code after built manually.
Build from source steps:
1. uninstall all spconv/cumm/spconv-cuxxx/cumm-cuxxx in your environment
2. clone spconv/cumm code (master or tag release)
3. enter cumm/spconv, run ```pip install -e .```
4. open a python REPL, run ```import spconv``` to trigger build.
after build, you will see generated code in spconv_repo/spconv/build.

**Comment by erwangccc** [comment]
Hi, @FindDefinition 

> 4. open a python REPL, run import spconv to trigger build.
> after build, you will see generated code in spconv_repo/spconv/build.

The following error occurs after i run import spconv.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/spconv/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/home/jovyan/spconv/spconv/spconv/build.py", line 70, in <module>
    pccm.builder.build_pybind(cus,
  File "/home/jovyan/.conda/envs/spconv/lib/python3.8/site-packages/pccm/builder/pybind.py", line 114, in build_pybind
    return ccimport.ccimport(
  File "/home/jovyan/.local/lib/python3.8/site-packages/ccimport/core.py", line 177, in ccimport
    shutil.copy(str(build_out_path), str(out_path))
  File "/home/jovyan/.conda/envs/spconv/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/jovyan/.conda/envs/spconv/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/spconv/spconv/spconv/build/core_cc/core_cc.cpython-38-x86_64-linux-gnu.so'
```
My env config as following. Is it lib version problem?
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
cryptography              37.0.4           py38h2b5fc30_0    conda-forge
cuda-nvcc                 11.4.48                       0    nvidia/label/cuda-11.4.0
cudatoolkit               11.3.1              h9edb442_10    conda-forge
cumm                      0.3.4                    pypi_0    pypi
cumm-cu114                0.3.4                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
libzlib                   1.2.12               h166bdaf_3    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.10.2.4                 pypi_0    pypi
numpy                     1.23.3           py38h3a7f9d9_0    conda-forge
pccm                      0.4.2                    pypi_0    pypi
pillow                    9.2.0            py38ha3b2c9c_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pybind11                  2.10.0                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
python                    3.8.13          h582c2e5_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.12.0          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
spconv                    2.2.3                    pypi_0    pypi
spconv-cu114              2.2.3                    pypi_0    pypi
sqlite                    3.39.3               h4ff8645_0    conda-forge
torchvision               0.13.0               py38_cu113    pytorch
```

**Comment by FindDefinition** [comment]
you need to remove installed ```spconv-cu114``` and ```cumm-cu114``` first.

**Comment by erwangccc** [comment]
Hi, @FindDefinition 

I removed `spconv-cu114` and `cumm-cu114`, enter cumm/spconv, run pip install -e .
Run import spconv to trigger build. It build so quick compared to early build.
after build, There is no generated code in spconv_repo/spconv/build. 

Could you give some tips for it? Thanks~

**Comment by FindDefinition** [comment]
you need to uninstall cpu version (```pip uninstall spconv cumm```) in your conda environment. if problem still exists, check [this line](https://github.com/FindDefinition/cumm/blob/main/cumm/__init__.py#L24) and find out why the build process not start

**Comment by erwangccc** [comment]
Hi, @FindDefinition 

I create a new envs and download a new repo to my local machine, and pip install. But there's still same error. I have checked the line you mentioned. I add some logs to it however it print nothing. So how to debug this code or do you have other advices.

Thanks~

**Comment by FindDefinition** [comment]
I can't reproduce your problem, please debug that line by yourself. 
e.g. check return values of ```project_is_installed```, ```project_is_editable``` and ```CUMM_DISABLE_JIT```.

**Comment by erwangccc** [comment]
Hi, @FindDefinition 

I have reinstalled spconv and import spconv from python REPL, it can be built successfully with cuda11.3.

And i wander that could we debug into this built cuda code when i run python code which will test spconv ops? Thanks in advance.

**Comment by FindDefinition** [comment]
I don't know how to debug cuda kernel in python script. to debug c++ code, you can go to spconv/build/core_cc and add breakpoints to generated c++ code.
