### ISSUE TITLE
int8 model quantization

### ISSUE THREAD

**Issue by shuyuan-wang** [traveller59/spconv#521]
Hi, just wondering if there's any tools which I can do int8 quantization? tensorrt's tool doesn't seem to work.

**Comment by FindDefinition** [comment]
int8 QAT support isn't available for now, it's work in progress, need several weeks to finish.

**Comment by shuyuan-wang** [comment]
Thanks, will it support nvidia's pytorch_quantization package?

**Comment by FindDefinition** [comment]
yes, we will support both pytorch native QAT and pytorch_quantization.
