### ISSUE TITLE
cannot imprort spcon2.2.x from pip

### ISSUE THREAD

**Issue by menma-at-here** [traveller59/spconv#522]
I tried to import spconv2.2.3 from pip, however I couldn't import it.
Errors are as below.
```
ERROR: Could not find a version that satisfies the requirement spconv-cu114==2.2.3 (from versions: 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.15, 2.1.16, 2.1.17, 2.1.18, 2.1.19, 2.1.20, 2.1.21, 2.1.24, 2.1.25)
ERROR: No matching distribution found for spconv-cu114==2.2.3
```
Could you add spcon2.2.x to PyPI ? Or should I build from source if I want to use spconv2.2.x ?

**Comment by FindDefinition** [comment]
spconv 2.2 drop support for python 3.6 due to [EOL](https://endoflife.date/python), please update your python.

**Comment by menma-at-here** [comment]
After creating virtual environment with pipenv and setting my environment to 3.8.0, spconv2.2.3 (and also cumm-cu114.3.4) can successfully be instaled ! Thank you so much.
