### ISSUE TITLE
tv::KernelLoopX<int> mean???

### ISSUE THREAD

**Issue by xiaoxifuhongse** [traveller59/spconv#525]
__global__ void getSubMIndicePairsKernel3(
    tv::TensorView<const Index> indicesIn, tv::TensorView<IndexGrid> gridsOut,
    tv::TensorView<Index> indicePairs, tv::TensorView<Index> indiceNum,
    const tv::SimpleVector<Index, 3> outSpatialShape, Index spatialVolume) 
{
 
  int point[3];
  int index = 0;
  int offset;
  int K0 = 3;
  int K1 = 3 ;
  int K2 = 3;
  int KV = K0 * K1 * K2;
  int center = KV / 2;

  *(indiceNum + center) = numActIn;
 for (int ix : tv::KernelLoopX<int>(numActIn)) 
  {
    printf("========%d, %d\n",blockIdx.x * blockDim.x + threadIdx.x, ix);  // print here 

    const int *indice_data = indicesIn + ix * (3 + 1);
#pragma unroll
    for (int i = 0; i < K0; ++i) 
    {
#pragma unroll
      for (int j = 0; j < K1; ++j) 
      {
#pragma unroll
        for (int k = 0; k < K2; ++k) 
        {
          offset = i * K1 * K2 + j * K2 + k;
        
          if (offset > center)
          {
            continue;
          }
          if (center == offset)
          {
              // center of subm indice pairs dont need atomicadd
              indicePairs[1*KV*numActIn+ offset*numActIn+ix] = ix;
              indicePairs[0*KV*numActIn+ offset*numActIn+ix] = ix;
           
          }
          else
          {
            point[2] = indice_data[3] - k + 1;//K2 / 2;
            point[1] = indice_data[2] - j + 1;//K1 / 2;
            point[0] = indice_data[1] - i + 1;//K0 / 2;
            if (point[1] >= 0 && 
                point[1] < outSpatialShape[1] &&
                point[2] >= 0 &&
                point[2] < outSpatialShape[2] && 
                point[0] >= 0 &&
                point[0] < outSpatialShape[0])
            {
                index = tv::ArrayIndexRowMajor<3, 3>::runPtrs(point, outSpatialShape.data(), 0) + spatialVolume * indice_data[0];
                if (gridsOut[index] != -1) 
                {
                    // for subm: indicePairs[0, i] = indicePairs[1, kernelVolume - i - 1]
                    int oldNum = atomicAdd(indiceNum + offset, 1);
                   atomicAdd(indiceNum + KV - offset - 1, 1);
                   indicePairs(1, offset, oldNum)          = gridsOut[index];
                   indicePairs(0, offset, oldNum)          = ix;
                   indicePairs(1, KV - offset - 1, oldNum) = ix;
                   indicePairs(0, KV - offset - 1, oldNum) = gridsOut[index];
              }
            }
          }
        }
      }
    }
  }

}
tv::KernelLoopX what that mean?

for example I set kernel<<<32, 1024>>> and numActIn=31930,
if I printf like above code,**
### printf("========%d, %d\n",blockIdx.x * blockDim.x + threadIdx.x, ix); // print here**

 the output not 31930 threads ,and get random number threads. why?
and run the kernel every time get different results? why?

**Comment by FindDefinition** [comment]
```KernelLoopX``` is a c++ version of ```CUDA_KERNEL_LOOP```:
```C++
#define CUDA_KERNEL_LOOP(i, n)                        \
  for (int i = blockIdx.x * blockDim.x + threadIdx.x; \
       i < (n);                                       \
       i += blockDim.x * gridDim.x)
```
```blockIdx.x * blockDim.x + threadIdx.x``` should be always equal to ```ix``` if you print them.
by the way, you are using old spconv 1.x code which is deprecated and not supported.

**Comment by xiaoxifuhongse** [comment]
@FindDefinition I understood it now, I using spconv1.2.1, but my second use it and get right result .
but when I Debug  the spconv1.2.1 indice.cu kernel. I  wander why my indices_pair result not equal the python result like the indiceNum does！  I run kernel every time got a different results ，and the value are all fix ,but result not fix.
