### ISSUE TITLE
Please provide spconv-cu116

### ISSUE THREAD

**Issue by mantkiew** [traveller59/spconv#526]
It would be great to support CUDA 11.6 because it is now also supported by PyTorch:

https://pytorch.org/get-started/locally/

Otherwise, the latest common version is 11.3.

**Comment by FindDefinition** [comment]
I will add cuda 11.6 and 11.8 prebuilt soon, for now you can use spconv-cu114 on any system that have nvidia driver >= 470 with pytorch + cu116, they should be compatible.

**Comment by mantkiew** [comment]
Thanks a lot!
```
Collecting spconv-cu116
  Downloading spconv_cu116-2.2.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (69.0 MB)
```
