### ISSUE TITLE
difference between 3060 and 3090

### ISSUE THREAD

**Issue by blazeCCC** [traveller59/spconv#527]
i have run spconv2.0 successfully with 3090, but i have a error result with 3060. all the environment are same. Can any one know the reason?

**Comment by FindDefinition** [comment]
could you provide the exact version of spconv you are using to debug, e.g. spconv 2.2.4 or spconv 2.1.25?

**Comment by FindDefinition** [comment]
I can't find any problem in RTX 3060 with [this file](https://github.com/traveller59/spconv/blob/master/test/test_multi_impl.py), which compare outputs between CPU and CUDA implementation. I need a minimal reproduce script to debug your problem.

**Comment by blazeCCC** [comment]
i use spconv 2.2.3 with source compile in ubuntu18. I haven't ruled out whether there is a problem with my code itself, and I am investigating.

**Comment by blazeCCC** [comment]
it's my fault in my code, i use two different cuda stream but sync only one of them. When the calculations are fast enough, bug was covered up.
