### ISSUE TITLE
Detailed Information About SparseConvTensor

### ISSUE THREAD

**Issue by aoligei178** [traveller59/spconv#528]
Hello! Thank you for your awesome work!
I notice that every SparseConvTensor has a member called "indice_dict", indice_dict has several ImplictGemmindiceData, I want to know what "mask_argsort_bwd_splits" and "mask_argsort_fwd_splits" means?
And I have another question! If I take 40960 points as input, I suppose that I get 10000 points after SparseConv3d(stride=2). Could I know which points are kept? For example, the first point in 10000 points is the ?th point in original 40960 points.

**Comment by aoligei178** [comment]
Emmmm.... I have another question, can I get which voxel is kept after SparseConv3d(stride=2)?

**Comment by FindDefinition** [comment]
mask_argsort_fwd_splits:
spconv 2.x sort valid kernel mask to make conv compute less invalid zeros, so we need a argsort to read inputs to match sorted mask.
 SparseConv3d(kernel_size=2, stride=2): four voxels merge to one, all input voxels are used to calculate a output voxel, so the "kept of voxel" is a wrong concept here.
