### ISSUE TITLE
Using spconv with complex data

### ISSUE THREAD

**Issue by YishaiEArbe** [traveller59/spconv#529]
Hi, 

Thanks for a great repo and libraries! Very useful for many projects. 

One question that I have, maybe you have already encountered this in your own work - is there a way to use the spconv library using complex data, by building it to use cuda's native complex data types and ops? 

Thanks!
Yishai

**Comment by FindDefinition** [comment]
complex data is currently not supported, currently spconv is mostly used in self-driving vehicles. could you share some info about complex use case?

**Comment by YishaiEArbe** [comment]
@FindDefinition Thanks for your reply. We are also thinking about it for automotive applications, for use on complex-valued 4D point clouds coming from imaging radar. 

Currently the complex values need to be encoded as channels, which create some inefficiencies and lose their native complex meaning unless you explicitly code the complex ops by separating channels and working on the real and imaginary parts separately (to my understanding, this is what is done in complex audio nets). This creates more inefficiencies. See, e.g., here:
https://arxiv.org/pdf/1705.09792.pdf
https://arxiv.org/pdf/2101.12249.pdf
(there are many more).
