### ISSUE TITLE
import error non_max_suppression from spconv.utils

### ISSUE THREAD

**Issue by dheerajgattupalli** [traveller59/spconv#53]
happening with  v1.1 ... no issues with v1 ....

**Comment by nlgranger** [comment]
Confirmed here as well, here is the traceback:

```
Traceback (most recent call last):
  File "second/create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "<...>/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "<...>/second.pytorch/second/data/kitti_dataset.py", line 11, in <module>
    from second.utils.eval import get_coco_eval_result, get_official_eval_result
  File "<...>/second.pytorch/second/utils/eval.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "<...>/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "<...>/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu
  File "<...>/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>
    from spconv.utils import non_max_suppression
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils'
```

**Comment by rfishrock** [comment]
Tried with cmpute's method, pity that still has this problem.

**Comment by yzhou377** [comment]
I concur with rfishrock, do we need a fresh new setup (re-run the setup file)?

**Comment by ZwwWayne** [comment]
meet the same problem, don't know why

**Comment by hly92711** [comment]
I met the same issue, how to solve it?

**Comment by cxxpython9** [comment]
After I installed spconv sucessfully on ubuntu, the same problem happened to me. Even though I installed spconv with the patch-1 version, it still happened.  I can not understand what had happed.

**Comment by Briwisdom** [comment]
same problem, any solutions?

**Comment by anshulpaigwar** [comment]
I am having a similar issue when training second.pytorch.

**Comment by ruguowoshiyu** [comment]
I solved this problem, it took a long time.I installed successfully on my own host,not met this error.but in my server,ImportError: cannot import name 'non_max_suppression' from 'spconv.utils' this error has happened. I compared the build folder on local host and server. in the /spconv/build/temp.xxxxx/ folder. if compile succeed, xx.cu appear. if failed, just exist xx.cc。the author of spconv implement nms in cuda only. if nvcc have problem or can not use due to incorrect installation, so it couldn't complie nms。when import non_max_suppression, the error will appear. i check my python env in my server. find torch.cuda.is_available() is False。so the problem is located: because torch or cuda wasn't installed incorrect, it led to torch.cuda.is_available() False,so nms wasn't complied.you can check torch.cuda.is_available(), if False, reinstall pytorch

**Comment by zhangfree2018** [comment]
@ruguowoshiyu , I have got 'detect_cuda_compute_capabilities.cu' and 'detect_cuda_version.cc' after compiled spconv.But this error still occurs. I also check my torch.cuda.is_available()， it's true.

**Comment by ruguowoshiyu** [comment]
@zhangfree2018, this is my print out when exe python setup bdist_wheel. you can compare with yours.
make sure nms.cu was complied. 

running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/guoyibo/anaconda3/envs/py36_torch/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data_1/guo/KITTI/git/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.5.0  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found torch: /home/guoyibo/anaconda3/envs/py36_torch/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.1
-- Found PythonInterp: /home/guoyibo/anaconda3/envs/py36_torch/bin/python3.6 (found suitable version "3.6.7", minimum required is "3.6") 
-- Found PythonLibs: /home/guoyibo/anaconda3/envs/py36_torch/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /data_1/guo/KITTI/git/spconv/build/temp.linux-x86_64-3.6
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
[  4%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[  9%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 14%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
**[ 19%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o**
[ 23%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
**[ 28%] Linking CUDA static library libspconv_nms.a**
[ 28%] Built target spconv_nms
Scanning dependencies of target spconv_utils
[ 33%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 38%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 42%] Linking CXX static library libcuhash.a
[ 42%] Built target cuhash
Scanning dependencies of target spconv
[ 47%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 52%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 57%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 61%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 66%] Building CXX object src/spconv/CMakeFiles/spconv.dir/nms.cc.o
[ 71%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 76%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 80%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[ 80%] Built target spconv_utils
[ 85%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
[ 90%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/pillar_scatter.cu.o
[ 95%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
@O@ptxas info    : 'device-function-maxrregcount' is a BETA feature
[100%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
[100%] Built target spconv
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1 -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/test_utils.py -> build/bdist.linux-x86_64/wheel/spconv
creating build/bdist.linux-x86_64/wheel/spconv/utils
copying build/lib.linux-x86_64-3.6/spconv/utils/__init__.py -> build/bdist.linux-x86_64/wheel/spconv/utils
copying build/lib.linux-x86_64-3.6/spconv/pool.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/modules.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/ops.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/functional.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.1 -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/__init__.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/conv.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/libspconv.so -> build/bdist.linux-x86_64/wheel/spconv
running install_egg_info
running egg_info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing top-level names to spconv.egg-info/top_level.txt
reading manifest file 'spconv.egg-info/SOURCES.txt'
writing manifest file 'spconv.egg-info/SOURCES.txt'
Copying spconv.egg-info to build/bdist.linux-x86_64/wheel/spconv-1.1-py3.6.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/spconv-1.1.dist-info/WHEEL
creating 'dist/spconv-1.1-cp36-cp36m-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'spconv/__init__.py'
adding 'spconv/conv.py'
adding 'spconv/functional.py'
adding 'spconv/libspconv.so'
adding 'spconv/modules.py'
adding 'spconv/ops.py'
adding 'spconv/pool.py'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.1'
adding 'spconv/test_utils.py'
adding 'spconv/utils/__init__.py'
adding 'spconv-1.1.dist-info/LICENSE'
adding 'spconv-1.1.dist-info/METADATA'
adding 'spconv-1.1.dist-info/WHEEL'
adding 'spconv-1.1.dist-info/top_level.txt'
adding 'spconv-1.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

**Comment by zhangfree2018** [comment]
@ruguowoshiyu ,thanks for your sharing. The log I got is the same as yours. I have a question, how to ensure that nms.cu is compiled ?

**Comment by ruguowoshiyu** [comment]
@zhangfree2018 , if your log is the same as mine. the cuda compilation of nms.cu is right.  Have you tried @cmpute method to modify path before loading?

**Comment by zhangfree2018** [comment]
@ruguowoshiyu ,Thank you very much for your feedback. I refered to your suggestion,but it is not solved. My error is that：
‘from spconv.utils import non_max_suppression
ImportError：cannot import name 'non_max_suppression’ from 'spconv.utils' (/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/spconv/utils/__init__.py)

Is there any other experience? I will try..........thanks!

**Comment by ruguowoshiyu** [comment]
I have no good idea and am very sorry that I have not been able to help you.

**Comment by zhangfree2018** [comment]
@ruguowoshiyu,thanks again! Can you send me a copy of spconv that you compiled successfully? I will compare it with yours. My e-mail address is 466908114@qq.com

**Comment by yzhou377** [comment]
> @ruguowoshiyu,thanks again!
> I temporarily solved this problem. I modified a statement in non_max_suppression.py. I changed "from ~ import non_max_suppression" to "try: ~ import ~, except ImportError：pass". I will try to verify whether this module has an impact on training.

I was using the same method. Things should work well for training only, bacause this part does not using nms at all. However, when we go into evaluation. This appears again to me as a problem. Are you experiencing the same issue?

**Comment by zhangfree2018** [comment]
@yzhou377 , you are right! This way is not effective completely. The problem you have occured is that because the spconv is not installed completely. I suggested that you should reinstall the spconv, and you should remove some packages created by "python setup.py bdist_wheel".

**Comment by chengdazhi** [comment]
The problem may be caused by not setting SPCONV_BuildCUDA to true in setup.py. 

You might want to first check if torch.cuda.is_available() returns true.

**Comment by yuanzheng-s** [comment]
python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=/media/maolei/work/second.pytorch/second/data/KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "./pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/home/maolei/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/maolei/second.pytorch/second/data/kitti_dataset.py", line 11, in <module>
    from second.utils.eval import get_coco_eval_result, get_official_eval_result
  File "/home/maolei/second.pytorch/second/utils/eval.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/maolei/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/maolei/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu
  File "/home/maolei/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>
    from spconv.utils import non_max_suppression
ImportError: cannot import name 'non_max_suppression'


cuda10.0 pytorch1.5.0 torchvision 0.6.0 spconv1.2 cmake3.13.3    is there anything wrong with my spconv version?  and my spconv/build/temp/   are detect_cuda_compute_capabilities.cpp  and  detect_cuda_version.cc

**Comment by yuanzheng-s** [comment]
> python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=/media/maolei/work/second.pytorch/second/data/KITTI_DATASET_ROOT
> Traceback (most recent call last):
> File "./pytorch/train.py", line 14, in
> import second.data.kitti_common as kitti
> File "/home/maolei/second.pytorch/second/data/**init**.py", line 1, in
> from . import kitti_dataset
> File "/home/maolei/second.pytorch/second/data/kitti_dataset.py", line 11, in
> from second.utils.eval import get_coco_eval_result, get_official_eval_result
> File "/home/maolei/second.pytorch/second/utils/eval.py", line 8, in
> from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
> File "/home/maolei/second.pytorch/second/core/non_max_suppression/**init**.py", line 1, in
> from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
> File "/home/maolei/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 8, in
> from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu
> File "/home/maolei/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in
> from spconv.utils import non_max_suppression
> ImportError: cannot import name 'non_max_suppression'
> 
> cuda10.0 pytorch1.5.0 torchvision 0.6.0 spconv1.2 cmake3.13.3 is there anything wrong with my spconv version? and my spconv/build/temp/ are detect_cuda_compute_capabilities.cpp and detect_cuda_version.cc

need help

**Comment by Giofist** [comment]
How can i check if spconv has been built with cuda enabled?
I'm having the same issue as you. torch.cuda.isavailable() returns true, I'm ussing cuda 10.0, pytorch 1.3.1 and build process end correctly. 
thanks in advance

**Comment by GYE19970220** [comment]
I have tried pytorch 1.1.0、1.2.0、1.3.1、1.4.0，and all of them meet the same problem that **cannot import name 'non_max_suppression**，any solutions？ @traveller59 @MartinHahner
`Traceback (most recent call last):
  File "./pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
ModuleNotFoundError: No module named 'spconv'
(spconv) gye@dell-DSS8440:~/PointCloud/objectDetection/second.pytorch/second$ python ./pytorch/train.py train --config_path=./configs/all.fhd.config --model_dir=test
Traceback (most recent call last):
  File "./pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/data/kitti_dataset.py", line 11, in <module>
    from second.utils.eval import get_coco_eval_result, get_official_eval_result
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/utils/eval.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu
  File "/home/gye/PointCloud/objectDetection/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>
    from spconv.utils import non_max_suppression
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils' (/home/gye/anaconda3/envs/spconv/lib/python3.7/site-packages/spconv/utils/__init__.py)`

**Comment by lixiang0** [comment]
I fix this problem by change code  `spconv.utils import non_max_suppression`  intead of  `from spconv.utils import non_max_suppression_cpu` in second/core/nums_gpu.py line 8 and line 16.

**Comment by Hetali-Vekariya** [comment]
> I fix this problem by change code `spconv.utils import non_max_suppression` intead of `from spconv.utils import non_max_suppression_cpu` in `second/core/non_max_suppression/nums_gpu.py` line 8 and line 16.

After making this change did you face any issue while training or evaluation?
Was it working fine after doing this change?
