### ISSUE TITLE
failure in  SpconvOps.sort_1d_by_key_allocator

### ISSUE THREAD

**Issue by ChaimBlau** [traveller59/spconv#530]
First of all - thanks so much for you great and useful tool!

spconv version 2.1.25
torch version 1.9.0

SubMConv3d raises this error:
`exception: no description
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/ops.py", line 357, in get_indice_pairs_implicit_gemm
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 404, in forward
    raise e
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/conv.py", line 404, in forward
    raise e
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1080, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/CenterPoint/det3d/models/backbones/scn.py", line 166, in forward
    x = self.conv_input(ret)`

Attached is the debugging information. 
The weird thing is that when I dump the input and call the layer, no error is raised
[spconv.log](https://github.com/traveller59/spconv/files/9903902/spconv.log)

**Comment by FindDefinition** [comment]
Your log is insufficient. I guess your problem is "failed in radix sort xxx step" or "invalid device function". it's a little hard to fix this in spconv 2.1, I recommend to use spconv 2.2 first and check whether it is fixed.

**Comment by ChaimBlau** [comment]
Thanks @FindDefinition, but I see that for my cuda version (11.1.1) spconv 2.1.25 is the latest available. Should I try a different version of spconv? Or it is not going to be resolved in this cuda version?

**Comment by FindDefinition** [comment]
you can install spconv 2.2 from source:
1. uninstall all spconv/cumm first, you can check by ```pip list | grep cumm``` and ```pip list | grep spconv```
2. clone spconv/cumm, run ```pip install -e .```
3. run ```python -c "import spconv"``` and wait the build finish.

**Comment by ChaimBlau** [comment]
Thanks for this quick response! Unfortunately, the build was failed:

`[1/39] [GCC][c++/pch]/home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch
FAILED: /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch 
g++ -MMD -MT /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch -MF /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch.d -I "/home/jovyan/cumm/cumm/build/core_cc/include" -I "/opt/conda/lib/python3.8/site-packages/pybind11/include" -I "/opt/conda/include/python3.8" -I "/usr/local/cuda/include" -I "/home/jovyan/cumm/include" -O3 -std=c++14 -fPIC -x c++-header -DTV_CUDA -c /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h -o /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h.gch
/home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
In file included from /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:5:
/home/jovyan/cumm/include/tensorview/cuda/nvrtc.h:25:10: fatal error: nvrtc.h: No such file or directory
   25 | #include <nvrtc.h>
      |          ^~~~~~~~~
compilation terminated.
[2/39] [GCC][c++/pch]/home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h.gch
FAILED: /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h.gch 
g++ -MMD -MT /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h.gch -MF /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h.gch.d -I "/home/jovyan/cumm/cumm/build/core_cc/include" -I "/opt/conda/lib/python3.8/site-packages/pybind11/include" -I "/opt/conda/include/python3.8" -I "/home/jovyan/cumm/include" -I "/usr/local/cuda/include" -O3 -std=c++14 -fPIC -x c++-header -DTV_CUDA -c /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h -o /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h.gch
/home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
In file included from /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:5,
                 from /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h:4:
/home/jovyan/cumm/include/tensorview/cuda/nvrtc.h:25:10: fatal error: nvrtc.h: No such file or directory
   25 | #include <nvrtc.h>
      |          ^~~~~~~~~
compilation terminated.
[3/39] [GCC][c++]/home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o
FAILED: /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o 
g++ -MMD -MT /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o -MF /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o.d -I "/home/jovyan/cumm/cumm/build/core_cc/include" -I "/opt/conda/lib/python3.8/site-packages/pybind11/include" -I "/opt/conda/include/python3.8" -I "/usr/local/cuda/include" -I "/home/jovyan/cumm/include" -O3 -std=c++14 -fPIC -DTV_CUDA -c /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc -o /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc.o
In file included from /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:5,
                 from /home/jovyan/cumm/cumm/build/core_cc/src/tensorview_bind/PyBindTensorViewBind/PyBindTensorViewBind_bind_TensorViewBind.cc:2:
/home/jovyan/cumm/include/tensorview/cuda/nvrtc.h:25:10: fatal error: nvrtc.h: No such file or directory
   25 | #include <nvrtc.h>
      |          ^~~~~~~~~
compilation terminated.
[4/39] [GCC][c++]/home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o
FAILED: /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o 
g++ -MMD -MT /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o -MF /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o.d -I "/home/jovyan/cumm/cumm/build/core_cc/include" -I "/opt/conda/lib/python3.8/site-packages/pybind11/include" -I "/opt/conda/include/python3.8" -I "/home/jovyan/cumm/include" -I "/usr/local/cuda/include" -O3 -std=c++14 -fPIC -DTV_CUDA -c /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc -o /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc.o
In file included from /home/jovyan/cumm/cumm/build/core_cc/include/tensorview_bind/TensorViewBind.h:5,
                 from /home/jovyan/cumm/cumm/build/core_cc/include/csrc/arrayref/ArrayPtr.h:4,
                 from /home/jovyan/cumm/cumm/build/core_cc/src/csrc/arrayref/PyBindArrayPtr/PyBindArrayPtr_bind_ArrayPtr.cc:2:
/home/jovyan/cumm/include/tensorview/cuda/nvrtc.h:25:10: fatal error: nvrtc.h: No such file or directory
   25 | #include <nvrtc.h>
      |          ^~~~~~~~~
compilation terminated.
[5/39] [GCC][c++]/home/jovyan/cumm/cumm/build/core_cc/src/core_cc_pybind_main/core_cc_pybind_main.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jovyan/spconv/spconv/__init__.py", line 15, in <module>
    from . import build as _build
  File "/home/jovyan/spconv/spconv/build.py", line 21, in <module>
    from .constants import PACKAGE_NAME, PACKAGE_ROOT, DISABLE_JIT
  File "/home/jovyan/spconv/spconv/constants.py", line 19, in <module>
    from cumm.gemm.constants import NVRTCMode
  File "/home/jovyan/cumm/cumm/__init__.py", line 28, in <module>
    pccm.builder.build_pybind([ArrayPtr(), TensorViewBind()],
  File "/opt/conda/lib/python3.8/site-packages/pccm/builder/pybind.py", line 114, in build_pybind
    return ccimport.ccimport(
  File "/opt/conda/lib/python3.8/site-packages/ccimport/core.py", line 155, in ccimport
    target_filename, no_work = build_simple_ninja(
  File "/opt/conda/lib/python3.8/site-packages/ccimport/buildtools/writer.py", line 1101, in build_simple_ninja
    raise subprocess.CalledProcessError(proc.returncode, cmds)`
    
My ninja version is 1.11.0

    Any ideas?

**Comment by ChaimBlau** [comment]
It seemed to be working well with `pip install spconv-cu113`, so this is good enough for me...

Thanks so much @FindDefinition !
