### ISSUE TITLE
Pooling gives negative indices (BUG?)

### ISSUE THREAD

**Issue by eddiewrc** [traveller59/spconv#532]
I tried to use Avg or Max pooling on my data.

I have a batch of 32 [65536, 65536] 2d sparse matrices. The batch contains a total of 1960260 points. Each point is a scalar value (1 channel only).

I try to use Avg or Max pooling, just doing SparseMaxPooling2d(kernelSize), with kernelSize equal to 2 or 4 (otherwise I trigger the assertion error at line 279 of pool.py).

Applying the sparse pooling, with kernelSize = 2, I obtain a batch V of  [32768, 32768] matrices with  541092 elements in total.

The very weird thing (a bug?) is that if I look a the indices of V (V.indices), they are negative. In particular

 t.min(V.indices) gives tensor(-32767, device='cuda:1', dtype=torch.int32)

Is this normal? What causes that? The indices are not that big to trigger an overflow of int32.

thanks in advance

**Comment by eddiewrc** [comment]
I see that this issue has been closed.

Could I ask 1) why this behavior happens? 2) is it intended? 3) how can I avoid it, or what can I do with it?

thanks

**Comment by FindDefinition** [comment]
This bug is fixed in spconv 2.2.5 (CI fail due to network problem)/2.2.6. you can wait for build finish or build from source.
