### ISSUE TITLE
which variable stores sparseconv output sparseconvtensor(features, indices, spatial_shape) in both subm and non-subm mode

### ISSUE THREAD

**Issue by hygxy** [traveller59/spconv#533]
I am researching on [main.cu](https://github.com/traveller59/spconv/blob/master/example/libspconv/main.cu) and have one quesiton(only consider the "kMaskImplicitGemm" situation):

How to get sparse convolution output sparseconvtensor both in subm and non-subm mode? the variable "conv_res" in [line 429](https://github.com/traveller59/spconv/blob/master/example/libspconv/main.cu#L429) is of type "std::tuple<int, ConvTuneResult>" and ConvTuneResult contains no information about the output sparseconvtensor(features, indices,spatial_shaple). So which variable stores the sparseconv output information?

**Comment by FindDefinition** [comment]
That's my mistake, that variable should be renamed to "conv_algo_meta" which only contains info of selected algorithm.
The ```spatial_shape``` is calculated [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L124), the indices is declared [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L188) and calculated by following function.

**Comment by hygxy** [comment]
> That's my mistake, that variable should be renamed to "conv_algo_meta" which only contains info of selected algorithm. The `spatial_shape` is calculated [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L124), the indices is declared [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L304) and calculated by following function.

In subm mode, the "out_inds" is just copyed from "indices" [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L311). But in non-subm mode, I can't see anywhere in code that updates "out_inds". Can I just pass [here](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L304)(maybe empty?) as output indices to next layer?

**Comment by FindDefinition** [comment]
it's passed via [allocator](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L357), origin code use (static) allocator to allocate outputs and save to allocator cache (return all outputs is better, maybe added in future), [here](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/pytorch/ops.py#L391) is python example. in real inference engine the output/workspace tensors are allocated once so we use a static allocator here. If you use a dynamic allocator, you may need to write a custom allocator inherit ```spconvlib::spconv::csrc::sparse::alloc::ExternalAllocator```.

**Comment by hygxy** [comment]
> it's passed via [allocator](https://github.com/traveller59/spconv/blob/v2.2.6/example/libspconv/main.cu#L357), origin code use (static) allocator to allocate outputs and save to allocator cache (return all outputs is better, maybe added in future), [here](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/pytorch/ops.py#L391) is python example. in real inference engine the output/workspace tensors are allocated once so we use a static allocator here. If you use a dynamic allocator, you may need to write a custom allocator inherit `spconvlib::spconv::csrc::sparse::alloc::ExternalAllocator`.

Ok thanks! I am now trying to call the c++ api of "get_indice_pairs_implicit_gemm()" and get one exception at "src/cumm/include/tensorview/tensor.h" called "cuda failed with error 1 invalid argument", the callstack looks as follows:
```
libc.so.6!__GI_raise(int sig) (/build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:50)
libc.so.6!__GI_abort() (/build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79)
libc.so.6!__assert_fail_base(const char * fmt, const char * assertion, const char * file, unsigned int line, const char * function) (/build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92)
libc.so.6!__GI___assert_fail(const char * assertion, const char * file, unsigned int line, const char * function) (/build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101)
tv::detail::TensorStorage<unsigned char>::zero_(tv::detail::TensorStorage<unsigned char> * const this, int64_t offset, int64_t length, tv::Context ctx) (~/cpp_engine/src/cumm/include/tensorview/tensor.h:224)
tv::Tensor::zero_(tv::Tensor * const this, tv::Context ctx) (~/cpp_engine/src/cumm/include/tensorview/tensor.h:1095)
spconvlib::spconv::csrc::sparse::alloc::StaticAllocator::zeros(spconvlib::spconv::csrc::sparse::alloc::StaticAllocator * const this, std::string name, std::vector<long, std::allocator<long> > shape, int dtype, int device, uintptr_t stream, bool is_temp_memory) (~/cpp_engine/src/spconv/src/spconvlib/spconv/csrc/sparse/alloc/StaticAllocator/StaticAllocator_zeros.cc:14)
spconvlib::spconv::csrc::sparse::alloc::ExternalAllocator::zeros_guard(spconvlib::spconv::csrc::sparse::alloc::ExternalAllocator * const this, std::vector<long, std::allocator<long> > shape, int dtype, int device, std::string name, uintptr_t stream) (~/cpp_engine/src/spconv/src/spconvlib/spconv/csrc/sparse/alloc/ExternalAllocator/ExternalAllocator_zeros_guard.cc:13)
spconvlib::spconv::csrc::sparse::all::SpconvOps::get_indice_pairs_implicit_gemm(spconvlib::spconv::csrc::sparse::all::ExternalAllocator & allocator, tv::Tensor indices, int batch_size, std::vector<int, std::allocator<int> > input_dims, int algo, std::vector<int, std::allocator<int> > ksize, std::vector<int, std::allocator<int> > stride, std::vector<int, std::allocator<int> > padding, std::vector<int, std::allocator<int> > dilation, std::vector<int, std::allocator<int> > out_padding, bool subm, bool transposed, bool is_train, uintptr_t stream_int, int num_out_act_bound, tv::CUDAKernelTimer timer, bool direct_table, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tv::Tensor, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tv::Tensor> > > preallocated) (~/cpp_engine/src/spconv/src/spconvlib/spconv/csrc/sparse/all/SpconvOps/SpconvOps_get_indice_pairs_implicit_gemm.cc:205)
SparseConvolution::forward(SparseConvolution * const this) (~/cpp_engine/src/main.cu:316)
``` 
and here are the exact function calls:
```checkCudaErrors(cudaMemsetAsync(data() + offset * sizeof(T), 0,length * sizeof(T), ctx.cuda_stream()));```
```storage_->zero_(byte_offset(), raw_size(), ctx);```
```return blob.zero_(tvctx);```
```auto ten = zeros(name, shape, dtype, device, stream, true);```
```auto uniqcnt = allocator.zeros_guard({1}, tv::int32, 0, "TightUniqueCount", stream_int);```

Could you please take a look and give some hints about the possible causes of this exception? thanks in advance!

**Comment by FindDefinition** [comment]
your problem looks so strange, could you provide a reproduce script? you can use ```tv::io``` to dump/load json + ```tv::Tensor``` and run a single spconv function in a simple cpp file. don't forget to run your program with CUDA_LAUNCH_BLOCKING=1.
common invalid argument reason in cuda memory apis:
1. invalid pointer (cuda can detect invalid memory pointer from a global perspective)
2. invalid length
3. invalid stream

**Comment by hygxy** [comment]
Ok I will give it a try. But firstly, how can I convert a tv::tensor to a json array so that it can be passed to the api "dump_to_ file(std::string path, const JsonArray& jarr)"?

**Comment by FindDefinition** [comment]
```C++
// Dump
tv::io::JsonArray jarr;
jarr.assign("arr0", tensor0); // data["arr0"] = tensor0
jarr.assign("vec_arr", std::vector<tv::Tensor>{...}); // data["arr1"] = [...]
jarr.assign("arr1", std::unordered_map<std::string, tv::Tensor>{...}); // data["arr2"] = {...}
auto& nested = jarr["nested"]; // nested = data["nested"]
nested.assign(...);
tv::io::dump_to_file(path, jarr);
// Read
auto jarr = tv::io::load_from_file(path);
auto arr0 = jarr.tensors[tv::access_idx(jarr.data["arr0"])];
auto vec = std::vector<tv::Tensor>{};
auto data1 = jarr.data["vec_arr"];
for (auto it = data1.begin(); it != data1.end(); ++it){
   vec.push_back(jarr.tensors[tv::access_idx(*it)]);
}
```

**Comment by hygxy** [comment]
During dumping, the following error occurs:
```
dev2host src/cumm/include/tensorview/cuda/driverops.h:105
cuda failed with error 1 invalid argument. use CUDA_LAUNCH_BLOCKING=1 to get correct traceback.
```
here is my code snippet for dumping:
```
tv::io::JsonArray jarr;
jarr.assign("indices_real", indices_real);
jarr.assign("ws_tensors", ws_tensors);
tv::io::dump_to_file(path, jarr);
```
The function ```get_indice_pairs_implicit_gemm``` requires ```indices_real``` and ```alloc```, which can be constructed from ```ws_tensors```. So I choose dump those two guys. Does the error mean that I should move the tensors firstly to cpu via ```.cpu()```, especially one by one for tensors stored as values in ```ws_tensors```?

**Comment by FindDefinition** [comment]
some cuda function produce error before your dump code, you need to figure out the exactly location of cuda error. you can insert some ```TV_CHECK_CUDA_ERR_V2("error");``` to check cuda error, don't forget to add CUDA_LAUNCH_BLOCKING=1

**Comment by hygxy** [comment]
This error is trigged when not enough [worksapce](https://github.com/traveller59/spconv/blob/master/example/libspconv/main.cu#L271) is allocated.
