### ISSUE TITLE
not implemented in c++, must be overrided in python!!!

### ISSUE THREAD

**Issue by hygxy** [traveller59/spconv#534]
when calling the ```ConvGemmOps::implicit_gemm``` api, I get the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  src/spconv/src/spconvlib/spconv/csrc/sparse/convops/convops/ConvTunerSimple/ConvTunerSimple_cached_get_nvrtc_params.cc(18)
not implemented in c++, must be overrided in python!!!
```
what possible causes could it be?

**Comment by FindDefinition** [comment]
libspconv currently don't support nvrtc (only available in python for best compatibility). This error means you run libspconv with unsupported arch or algo. could you provide the cuda arch you running and arch you compiled in libspconv? you can also debug [this](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/csrc/sparse/convops.py#L1090) and [this](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/csrc/sparse/convops.py#L1173) to figure out why that function is called.

**Comment by hygxy** [comment]
It's my mistake, I used another libspconv that is compiled with cuda_arch 7.5, rebuilding libspconv fixes the error

**Comment by hawl666** [comment]
> libspconv currently don't support nvrtc (only available in python for best compatibility). This error means you run libspconv with unsupported arch or algo. could you provide the cuda arch you running and arch you compiled in libspconv? you can also debug [this](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/csrc/sparse/convops.py#L1090) and [this](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/csrc/sparse/convops.py#L1173) to figure out why that function is called.

Hi,Does Jetson Orin support the latest libspconv?

This is my environment：

![Image](https://github.com/user-attachments/assets/b606ac4d-1ef9-4a9a-8f4a-534d232e51a9)
