### ISSUE TITLE
GemmTunerSimple_cached_get_nvrtc_params.cc

### ISSUE THREAD

**Issue by hlyyyyy** [traveller59/spconv#537]
After successfully building libspconv, I run the main executable program with the command `./main ../benchmark-pc.jarr`, but get errors below:

`terminate call after throwing an instance of 'std::runtime_error'`
`what(): /workspace/libspconv/spconv/src/spconvlib/spconv/csrc/sparse/convops/gemmops/GemmTunerSimple_cached_get_nvrtc_params.cc(18)`
`not implemented in c++, must be overrided in python!!!`
`Aborted (core dumped)`

Can you tell me how to deal with the error? Thanks a lot!

**Comment by FindDefinition** [comment]
This error means libspconv can't find your running gpu arch in prebuilt. you need to check libspconv build flag and your current gpu arch.

**Comment by hlyyyyy** [comment]
> This error means libspconv can't find your running gpu arch in prebuilt. you need to check libspconv build flag and your current gpu arch.

Thanks a lot, I have solved the error with your suggestion!
