### ISSUE TITLE
running time of libspconv

### ISSUE THREAD

**Issue by hlyyyyy** [traveller59/spconv#541]
Hi, thanks for your great work!

When I use `cudaEventRecord(start, stream) cudaEventRecord(stop, stream) cudaEventSynchronize(stop) cudaEventElapsedTime(&elapsedTime, start, stop)` to record running time of `point_to_voxel_hash_static`, I got unstable results.

The running time of 'voxelize' varies from 5ms to 100+ms, do you have any idea with this problem? Thanks a lot!

**Comment by FindDefinition** [comment]
this shouldn't happen, could you provide more information, for example
1. is this exists in unit test for point_to_voxel_hash_static?
2. do you run another cuda program at the same time / is gpu idle when you run spconv model?

**Comment by hlyyyyy** [comment]
> this shouldn't happen, could you provide more information, for example
> 
> 1. is this exists in unit test for point_to_voxel_hash_static?
> 2. do you run another cuda program at the same time / is gpu idle when you run spconv model?

I test  `point_to_voxel_hash_static` `get_indice_pairs_implicit_gemm` and `implicit_gemm` as in pics
![image](https://user-images.githubusercontent.com/56571316/207235379-0e2440ad-732b-4943-8f63-e144a8ce6438.png)
![image](https://user-images.githubusercontent.com/56571316/207235543-a28082ce-4773-4dea-97b2-8ec2509e43f9.png)
![image](https://user-images.githubusercontent.com/56571316/207235611-633000f7-0e0c-47ce-9f80-b9de882b7fc9.png)

and I got stable results, but the speed results are slower than 'benchmark', as in pics
![image](https://user-images.githubusercontent.com/56571316/207235944-e051b9b3-300c-468d-ae6a-6334e5d3a30e.png)

I use 3090 and didn't run any other program at the same time, I have no idea with this results.

**Comment by hlyyyyy** [comment]
But when I run `python -m spconv.benchmark bench_basic tf32`, I got normal results
![image](https://user-images.githubusercontent.com/56571316/207237461-7460ba5f-2e27-4ddc-8255-eb1dbc80a4d2.png)
I'm wondering if I used incorrect way to record the time?

**Comment by FindDefinition** [comment]
```implicit_gemm``` will run algorithm tuning in first run and cache result in ```tuner```, so the first running time is always greatly slower than subsequence runs.

**Comment by hlyyyyy** [comment]
Thanks a lot，when I run a for loop, subsequence running time gets faster!
