### ISSUE TITLE
what's the mean of nhw_to_npq

### ISSUE THREAD

**Issue by QING-ML** [traveller59/spconv#542]
In file https://github.com/traveller59/spconv/blob/master/spconv/csrc/sparse/indices.py, ConvOutLocIter, there is a concept of npq, that is used in CPU generate_subm_conv_ids. Could you introduce the meaning of npq

**Comment by FindDefinition** [comment]
npq/nhw come from dense conv, npq means output coordinates of a 2d conv, nhw means input coordinates.

**Comment by QING-ML** [comment]
thanks
