### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by C-hongfei** [traveller59/spconv#543]
Is this error due to a problem with my spconv installation? How to solve it?
![image](https://user-images.githubusercontent.com/57583118/208042400-7f8c8c15-e5ac-44ac-97ba-ab61ccd12e80.png)

**Comment by FindDefinition** [comment]
your cuda driver version is too low for spconv cuda version, you can use nvidia-smi to check highest supported cuda of current driver, then install a suitable spconv version.
