### ISSUE TITLE
Question about dtype of SparseConvIndicesCPU or SparseConvIndices

### ISSUE THREAD

**Issue by QING-ML** [traveller59/spconv#545]
I see the code in spconv2.0/csrc/sparse/all.py:71 The dtype of  SparseConvIndicesCPU and SparseConvIndices is initialized as int32, but the hash table index is from 0 to prod(input_dims). Prod(input_dims) is larger than max of int32 in the example mmdetection3d SECOND, in that input_dims =  [41, 1600, 1408]. why does the program run right now?

**Comment by FindDefinition** [comment]
in spconv 2.x, when we detect the int32 isn't enough for large spatial shape, we will use i64->i32 hash table instead of i32->i32.
see [code](https://github.com/traveller59/spconv/blob/v2.2.6/spconv/pytorch/ops.py#L461) here.

**Comment by QING-ML** [comment]
you're so nice, thanks
