### ISSUE TITLE
int8 tensorrt build

### ISSUE THREAD

**Issue by shuyuan-wang** [traveller59/spconv#554]
Hi, in the Tensorrt int8 Guide, it says use torch.fx.Interpreter to convert to tensorrt engine. However, in the example, I can't seem to find where the engine is being built. Is there anywhere I can find the building process?

**Comment by ShaunYang1** [comment]
Hi @shuyuan-wang  , have you figured out how to build for tensorrt? thanks !

**Comment by shuyuan-wang** [comment]
I put everything including sparseconvtensor and everything used in conv foward in c++. Maybe not the best solution.

**Comment by sandeepnmenon** [comment]
Any update on this?

**Comment by akjt** [comment]
@shuyuan-wang @traveller59 Any updates on this. I tried exporting to onnx but got a segfault, which makes me question whether spconv can be traced using onnx. 
It will be apprecated with a complete tensorrt example, including writing the handles and exporting the trt engine
