### ISSUE TITLE
Point2VoxelCPU3d import error in CPU

### ISSUE THREAD

**Issue by suryajayaraman** [traveller59/spconv#570]
Hi,

Firstly, thanks for the amazing library.

I'm trying to make use of Point2VoxelCPU3d in CPU environment. But, I get the import error when trying to do so:

![spconv_import_error](https://user-images.githubusercontent.com/17627202/222592473-943f9d82-ec5d-41d3-8512-b7393cb0eb4c.png)

I tried updating cumm version following [405](https://github.com/traveller59/spconv/issues/405) but still the error persists

**Environment**:
CPU-only 
OS : Ubuntu 
miniconda
spconv version : 2.3.3

![spconv_install](https://user-images.githubusercontent.com/17627202/222592506-1bc44f74-6b73-4932-b94e-5ce2cccdcf66.png)

It'd be great if someone can help solve this error

**Comment by Merealtea** [comment]
I met the same issue, any new solution?
