### ISSUE TITLE
unknown device type error

### ISSUE THREAD

**Issue by lonlonago** [traveller59/spconv#58]
I use k2200 GPU , does it not supported ?

**Comment by traveller59** [comment]
I think k2200 is supported, but you may need to use cuda 9.0+.

**Comment by lonlonago** [comment]
I use cuda 10, win10, compile is suscess.  I run simple_inference code.  seems much changes need to fix this code, here are some places need to fix: 
1  change_detection_range()    model_config  proto  changed; 
2   voxels, coords, num_points = voxel_generator.generate(points, max_voxels=90000)   too many value to unpack ;
3  pred = net(example)[0]     assert unknown device type error;

**Comment by MartinHahner88** [comment]
I get the same error using [PCDet](https://github.com/sshaoshuai/PCDet)

```
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main()
  File "train.py", line 210, in main
    max_ckpt_save_num=arguments.max_ckpt_save_num)
  File "/scratch_net/hox/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 80, in train_model
    leave_pbar=(cur_epoch + 1 == total_epochs)
  File "/scratch_net/hox/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 36, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/scratch_net/hox/mhahner/repositories/PCDet/pcdet/models/__init__.py", line 25, in model_func
    ret_dict, tb_dict, disp_dict = model(input_dict)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/hox/mhahner/repositories/PCDet/pcdet/models/detectors/PartA2_net.py", line 106, in forward
    rpn_ret_dict = self.forward_rpn(**input_dict)
  File "/scratch_net/hox/mhahner/repositories/PCDet/pcdet/models/detectors/PartA2_net.py", line 33, in forward_rpn
    **kwargs
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/hox/mhahner/repositories/PCDet/pcdet/models/rpn/rpn_unet.py", line 471, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/spconv/conv.py", line 177, in forward
    use_hash=self.use_hash)
  File "/home/mhahner/scratch/apps/anaconda3/envs/apex/lib/python3.7/site-packages/spconv/ops.py", line 93, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
ValueError: /scratch_net/hox/mhahner/repositories/spconv/include/spconv/spconv_ops.h 132
false assert faild. unknown device type
```

**Comment by MartinHahner88** [comment]
In case anyone wants to build spconv **v.1.0** ([commit 8da6f96](https://github.com/traveller59/spconv/tree/8da6f967fb9a054d8870c3515b1b44eca2103634))
with a fairly up-to-date conda environment, here is how we in our [lab](https://www.trace.ethz.ch/) were able to do it:

- download and unzip our [hotfixes](https://github.com/traveller59/spconv/files/4658204/hotfixes.zip)

- `conda create --name spconv python=3.7 pytorch=1.4 cudatoolkit=10.1 cudatoolkit-dev=10.1 cmake --channel pytorch`
- `conda activate spconv`
- `conda install cudnn`
- `git clone https://github.com/traveller59/spconv --recursive`
- `cd spconv`
- `git checkout 8da6f967fb9a054d8870c3515b1b44eca2103634`
- `git am <path_to_hotfixes>/0001-fix-problem-with-torch-1.4.patch`
- `git am <path_to_hotfixes>/0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch`
- `CUDA_ROOT=<path_to_your_conda_installation>/envs/spconv python setup.py bdist_wheel`
- `cd dist/`
- `pip install *`

Thank me later.

**Comment by MartinHahner88** [comment]
Here is an even better solution:

```
conda create --name PCDet python=3.6 pytorch=1.1 cudatoolkit=9.2 cudatoolkit-dev=9.2 \
cmake --channel pytorch --channel=conda-forge
conda activate PCDet
conda install cudnn
conda install boost
git clone https://github.com/traveller59/spconv spconv_8da6f96 --recursive
cd spconv_8da6f96
git checkout 8da6f967fb9a054d8870c3515b1b44eca2103634
```

> If necessary: 
> Download and extract 
> [0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch.zip](https://github.com/sshaoshuai/PCDet/files/4737235/0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch.zip)
> and patch _spconv_ via:
> ```git am <PATH_TO_EXTRACTED_FILE>/0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch```

```
CUDA_ROOT=<PATH_TO_YOUR_CONDA_INSTALLATION>/conda_envs/PCDet python setup.py bdist_wheel
cd dist/
pip install *
```
Test _spconv_ via:
`python -c 'import spconv'`
(should just return and not raise any errors) 

Done!

I hope these instructions help someone else who struggles to build _spconv_ as well.

**Comment by SternSu** [comment]
> Here is an even better solution:
> 
> ```
> conda create --name PCDet python=3.6 pytorch=1.1 cudatoolkit=9.2 cudatoolkit-dev=9.2 \
> cmake --channel pytorch --channel=conda-forge
> conda activate PCDet
> conda install cudnn
> conda install boost
> git clone https://github.com/traveller59/spconv spconv_8da6f96 --recursive
> cd spconv_8da6f96
> git checkout 8da6f967fb9a054d8870c3515b1b44eca2103634
> ```
> 
> > If necessary:
> > Download and extract
> > [0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch.zip](https://github.com/sshaoshuai/PCDet/files/4737235/0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch.zip)
> > and patch _spconv_ via:
> > `git am <PATH_TO_EXTRACTED_FILE>/0001-Allow-to-specifiy-CUDA_ROOT-directory-and-pick-corre.patch`
> 
> ```
> CUDA_ROOT=<PATH_TO_YOUR_CONDA_INSTALLATION>/conda_envs/PCDet python setup.py bdist_wheel
> cd dist/
> pip install *
> ```
> 
> Test _spconv_ via:
> `python -c 'import spconv'`
> (should just return and not raise any errors)
> 
> Done!
> 
> I hope these instructions help someone else who struggles to build _spconv_ as well.

Thank you very much for your help! This problem has puzzled me for a long time.

**Comment by lipengfeizju** [comment]
Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2

**Comment by MartinHahner88** [comment]
> Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2

If you don't need features in spconv v1.2 specifically, 
try spconv v1.0 (commit 8da6f967fb9a054d8870c3515b1b44eca2103634) and the introductions mentioned above.

**Comment by lipengfeizju** [comment]
> > Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2
> 
> If you don't need features in spconv v1.2 specifically,
> try spconv v1.0 (commit [8da6f96](https://github.com/traveller59/spconv/commit/8da6f967fb9a054d8870c3515b1b44eca2103634)) and the introductions mentioned above.

Thanks! It works now

**Comment by Xiangjun-Gao** [comment]
> > Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2
> 
> If you don't need features in spconv v1.2 specifically,
> try spconv v1.0 (commit [8da6f96](https://github.com/traveller59/spconv/commit/8da6f967fb9a054d8870c3515b1b44eca2103634)) and the introductions mentioned above.

Hi, martin, I install spconv and run it correctly in a docker image, I release this image and use Microsoft azurel cloud server to pull this image, the program doesn't work with an `unknown device type error`.  Do you know the reason, thanks.

**Comment by MartinHahner** [comment]
> > > Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2
> > 
> > 
> > If you don't need features in spconv v1.2 specifically,
> > try spconv v1.0 (commit [8da6f96](https://github.com/traveller59/spconv/commit/8da6f967fb9a054d8870c3515b1b44eca2103634)) and the introductions mentioned above.
> 
> Hi, martin, I install spconv and run it correctly in a docker image, I release this image and use Microsoft azurel cloud server to pull this image, the program doesn't work with an `unknown device type error`. Do you know the reason, thanks.

Hi Xiangjun, you probably need to install spconv directly on the server, otherwise the `device type` (GPU) does not match. I assume the server uses different GPUs.

**Comment by Xiangjun-Gao** [comment]
> > > > Hi, I use a 2080ti GPU and encounter similar problem (unknown device type). Is this model not supported ? I am in spconv v1.2
> > > 
> > > 
> > > If you don't need features in spconv v1.2 specifically,
> > > try spconv v1.0 (commit [8da6f96](https://github.com/traveller59/spconv/commit/8da6f967fb9a054d8870c3515b1b44eca2103634)) and the introductions mentioned above.
> > 
> > 
> > Hi, martin, I install spconv and run it correctly in a docker image, I release this image and use Microsoft azurel cloud server to pull this image, the program doesn't work with an `unknown device type error`. Do you know the reason, thanks.
> 
> Hi Xiangjun, you probably need to install spconv directly on the server, otherwise the `device type` (GPU) does not match.
> I assume the server uses different GPUs.

Yeah, I build it on Tesla M40, but run it on V100, anyway, I will try to build it on V100.
