### ISSUE TITLE
error when setup: more than one operator ">"/"==" matches these operands

### ISSUE THREAD

**Issue by ShioHZY** [traveller59/spconv#585]
my environment: ubuntu 22.04, gcc-9, g++-9, cuda 11.6, python 3.8, pytorch 1.12

when i run "python setup.py bdist_wheel"：
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shioh/save_source/IA-SSD/spconv1.0/build/temp.linux-x86_64-cpython-38
[  7%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 15%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 23%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 30%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 38%] Linking CUDA shared library ../../../lib.linux-x86_64-cpython-38/spconv/libspconv_nms.so
[ 38%] Built target spconv_nms
[ 46%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
// a lot of warnings about /spconv1.0/include/torch_utils.h
[ 53%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
[ 61%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 69%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 76%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
// a lot of errors here, more than one operator ">" (or "==") matches these operands, like:
/home/shioh/save_source/IA-SSD/spconv1.0/src/spconv/maxpool.cu(116): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
/usr/local/cuda/include/cuda_fp16.hpp(296): here
operand types are: c10::Half > c10::Half
          detected during:
            instantiation of "void spconv::maxPoolFwdVecBlockKernel<T,Index,NumTLP,NumILP,VecType>(T *, const T *, const Index *, const Index *, int, int) [with T=c10::Half, Index=int, NumTLP=64, NumILP=16, VecType=int2]"
/home/shioh/save_source/IA-SSD/spconv1.0/include/spconv/mp_helper.h(16): here
            instantiation of "F spconv::detail::mp_for_each_impl(spconv::mp_list<T...>, F &&) [with T=<std::integral_constant<int, 64>, std::integral_constant<int, 32>, std::integral_constant<int, 16>>, F=lambda [](auto)->auto]"
/home/shioh/save_source/IA-SSD/spconv1.0/include/spconv/mp_helper.h(43): here
            instantiation of "F spconv::mp_for_each<L,F>(F &&) [with L=spconv::mp_list<std::integral_constant<int, 64>, std::integral_constant<int, 32>, std::integral_constant<int, 16>>, F=lambda [](auto)->auto]"
(351): here
            instantiation of "void spconv::functor::SparseMaxPoolForwardFunctor<tv::GPU, T, Index>::operator()(const tv::GPU &, tv::TensorView<T, -1>, tv::TensorView<const T, -1>, tv::TensorView<const Index, -1>, int) [with T=c10::Half, Index=int]"
(467): here
/home/shioh/save_source/IA-SSD/spconv1.0/src/spconv/maxpool.cu(262): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
/usr/local/cuda/include/cuda_fp16.hpp(294): here
            operand types are: c10::Half == c10::Half
          detected during:
            instantiation of "void spconv::maxPoolBwdVecBlockKernel<T,Index,NumTLP,NumILP,VecType>(const T *, const T *, const T *, T *, const Index *, const Index *, int, int) [with T=c10::Half, Index=int, NumTLP=64, NumILP=16, VecType=int2]"

**Comment by lacie-life** [comment]
I met the same error. Have you solved it?

**Comment by ShioHZY** [comment]
@lacie-life 
I changed the version of Ubuntu and used "pip install spconv" (see the details on the official website). But another library associated with it has problems as well, i used docker finally without installing spconv.
