### ISSUE TITLE
sparse convolution(non subm) real out_inds in c++

### ISSUE THREAD

**Issue by shuyuan-wang** [traveller59/spconv#592]
I'm trying to write tensorrt plugin. I can correctly get pairs for subm conv. However, when the convolution is not subm, the out_ids is not the same as the one I got from pytorch. is the outids not sorted in newest version?

**Comment by shuyuan-wang** [comment]
is the out_ids in non-subm convolution not sorted?

**Comment by FindDefinition** [comment]
yes, the order of out inds of regular conv is undefined when you set direct_table to True. If false, the order is sorted.
You should always use sparse add instead of direct compare when you compare sparse results.
