### ISSUE TITLE
parameter of PointToVoxel: clear_voxels

### ISSUE THREAD

**Issue by shawnding** [traveller59/spconv#593]
https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/pytorch/utils.py#L80

I don't understand the parameter `clear_voxels` here. It says "call zero on voxels" and it defaults to `True`. Does it mean that the features of the generated voxels will be all zeroes regardless of the input points?

I tried to check the source code of its implementation, but I'm not quite familiar with CUDA. Any help would be appreciated!

**Comment by FindDefinition** [comment]
voxels are padded to maximum number of points in one voxel. If you set clear_voxels to false, the value in padding part of voxel is undefined (may be value calculated in previous call). If you set it, we will clear whole voxel tensor before do any operation to make sure all voxel value is defined.

**Comment by shawnding** [comment]
Very clear, thanks!
