### ISSUE TITLE
Error when using SparseInverseConv3d

### ISSUE THREAD

**Issue by Benzlxs** [traveller59/spconv#6]
https://github.com/traveller59/spconv/blob/b9bc9d4e1753081c01c3368b953c3d596a831270/spconv/conv.py#L297

Hey, when using spconv.SparseInverseConv3d(64, 32, 3, 2,indice_key="cp0") mentioned in the Readme file, the error message is multiple arguments for indice_key. The `class SparseInverseConv3d(SparseConvolution):` has no `kernel_size` and `stride` argument options. 

Should `SparseConvTranspose3d(64, 32, 3, 2,indice_key="cp0")` be used for deconvolution instead of using `SparseInverseConv3d` ?

**Comment by traveller59** [comment]
That's my mistake, SparseInverseConv3d shouldn't take any conv params, because it use indices from "couple" convolution and use it inversely. 
The SparseConvTranspose3d is sparse version of ConvTranspose3d. but it should't be used due to slow speed. SparseInverseConv3d should be the only option in 3d segmentation.

**Comment by traveller59** [comment]
No.
1. the SubM don't change spatial structure so you can use it in any position.
2. you can use other sparse convolutions inside the coupled convolution pair and use inverse to convert spatial structure back.

**Comment by Benzlxs** [comment]
Thanks for the reply. I will have a try on 3D point cloud semantic segmentation

**Comment by buaaJeremyduan** [comment]
So the inverse convolutions are just like upsample, is that right?

**Comment by Haerxu** [comment]
> 

Hi,

I also have this question (SparseInverseConv3d doesn't have any learnbale parameters?). Did you figure out the answer?
