### ISSUE TITLE
The difference between "SparseConvTranspose2d" and "SparseInverseConv2d"

### ISSUE THREAD

**Issue by shuluoshu** [traveller59/spconv#61]
@traveller59 
Hi, I want to know the The difference between "SparseConvTranspose2d" and "SparseInverseConv2d", do they the same and which corresponds to the original deconv in dense CNN ?

**Comment by wangguojun2018** [comment]
> @traveller59
> Hi, I want to know the The difference between "SparseConvTranspose2d" and "SparseInverseConv2d", do they the same and which corresponds to the original deconv in dense CNN ?

Ｉalso have same problem, do you know it
