### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Yochengliu** [traveller59/spconv#622]
Environment:
cumm-118 & spconv-cu118
mmdetection3.0 & pytorch2.0
Ubuntu 7.5.0-3ubuntu1~18.04

Voxel setting:
max_voxels=[120000, 160000]

Memory info:
training - 16G/24G，stable， no out of memory.

Bug frequency:
seems accidental, offen happen in epoch 1~8, sometimes at training stage, sometimes at validating stage.

Bug info:
Traceback (most recent call last):
  File "/home/miniconda3/envs/mmdet3_torch2/lib/python3.9/site-packages/spconv/pytorch/conv.py", line 385, in _conv_forward         
    res = ops.get_indice_pairs_implicit_gemm(                                                                                    
  File "/home/lyc/miniconda3/envs/mmdet3_torch2/lib/python3.9/site-packages/spconv/pytorch/ops.py", line 550, in get_indice_pairs_impli$
it_gemm                                                                                                                                 
    SpconvOps.sort_1d_by_key_allocator(pair_mask_tv[j],                                                                                 
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

Something done:
1. Guess something wrong in spare_tensor_size & kernel & padding setting. Try to modify them a few times, but no effect.
2. Guess setting too many voxels (200000), leading to some num in spconv greater than INT32. Reduce the num to 160000, no effect. BTW, the official voxel num of the used model is set to 160000 and they can get right training. 

Any problem, suggestion?

**Comment by FindDefinition** [comment]
i need a minimal reproduce script to debug this kind of problem. please provide the script and data.

**Comment by Yochengliu** [comment]
Cannot find/reproduce this bug regularly in short time, it happens accidentally. I just go to use minkowski engine. Thx anyway.

Best.
