### ISSUE TITLE
error when run python setup.py bdist_wheel

### ISSUE THREAD

**Issue by swordzxz** [traveller59/spconv#64]
hello，
When I run  python setup.py bdist_wheel, this error occurs,
How can I solve it? 
I look forward to hearing from you.

zxz@omnisky:~/project/second.pytorch/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/zxz/anaconda3/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/zxz/project/second.pytorch/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.0.176
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.0
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda-9.0/include, library: /usr/local/cuda-9.0/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1;6.1;6.1;6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zxz/project/second.pytorch/spconv/build/temp.linux-x86_64-3.6
[ 14%] Built target spconv_nms
[ 35%] Built target spconv_utils
make[2]: *** No rule to make target '/usr/local/cuda-9.0/lib64/libcudnn.so', needed by 'src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o'.  Stop.
CMakeFiles/Makefile2:108: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/zxz/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/zxz/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/zxz/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/zxz/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zxz/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
    self.run_command('build')
  File "/home/zxz/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zxz/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/zxz/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/zxz/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/zxz/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/zxz/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by McDifference** [comment]
I have the same problem with cuda-10.0: " *** No rule to make target '/usr/local/cuda-10.0/lib64/libcudnn.so', needed by 'src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o'. Stop."
Have got any solution? Thanks.
@traveller59

**Comment by McDifference** [comment]
I have solved the problem by reinstalling cuDNN. I previously installed cuDNN from a Tar file, this time I deleted all the cuDNN related files and reinstalled from Debian files. Installation guide refers to 2.3.2 on https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-linux.

Spconv successfully compiled and installed on:
Ubuntu 18.04
Python 3.6.8
gcc 7.4.0
cmake 3.15.2
Nvidia GTX 1080
cuda 10.0
cuDNN 7.6.2
pytorch 1.1.0

**Comment by AhmedMagdyHendawy** [comment]
Same problem but I tried your solution @McDifference but it did not solve it.

**Comment by ll594282475** [comment]
> Same problem but I tried your solution @McDifference but it did not solve it.

did you sloved your problem? I'm upset about this issue for a long time

**Comment by McDifference** [comment]
> > Same problem but I tried your solution @McDifference but it did not solve it.
> 
> did you sloved your problem? I'm upset about this issue for a long time

The problem seems to be the wrong path or wrong name of the related .so file.
I moved to new PC and setup the whole environment again a few days ago. I installed CUDA and cuDNN both from Debian files. All work fine.
