### ISSUE TITLE
FindCUDA says CUDA version is (usually determined by nvcc), but the CUDA   headers say the version is 10.1

### ISSUE THREAD

**Issue by ven1234** [traveller59/spconv#65]
I have installed CUDA 9.2. i stopped it to get update 10.1 itself. i have tried deep learning other programs. All are working fine Although when i try to run `python setup.py bdist_wheel` i get following errors. Do i need to change CMakeList.txt to overcome this error. Thank you

`Found CUDA: /usr/local/cuda-9.2 (found suitable version "9.2", minimum required is "7.0") 
-- Caffe2: CUDA detected: 9.2.148
-- Caffe2: CUDA nvcc is: /usr/local/cuda-9.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-9.2
-- Caffe2: Header version is: 10.1
CMake Error at /home/ven/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:59 (message):
  FindCUDA says CUDA version is (usually determined by nvcc), but the CUDA
  headers say the version is 10.1.  This often occurs when you set both
  CUDA_HOME and CUDA_NVCC_EXECUTABLE to non-standard locations, without also
  setting PATH to point to the correct nvcc.  Perhaps, try re-running this
  command again with PATH=/usr/local/cuda-9.2/bin:$PATH.  See above log
  messages for more diagnostics, and see
  https://github.com/pytorch/pytorch/issues/8092 for more details.
Call Stack (most recent call first):
  /home/ven/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/ven/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
  CMakeLists.txt:20 (find_package)
`

**Comment by tsbiosky** [comment]
Hi I have the same problem ,how did you solve that ? bro

**Comment by ChaiBapchya** [comment]
Got similar error. Any workaround? @ven1234

**Comment by abhishek-t-naive** [comment]
@tsbiosky @ChaiBapchya @ven1234 Were you able to figure this out? I have no clue what is going wrong and have tried setting all sorts of PATH variables. Would appreciate the help

**Comment by mhudnell** [comment]
I was able to resolve this by unsetting `CUDA_HOME`, and letting it default to `/usr/local/cuda`

**Comment by ahip88** [comment]
> I was able to resolve this by unsetting `CUDA_HOME`, and letting it default to `/usr/local/cuda`

Did this cause any issues down the line?
