### ISSUE TITLE
ERROR: spconv-1.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by ven1234** [traveller59/spconv#67]
I have cuda 10.1 with python 3.6 installed using conda. I could built python setup.py bdist_wheel on system. I tried to install spconv-1.1-cp36-cp36m-linux_x86_64.whl inside the dst directory using pip install spconv-1.1-cp36-cp36m-linux_x86_64.whl it fails. Any idea ? Thank you. 

`(pytorch1) ven@ven:~/workspace/second.pytorch/spconv$ cd dist/
(pytorch1) ven@ven:~/workspace/second.pytorch/spconv/dist$ pip install spconv-1.1-cp36-cp36m-linux_x86_64.whl 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ERROR: spconv-1.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
(pytorch1) ven@ven:~/workspace/second.pytorch/spconv/dist$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168
`

**Comment by hly92711** [comment]
Hello, I met the same issue, have you solved it?

**Comment by hellowangqian** [comment]
I had the same issue. Upgrading pip solved it.

**Comment by arxidinakbar** [comment]
```
(spconv) omnisky@omnisky:~/aixiding/spconv/dist$ pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: spconv-1.2.1-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
```

Hi, all. I've met the same issue as yours and tried with upgrading pip, still, problem remain. could anyone drop some hint?
thank you!

**Comment by sainisanjay** [comment]
@arxidinakbar Same error..did you able to solve?

**Comment by arxidinakbar** [comment]
@sainisanjay  I did found where the problem is, it seems caused by wrong python version where linked to the pip. (you could check it out with command: pipi -V).
So, i was working on changing the python version which linked to the pip. Would update comment if problem solved successfully.

**Comment by arxidinakbar** [comment]
@sainisanjay  Hi, I've solved the issue with slightly different command lines. try with:
`python -m pip install spconv-1.2.1-cp37-cp37m-linux_x86_64.whl`
