### ISSUE TITLE
nvcc fatal   : Unknown option 'Wall'

### ISSUE THREAD

**Issue by hellodhd** [traveller59/spconv#69]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/usr/local/lib/python3.6/dist-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.6.0  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Autodetected CUDA architecture(s):  6.1
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/spconv/build/temp.linux-x86_64-3.6
[  9%] Built target spconv_nms
[ 19%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 19%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 23%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 28%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
nvcc fatal   : Unknown option 'Wall'
src/cuhash/CMakeFiles/cuhash.dir/build.make:62: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] Error 1
nvcc fatal   : Unknown option 'Wall'
make[2]: *** Waiting for unfinished jobs....
src/cuhash/CMakeFiles/cuhash.dir/build.make:88: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] Error 1
[ 38%] Built target spconv_utils
In file included from /home/spconv/include/cuhash/hash_table.h:22:0,
                 from /home/spconv/src/cuhash/hash_table.cpp:17:
/home/spconv/include/cuhash/hash_functions.h: In function ‘unsigned int cuhash::stash_hash_function(uint2, unsigned int)’:
/home/spconv/include/cuhash/hash_functions.h:89:35: warning: suggest parentheses around arithmetic in operand of ‘^’ [-Wparentheses]
   return (stash_constants.x ^ key + stash_constants.y) % kStashSize;
                               ~~~~^~~~~~~~~~~~~~~~~~~
CMakeFiles/Makefile2:120: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/all' failed
make[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by Tartisan** [comment]
Same problem. Have you saved it ?

**Comment by Kemo-Huang** [comment]
Just comment the two lines of "INTERFACE_COMPILE_OPTIONS" in **Caffe2Targets.cmake** file of pytorch package

**Comment by BalajiGobinathan** [comment]
Hi @Kemo-Huang,
I have two questions

1.Could you kindly let me know where the file is in which we have to change.

I Am using google colab.

The CUDA Version 10.1.243
Pytorch - 1.5.0+cu101
0.6.0+cu101


2. Even if the build is successful, while running the train.py , I get the following error:

File "/content/content/second.pytorch/spconv/ops.py", line 93, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
ValueError: /content/spconv/include/spconv/spconv_ops.h 132
false assert faild. unknown device type

It would be of great help if you could give an answer to the above..

Thanks
Balaji Gobinathan

**Comment by Kemo-Huang** [comment]
@BalajiGobinathan 
This issue is also addressed in README.md. It occurs when torch version >= 1.4

If you are using linux, you can simply type ```locate Caffe2Targets.cmake``` in terminal to see the location of the file. For instance, the location could be "~/anaconda3/pkgs/pytorch-1.5.0-py3.7_cuda10.1.243_cudnn7.6.3_0/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Targets.cmake" in your machine. Edit the file for the pytorch version you will use.

There are two lines ```INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-missing-field-initializers;-Wno-write-strings;-Wno-unknown-pragmas;-Wno-missing-braces;-fopenmp"``` in the file. Search for them and comment out those two lines.

**Comment by CrocodileFly** [comment]
@Kemo-Huang Thank you! It works !

**Comment by MrCrazyCrab** [comment]
@Kemo-Huang  i can only find one line in the Caffe2Targets.cmake, and i comment it. But i still got the problem, how can i solve it ?

**Comment by realshijy** [comment]
@Kemo-Huang Thank you! It works finally!

**Comment by tornadomeet** [comment]
> @Kemo-Huang i can only find one line in the Caffe2Targets.cmake, and i comment it. But i still got the problem, how can i solve it ?
commnet another line:
```INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-missing-field-initializers;-Wno-write-strings;-Wno-unknown-pragmas;-Wno-missing-braces"```

**Comment by crayonsea** [comment]
> @Kemo-Huang i can only find one line in the Caffe2Targets.cmake, and i comment it. But i still got the problem, how can i solve it ?

 comment out those two lines: 
- `INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-missing-field-initializers;-Wno-write-strings;-Wno-unknown-pragmas;-Wno-missing-braces;-fopenmp"`
- `INTERFACE_COMPILE_OPTIONS "\$<TARGET_PROPERTY:torch_cuda,INTERFACE_COMPILE_OPTIONS>`

**Comment by shanjiayao** [comment]
> > @Kemo-Huang i can only find one line in the Caffe2Targets.cmake, and i comment it. But i still got the problem, how can i solve it ?
> 
> comment out those two lines:
> 
> * `INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-missing-field-initializers;-Wno-write-strings;-Wno-unknown-pragmas;-Wno-missing-braces;-fopenmp"`
> * `INTERFACE_COMPILE_OPTIONS "\$<TARGET_PROPERTY:torch_cuda,INTERFACE_COMPILE_OPTIONS>`

comment out those two lines solved my problem, thanks!

**Comment by deavn2236** [comment]
> > > @Kemo-Huang i can only find one line in the Caffe2Targets.cmake, and i comment it. But i still got the problem, how can i solve it ?
> > 
> > 
> > comment out those two lines:
> > 
> > * `INTERFACE_COMPILE_OPTIONS "-Wall;-Wextra;-Wno-unused-parameter;-Wno-missing-field-initializers;-Wno-write-strings;-Wno-unknown-pragmas;-Wno-missing-braces;-fopenmp"`
> > * `INTERFACE_COMPILE_OPTIONS "\$<TARGET_PROPERTY:torch_cuda,INTERFACE_COMPILE_OPTIONS>`
> 
> comment out those two lines solved my problem, thanks!

hello ,where is “INTERFACE_COMPILE_OPTIONS "$<TARGET_PROPERTY:torch_cuda,INTERFACE_COMPILE_OPTIONS>” I can't find it in Caffe2Targets.cmake
