### ISSUE TITLE
How to get FLOPs when using spconv 2.x?

### ISSUE THREAD

**Issue by Aiuan** [traveller59/spconv#697]
The homepage states "since spconv 2.x doesn't depend on pytorch binary (never in future), it's impossible to support torch.jit/libtorch inference." Therefore, jit cannot be used for statistical analysis of FLOPs. What should I do if I want to obtain FLOPs?

**Comment by barrydoooit** [comment]
Have you tried [thop](https://github.com/Lyken17/pytorch-OpCounter)? I could remember that it worked in one of my previous case.

**Comment by Aiuan** [comment]
Thank for your kind suggestion. I try [https://github.com/Lyken17/pytorch-OpCounter](thop) and find it works.
