### ISSUE TITLE
ERROR: No matching distribution found for spconv-cu114

### ISSUE THREAD

**Issue by barrydoooit** [traveller59/spconv#698]
Hi there. I'm on Jetson AGX Orin with L4T R35.4.1. While I'm playing with the container from [dustynv](https://hub.docker.com/r/dustynv/pytorch/tags?page=&page_size=&ordering=&name=r35.4.1) and with Python 3.8 (pip3 24.0), pip install spconv-cu114 (as well as spconv only) always ends up like
```
ERROR: Could not find a version that satisfies the requirement spconv-cu114 (from versions: none)
ERROR: No matching distribution found for spconv-cu114
```
Any suggestions on resolving such issue?

**Comment by barrydoooit** [comment]
Just realized that this is still open. The conclusion is that building from source will solve the issue.

**Comment by KantaphatLeelakunwet** [comment]
> Just realized that this is still open. The conclusion is that building from source will solve the issue.

Hey, do you mind sharing the steps or which cumm version and spconv version you are using? I have been trying to build from two weeks but I kept getting errors.

**Comment by barrydoooit** [comment]
> > Just realized that this is still open. The conclusion is that building from source will solve the issue.
> 
> Hey, do you mind sharing the steps or which cumm version and spconv version you are using? I have been trying to build from two weeks but I kept getting errors.

@KantaphatLeelakunwet Hi there. Probably the dockerfile snippet below may help:
```
ENV TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX;Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing;8.6"
ENV CPATH=/usr/local/cuda/include:$CPATH
ENV LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda/bin:$PATH
ENV CUDA_HOME=/usr/local/cuda

WORKDIR /builds
RUN git clone https://github.com/FindDefinition/cumm.git
WORKDIR /builds/cumm
RUN git checkout v0.3.7
ENV CUMM_CUDA_ARCH_LIST="8.7"
ENV CUMM_CUDA_VERSION="11.4"
RUN pip install -e . 
RUN python -c "import cumm"

WORKDIR /builds
RUN git clone https://github.com/traveller59/spconv.git
WORKDIR /builds/spconv
RUN git checkout v2.2.6
RUN sed -i 's/, "cumm>=0.3.7"//g' pyproject.toml
RUN pip install -e . 
RUN python -c "import spconv"
```

**Comment by rengithubs** [comment]
> > > Just realized that this is still open. The conclusion is that building from source will solve the issue.
> > 
> > 
> > Hey, do you mind sharing the steps or which cumm version and spconv version you are using? I have been trying to build from two weeks but I kept getting errors.
> 
> [@KantaphatLeelakunwet](https://github.com/KantaphatLeelakunwet) Hi there. Probably the dockerfile snippet below may help:
> 
> ```
> ENV TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX;Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing;8.6"
> ENV CPATH=/usr/local/cuda/include:$CPATH
> ENV LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
> ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
> ENV PATH=/usr/local/cuda/bin:$PATH
> ENV CUDA_HOME=/usr/local/cuda
> 
> WORKDIR /builds
> RUN git clone https://github.com/FindDefinition/cumm.git
> WORKDIR /builds/cumm
> RUN git checkout v0.3.7
> ENV CUMM_CUDA_ARCH_LIST="8.7"
> ENV CUMM_CUDA_VERSION="11.4"
> RUN pip install -e . 
> RUN python -c "import cumm"
> 
> WORKDIR /builds
> RUN git clone https://github.com/traveller59/spconv.git
> WORKDIR /builds/spconv
> RUN git checkout v2.2.6
> RUN sed -i 's/, "cumm>=0.3.7"//g' pyproject.toml
> RUN pip install -e . 
> RUN python -c "import spconv"
> ```

Hello, do you have this kind of error when using spconv? I installed the same version of cumm and spconv as you gave the command

![Image](https://github.com/user-attachments/assets/3c898544-b06b-45ad-9fb8-e490872ff1ac)

**Comment by barrydoooit** [comment]
> Hello, do you have this kind of error when using spconv? I installed the same version of cumm and spconv as you gave the command
> 
> ![Image](https://github.com/user-attachments/assets/3c898544-b06b-45ad-9fb8-e490872ff1ac)

Hi @rengithubs. Sad that I haven't been into such cases where additional compilations are triggered in my python (mostly within pytorch) code.

Probably others may help if details of your tta test script can be revealed. Wish u good luck.
