### ISSUE TITLE
cumm and spconv versions do not match

### ISSUE THREAD

**Issue by BlackNightdd** [traveller59/spconv#726]
I encountered the following error while installing spconv.
ERROR: Could not find a version that satisfies the requirement cumm<0.5.0,>=0.4.5 (from spconv) (from versions: 0.1.0, 0.5.0, 0.5.1, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3)
ERROR: No matching distribution found for cumm<0.5.0,>=0.4.5
I don't know how to solve it?

**Comment by mk2510** [comment]
Hi, you need to remove the dependencies also in setup.py in line 44

**Comment by BlackNightdd** [comment]
> 嗨，您还需要在第 44 行的 setup.py 中删除依赖项

Solved, thank you！

**Comment by DOUDOUZXL** [comment]
I encountered the following error while installing spconv.
ERROR: Could not find a version that satisfies the requirement cumm<0.8.0,>=0.7.11 (from spconv) (from versions: 0.1.0, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.5, 0.2.6, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.4.0, 0.4.1, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.5.0, 0.5.1, 0.5.3)
ERROR: No matching distribution found for cumm<0.8.0,>=0.7.11

I don't know how to solve it?

**Comment by WilliamFlinchbaugh** [comment]
> ERROR: Could not find a version that satisfies the requirement cumm<0.8.0,>=0.7.11 (from spconv)

Also getting this issue.

I'm on a clean conda environment with Python 3.9, I've just installed cumm 0.7.12 from source using `pip install -e .` and tried install spconv from source using `pip install -e .` as instructed.

Anyone figured this out yet? May need to open a new issue.

**Comment by WilliamFlinchbaugh** [comment]
Posting for anyone else having this problem who might be on Orin, just missed these important sections in the README:

> For NVIDIA Embedded Platforms, you need to specify cuda arch before build: export CUMM_CUDA_ARCH_LIST="7.2" for xavier, export CUMM_CUDA_ARCH_LIST="6.2" for TX2, export CUMM_CUDA_ARCH_LIST="8.7" for orin.

> You need to remove cumm in requires section in pyproject.toml after install editable cumm and before install spconv due to pyproject limit (can't find editable installed cumm).

> You need to ensure pip list | grep spconv and pip list | grep cumm show nothing before install editable spconv/cumm.

I ran 
`export CUMM_CUDA_ARCH_LIST="8.7"` since I'm on Orin, then removed "cumm>=0.7.11" from requirements in pyproject.toml and it installed no problem.
