### ISSUE TITLE
All outputs contain nan values when using SparseConv3d and SubMConv3d

### ISSUE THREAD

**Issue by YunjieYu** [traveller59/spconv#73]
Hi Yan. Very nice work! Congratulations!

Recently, I have made a minor modification for your codes (e.g. middle.py).

However, I find that all the output results for a certain conv module (including one SpConv3d and three SubMConv3d) are nan.

For example:
```
middle_out3 = self.middle_conv3(middle_out2)

middle_out2.features[10:12]
tensor([[0.1458, 0.0000, 0.0000, 0.0000, 0.0837, 0.0000, 0.0000, 0.0006, 0.0000,
         0.0207, 0.0162, 0.0864, 0.0149, 0.0312, 0.0618, 0.0000, 0.0000, 0.0027,
         0.1244, 0.0275, 0.0000, 0.0000, 0.0462, 0.0043, 0.0008, 0.0156, 0.0468,
         0.0000, 0.0257, 0.0000, 0.0597, 0.0871],
        [0.0000, 0.0000, 0.1629, 0.2219, 0.0000, 0.0071, 0.0000, 0.0006, 0.0573,
         0.0513, 0.0656, 0.0820, 0.0000, 0.1057, 0.0183, 0.0147, 0.0000, 0.0061,
         0.0000, 0.0482, 0.0000, 0.1762, 0.0000, 0.0048, 0.0000, 0.1373, 0.0000,
         0.0018, 0.0720, 0.2367, 0.0000, 0.0000]], device='cuda:0',
       grad_fn=<SliceBackward>)

middle_out3.features[10:12]
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
       device='cuda:0', grad_fn=<SliceBackward>)
```

I have checked the conv weights in middle_conv3, and felt that there seems to be no abnormality for the weights. I do not know why this problem happens. 

Please help. Thanks in advance!

Below is my code:
```
class SpMiddleFHD(nn.Module):
    def __init__(self,
                 output_shape,
                 use_norm=True,
                 num_input_features=128,
                 num_filters_down1=[64],
                 num_filters_down2=[64, 64],
                 name='SpMiddleFHD'):
        super(SpMiddleFHD, self).__init__()
        self.name = name
        if use_norm:
            BatchNorm2d = change_default_args(eps=1e-3, momentum=0.01)(nn.BatchNorm2d)
            BatchNorm1d = change_default_args(eps=1e-3, momentum=0.01)(nn.BatchNorm1d)
            Conv2d = change_default_args(bias=False)(nn.Conv2d)
            SpConv3d = change_default_args(bias=False)(spconv.SparseConv3d)
            SparseInverseConv3d = change_default_args(bias=False)(spconv.SparseInverseConv3d)
            SubMConv3d = change_default_args(bias=False)(spconv.SubMConv3d)
            ConvTranspose2d = change_default_args(bias=False)(nn.ConvTranspose2d)
        else:
            BatchNorm2d = Empty
            BatchNorm1d = Empty
            Conv2d = change_default_args(bias=True)(nn.Conv2d)
            SpConv3d = change_default_args(bias=True)(spconv.SparseConv3d)
            SparseInverseConv3d = change_default_args(bias=True)(spconv.SparseInverseConv3d)
            SubMConv3d = change_default_args(bias=True)(spconv.SubMConv3d)
            ConvTranspose2d = change_default_args(bias=True)(nn.ConvTranspose2d)
        sparse_shape = np.array(output_shape[1:4]) + [1, 0, 0]
        # sparse_shape[0] = 11
        print(sparse_shape)
        self.sparse_shape = sparse_shape
        self.voxel_output_shape = output_shape
        # input: # [1600, 1200, 41]

        self.middle_conv1 = spconv.SparseSequential(
            SubMConv3d(num_input_features, 16, 3, indice_key="subm0"),
            BatchNorm1d(16),
            nn.ReLU(),
            SubMConv3d(16, 16, 3, indice_key="subm0"),
            BatchNorm1d(16),
            nn.ReLU())

        self.middle_conv2 = spconv.SparseSequential(
            SpConv3d(16, 32, 3, 2, padding=1, indice_key="subm1"),  # [1600, 1200, 41] -> [800, 600, 21]
            BatchNorm1d(32),
            nn.ReLU(),
            SubMConv3d(32, 32, 3, indice_key="subm1"),
            BatchNorm1d(32),
            nn.ReLU(),
            SubMConv3d(32, 32, 3, indice_key="subm1"),
            BatchNorm1d(32),
            nn.ReLU())

        self.middle_conv3 = spconv.SparseSequential(
            SpConv3d(32, 64, 3, 2, padding=1, indice_key="subm2"),  # [800, 600, 21] -> [400, 300, 11]
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm2"),
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm2"),
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm2"),
            BatchNorm1d(64),
            nn.ReLU())

        self.middle_conv4 = spconv.SparseSequential(
            SpConv3d(64, 64, 3, 2, padding=[0, 1, 1], indice_key="subm3"),  # [400, 300, 11] -> [200, 150, 5]
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm3"),
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm3"),
            BatchNorm1d(64),
            nn.ReLU(),
            SubMConv3d(64, 64, 3, indice_key="subm3"),
            BatchNorm1d(64),
            nn.ReLU())

        self.middle_conv5 = spconv.SparseSequential(
            SpConv3d(64, 64, (3, 1, 1),
                     (2, 1, 1)),  # [200, 150, 5] -> [200, 150, 2]
            BatchNorm1d(64),
            nn.ReLU())

        # self.middle_deconv2 = spconv.SparseSequential(
        #     SparseInverseConv3d(32, 16, 3, indice_key="subm1"),
        #     BatchNorm1d(16),
        #     nn.ReLU())
        #
        # self.middle_deconv3 = spconv.SparseSequential(
        #     SparseInverseConv3d(64, 32, 3, indice_key="subm2"),
        #     BatchNorm1d(32),
        #     nn.ReLU())
        #
        # self.middle_deconv4 = spconv.SparseSequential(
        #     SparseInverseConv3d(64, 64, 3, indice_key="subm3"),
        #     BatchNorm1d(64),
        #     nn.ReLU())

        # self.block_1 = SUBlock(16, 32, indice_key="subm0")
        # self.block_2 = SUBlock(32, 64, indice_key="subm1")
        # self.block_3 = SUBlock(64, 64, indice_key="subm2")
        # self.block_4 = SUBlock(64, indice_key="subm3")

        self.max_batch_size = 6
        # self.grid = torch.full([self.max_batch_size, *sparse_shape], -1, dtype=torch.int32).cuda()

    def forward(self, voxel_features, coors, batch_size):
        # coors[:, 1] += 1
        coors = coors.int() # unlike torch, this library only accept int coordinates.
        ret = spconv.SparseConvTensor(voxel_features, coors, self.sparse_shape, batch_size)
        # t = time.time()
        # torch.cuda.synchronize()

        middle_out1 = self.middle_conv1(ret)
        middle_out2 = self.middle_conv2(middle_out1)
        middle_out3 = self.middle_conv3(middle_out2)
        middle_out4 = self.middle_conv4(middle_out3)
        middle_out = self.middle_conv5(middle_out4)

        # upsampling_out = self.middle_deconv4(middle_out4)
        # upsampling_out = self.middle_deconv3(upsampling_out)
        # upsampling_out = self.middle_deconv2(upsampling_out)

        pdb.set_trace()

        # upsampling_out = self.block_4(middle_out4)
        # upsampling_out = self.block_3(middle_out3, upsampling_out)
        # upsampling_out = self.block_2(middle_out2, upsampling_out)
        # upsampling_out = self.block_1(middle_out1, upsampling_out)

        # torch.cuda.synchronize()
        # print("spconv forward time", time.time() - t)
        middle_out = middle_out.dense()

        N, C, D, H, W = middle_out.shape
        middle_out = middle_out.view(N, C * D, H, W)
        return middle_out, upsampling_out
```

**Comment by YunjieYu** [comment]
I have another question:
For a sparse tensor, it has a indice_dict. The indice_dict includes both the indices before conv and the indices after conv and spatial_shape, right?  what are the remaining variables?

For example:
```
middle_out3.indice_dict
{'subm0': (tensor([[  0,  13, 664, 225],
        [  0,  13, 549, 222],
        [  0,  19, 725, 756],
        ...,
        [  0,  13, 696, 262],
        [  0,  11, 388, 101],
        [  0,  14, 480, 207]], device='cuda:0', dtype=torch.int32), tensor([[  0,  13, 664, 225],
        [  0,  13, 549, 222],
        [  0,  19, 725, 756],
        ...,
        [  0,  13, 696, 262],
        [  0,  11, 388, 101],
        [  0,  14, 480, 207]], device='cuda:0', dtype=torch.int32), tensor([[[13681,  6673,  6814,  ...,    -1,    -1,    -1],
         [13304,  7323, 13716,  ...,    -1,    -1,    -1]],

        [[13419, 13426, 13561,  ...,    -1,    -1,    -1],
         [ 5586,  5855,  8369,  ...,    -1,    -1,    -1]],

        [[ 2252,  3015,  3029,  ...,    -1,    -1,    -1],
         [ 3817,  3649,  8655,  ...,    -1,    -1,    -1]],

        ...,

        [[ 7641,  6383, 11705,  ...,    -1,    -1,    -1],
         [13107,  3526,  3738,  ...,    -1,    -1,    -1]],

        [[11683, 11708,  2121,  ...,    -1,    -1,    -1],
         [13780, 12678,  7028,  ...,    -1,    -1,    -1]],

        [[10700,  6383,  3225,  ...,    -1,    -1,    -1],
         [ 6338,   505,  5247,  ...,    -1,    -1,    -1]]], device='cuda:0',
       dtype=torch.int32), tensor([  233,   428,   581,   382,   629,   503,   596,   460,   275,  3618,
         3264,  1376,  2202, 14230,  2202,  1376,  3264,  3618,   275,   460,
          596,   503,   629,   382,   581,   428,   233], device='cuda:0',
       dtype=torch.int32), array([  41, 1600, 1408])), 'subm1': (tensor([[  0,   2, 190, 262],
        [  0,   2, 192, 246],
        [  0,   2, 193, 246],
        ...,
        [  0,  20, 348, 273],
        [  0,  20, 349, 270],
        [  0,  20, 349, 271]], device='cuda:0', dtype=torch.int32), tensor([[  0,  13, 664, 225],
        [  0,  13, 549, 222],
        [  0,  19, 725, 756],
        ...,
        [  0,  13, 696, 262],
        [  0,  11, 388, 101],
        [  0,  14, 480, 207]], device='cuda:0', dtype=torch.int32), tensor([[[10409,  3272, 10416,  ...,    -1,    -1,    -1],
         [16423, 14657, 25096,  ...,    -1,    -1,    -1]],

        [[ 4482,  4507,  4486,  ...,    -1,    -1,    -1],
         [17776, 15310, 24301,  ...,    -1,    -1,    -1]],

        [[ 3272,  3286,  3293,  ...,    -1,    -1,    -1],
         [14656, 16946, 13725,  ...,    -1,    -1,    -1]],

        ...,

        [[10691, 10714, 10715,  ...,    -1,    -1,    -1],
         [ 3710,  3667,  4977,  ...,    -1,    -1,    -1]],

        [[ 4482,  4507,  4486,  ...,    -1,    -1,    -1],
         [ 7018,  5289, 23452,  ...,    -1,    -1,    -1]],

        [[10691, 10714, 10715,  ...,    -1,    -1,    -1],
         [ 3709,  3666,  4976,  ...,    -1,    -1,    -1]]], device='cuda:0',
       dtype=torch.int32), tensor([2355, 2308, 2355, 2328, 2307, 2328, 2355, 2308, 2355, 1217, 1307, 1217,
        1196, 1212, 1196, 1217, 1307, 1217, 2355, 2308, 2355, 2328, 2307, 2328,
        2355, 2308, 2355], device='cuda:0', dtype=torch.int32), array([  41, 1600, 1408])), 
'subm2': ......
}
```
What do third and fourth variable represent? And, What are the implications of them?

**Comment by zxczrx123** [comment]
> Hi Yan. Very nice work! Congratulations!
> 
> Recently, I have made a minor modification for your codes (e.g. middle.py).
> 
> However, I find that all the output results for a certain conv module (including one SpConv3d and three SubMConv3d) are nan.
> 
> For example:
> 
> ```
> middle_out3 = self.middle_conv3(middle_out2)
> 
> middle_out2.features[10:12]
> tensor([[0.1458, 0.0000, 0.0000, 0.0000, 0.0837, 0.0000, 0.0000, 0.0006, 0.0000,
>          0.0207, 0.0162, 0.0864, 0.0149, 0.0312, 0.0618, 0.0000, 0.0000, 0.0027,
>          0.1244, 0.0275, 0.0000, 0.0000, 0.0462, 0.0043, 0.0008, 0.0156, 0.0468,
>          0.0000, 0.0257, 0.0000, 0.0597, 0.0871],
>         [0.0000, 0.0000, 0.1629, 0.2219, 0.0000, 0.0071, 0.0000, 0.0006, 0.0573,
>          0.0513, 0.0656, 0.0820, 0.0000, 0.1057, 0.0183, 0.0147, 0.0000, 0.0061,
>          0.0000, 0.0482, 0.0000, 0.1762, 0.0000, 0.0048, 0.0000, 0.1373, 0.0000,
>          0.0018, 0.0720, 0.2367, 0.0000, 0.0000]], device='cuda:0',
>        grad_fn=<SliceBackward>)
> 
> middle_out3.features[10:12]
> tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
>         [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
>        device='cuda:0', grad_fn=<SliceBackward>)
> ```
> 
> I have checked the conv weights in middle_conv3, and felt that there seems to be no abnormality for the weights. I do not know why this problem happens.
> 
> Please help. Thanks in advance!
> 
> Below is my code:
> 
> ```
> class SpMiddleFHD(nn.Module):
>     def __init__(self,
>                  output_shape,
>                  use_norm=True,
>                  num_input_features=128,
>                  num_filters_down1=[64],
>                  num_filters_down2=[64, 64],
>                  name='SpMiddleFHD'):
>         super(SpMiddleFHD, self).__init__()
>         self.name = name
>         if use_norm:
>             BatchNorm2d = change_default_args(eps=1e-3, momentum=0.01)(nn.BatchNorm2d)
>             BatchNorm1d = change_default_args(eps=1e-3, momentum=0.01)(nn.BatchNorm1d)
>             Conv2d = change_default_args(bias=False)(nn.Conv2d)
>             SpConv3d = change_default_args(bias=False)(spconv.SparseConv3d)
>             SparseInverseConv3d = change_default_args(bias=False)(spconv.SparseInverseConv3d)
>             SubMConv3d = change_default_args(bias=False)(spconv.SubMConv3d)
>             ConvTranspose2d = change_default_args(bias=False)(nn.ConvTranspose2d)
>         else:
>             BatchNorm2d = Empty
>             BatchNorm1d = Empty
>             Conv2d = change_default_args(bias=True)(nn.Conv2d)
>             SpConv3d = change_default_args(bias=True)(spconv.SparseConv3d)
>             SparseInverseConv3d = change_default_args(bias=True)(spconv.SparseInverseConv3d)
>             SubMConv3d = change_default_args(bias=True)(spconv.SubMConv3d)
>             ConvTranspose2d = change_default_args(bias=True)(nn.ConvTranspose2d)
>         sparse_shape = np.array(output_shape[1:4]) + [1, 0, 0]
>         # sparse_shape[0] = 11
>         print(sparse_shape)
>         self.sparse_shape = sparse_shape
>         self.voxel_output_shape = output_shape
>         # input: # [1600, 1200, 41]
> 
>         self.middle_conv1 = spconv.SparseSequential(
>             SubMConv3d(num_input_features, 16, 3, indice_key="subm0"),
>             BatchNorm1d(16),
>             nn.ReLU(),
>             SubMConv3d(16, 16, 3, indice_key="subm0"),
>             BatchNorm1d(16),
>             nn.ReLU())
> 
>         self.middle_conv2 = spconv.SparseSequential(
>             SpConv3d(16, 32, 3, 2, padding=1, indice_key="subm1"),  # [1600, 1200, 41] -> [800, 600, 21]
>             BatchNorm1d(32),
>             nn.ReLU(),
>             SubMConv3d(32, 32, 3, indice_key="subm1"),
>             BatchNorm1d(32),
>             nn.ReLU(),
>             SubMConv3d(32, 32, 3, indice_key="subm1"),
>             BatchNorm1d(32),
>             nn.ReLU())
> 
>         self.middle_conv3 = spconv.SparseSequential(
>             SpConv3d(32, 64, 3, 2, padding=1, indice_key="subm2"),  # [800, 600, 21] -> [400, 300, 11]
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm2"),
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm2"),
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm2"),
>             BatchNorm1d(64),
>             nn.ReLU())
> 
>         self.middle_conv4 = spconv.SparseSequential(
>             SpConv3d(64, 64, 3, 2, padding=[0, 1, 1], indice_key="subm3"),  # [400, 300, 11] -> [200, 150, 5]
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm3"),
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm3"),
>             BatchNorm1d(64),
>             nn.ReLU(),
>             SubMConv3d(64, 64, 3, indice_key="subm3"),
>             BatchNorm1d(64),
>             nn.ReLU())
> 
>         self.middle_conv5 = spconv.SparseSequential(
>             SpConv3d(64, 64, (3, 1, 1),
>                      (2, 1, 1)),  # [200, 150, 5] -> [200, 150, 2]
>             BatchNorm1d(64),
>             nn.ReLU())
> 
>         # self.middle_deconv2 = spconv.SparseSequential(
>         #     SparseInverseConv3d(32, 16, 3, indice_key="subm1"),
>         #     BatchNorm1d(16),
>         #     nn.ReLU())
>         #
>         # self.middle_deconv3 = spconv.SparseSequential(
>         #     SparseInverseConv3d(64, 32, 3, indice_key="subm2"),
>         #     BatchNorm1d(32),
>         #     nn.ReLU())
>         #
>         # self.middle_deconv4 = spconv.SparseSequential(
>         #     SparseInverseConv3d(64, 64, 3, indice_key="subm3"),
>         #     BatchNorm1d(64),
>         #     nn.ReLU())
> 
>         # self.block_1 = SUBlock(16, 32, indice_key="subm0")
>         # self.block_2 = SUBlock(32, 64, indice_key="subm1")
>         # self.block_3 = SUBlock(64, 64, indice_key="subm2")
>         # self.block_4 = SUBlock(64, indice_key="subm3")
> 
>         self.max_batch_size = 6
>         # self.grid = torch.full([self.max_batch_size, *sparse_shape], -1, dtype=torch.int32).cuda()
> 
>     def forward(self, voxel_features, coors, batch_size):
>         # coors[:, 1] += 1
>         coors = coors.int() # unlike torch, this library only accept int coordinates.
>         ret = spconv.SparseConvTensor(voxel_features, coors, self.sparse_shape, batch_size)
>         # t = time.time()
>         # torch.cuda.synchronize()
> 
>         middle_out1 = self.middle_conv1(ret)
>         middle_out2 = self.middle_conv2(middle_out1)
>         middle_out3 = self.middle_conv3(middle_out2)
>         middle_out4 = self.middle_conv4(middle_out3)
>         middle_out = self.middle_conv5(middle_out4)
> 
>         # upsampling_out = self.middle_deconv4(middle_out4)
>         # upsampling_out = self.middle_deconv3(upsampling_out)
>         # upsampling_out = self.middle_deconv2(upsampling_out)
> 
>         pdb.set_trace()
> 
>         # upsampling_out = self.block_4(middle_out4)
>         # upsampling_out = self.block_3(middle_out3, upsampling_out)
>         # upsampling_out = self.block_2(middle_out2, upsampling_out)
>         # upsampling_out = self.block_1(middle_out1, upsampling_out)
> 
>         # torch.cuda.synchronize()
>         # print("spconv forward time", time.time() - t)
>         middle_out = middle_out.dense()
> 
>         N, C, D, H, W = middle_out.shape
>         middle_out = middle_out.view(N, C * D, H, W)
>         return middle_out, upsampling_out
> ```

I have encountered the same error,have you solved it?

**Comment by zxczrx123** [comment]
@YunjieYu I have encountered the same NAN error,have you solved it？

**Comment by ErenBalatkan** [comment]
Same issue, randomly getting NaN values. They can happen frequently or they can happen once in like 150 epochs.

**Comment by lx709** [comment]
Same issue. have you guys figured out the problem.

**Comment by vivi0604** [comment]
Changing version from "spconv 1.2" to "pytorch1.1, spconv1.1" resolves the issue.

**Comment by Cknex** [comment]
After replacing the normal convolution with the sparse convolution (a model including both spconv, subm conv and inverse conv), I also often meet the NAN problem.

**Comment by twn29004** [comment]
> 
I have the same problem. Have do you sloved it ?

**Comment by neriya333** [comment]
had the same but with nn.ConvTranspose2d:
self.tconv1 = nn.ConvTranspose2d(100, 512, kernel_size=4, stride=1)
return nan-s suddenly.
