### ISSUE TITLE
libtorch/include/c10/util/typeid.h:345:32: error:  

### ISSUE THREAD

**Issue by yhw-yhw** [traveller59/spconv#8]
libtorch/include/c10/util/typeid.h:345:32: error: explicitly defaulted function ‘constexpr caffe2::TypeMeta& caffe2::TypeMeta::operator=(const caffe2::TypeMeta&)’ cannot
be declared as constexpr because the implicit declaration is not constexpr:                                          
   AT_CPP14_CONSTEXPR TypeMeta& operator=(const TypeMeta& src) noexcept =
                                ^

**Comment by traveller59** [comment]
I google this problem and it tell me this is a gcc bug, what's your gcc version? This repo is tested in gcc 5.4/16.04, gcc 5.5/18.04

**Comment by yhw-yhw** [comment]
yes, I've fix this by install gcc .5.4. Thanks a lot.
