### ISSUE TITLE
Recommended reminds to Put in README.md

### ISSUE THREAD

**Issue by DonaldRR** [traveller59/spconv#80]
My CUDA and CUDNN are not installed under /usr/local, thus CMake could not find my CUDA and CUDNN and gave me errors. In such cases, I recommend authors to put:

export CUDA_PATH=/path/to/cuda/root
export CUDACXX=/path/to/cuda/nvcc/
export CUDNN_LIBRARY=/path/to/cudnn/library/file
export CUDNN_INCLUDE_DIR=/path/to/cudnn/include/dir

for Users to check if they have all above environment variables assigned

**Comment by HenryJunW** [comment]
Thanks for your advice, which is very helpful for the cuda and cudnn not installing in the default location. However, I still got the error about the path of the cuda when make target `/usr/local/cuda/lib64/libculibos.a', needed by the 'src/spconv/CMakeFiles/spconv.dir/cmake_device_link.o'. Do you know how to fix this? thanks

**Comment by HenryJunW** [comment]
Solved by another thread. Thanks.

**Comment by MeyLavie** [comment]
Hi @HenryJunW can you please share how did you solve this?
