### ISSUE TITLE
Difference between spconv.SparseConv3d and spconv.SubMConv3d

### ISSUE THREAD

**Issue by turboxin** [traveller59/spconv#81]
hi @traveller59 , thanks for opensourcing this excellent work! I wonder what's the difference between spconv.SparseConv3d and spconv.SubMConv3d, is spconv.SparseConv3d corresponding to sparse convolution(SC) and spconv.SubMConv3d corresponding to valid sparse convolution(VSC)   
in facebook's paper “Submanifold Sparse Convolutional Networks”？
Thank you in advance!

**Comment by sidml** [comment]
@turboxin Did you find out the difference ?
