### ISSUE TITLE
run setup.py error

### ISSUE THREAD

**Issue by z393** [traveller59/spconv#85]
bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/nextcar/anaconda3/envs/second/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/nextcar/spconv-master/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Autodetected CUDA architecture(s):  6.1
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nextcar/spconv-master/build/temp.linux-x86_64-3.7
[  9%] Built target spconv_nms
[ 14%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 19%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
[ 28%] Built target spconv_utils
In file included from /usr/include/c++/4.9/type_traits:35:0,
                 from /home/nextcar/spconv-master/include/tensorview/tensorview.h:24,
                 from /home/nextcar/spconv-master/include/cuhash/definitions.h:23,
                 from /home/nextcar/spconv-master/include/cuhash/debugging.h:21,
                 from /home/nextcar/spconv-master/src/cuhash/hash_table.cu:18:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.9/type_traits:35:0,
                 from /home/nextcar/spconv-master/include/tensorview/tensorview.h:24,
                 from /home/nextcar/spconv-master/include/cuhash/definitions.h:23,
                 from /home/nextcar/spconv-master/include/cuhash/hash_table.h:21,
                 from /home/nextcar/spconv-master/src/cuhash/hash_functions.cu:1:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
src/cuhash/CMakeFiles/cuhash.dir/build.make:88: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/cuhash/CMakeFiles/cuhash.dir/build.make:62: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o' failed
make[2]: *** [src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/cuhash/CMakeFiles/cuhash.dir/all' failed
make[1]: *** [src/cuhash/CMakeFiles/cuhash.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/nextcar/anaconda3/envs/second/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

I met this error, but i don't know how to deal it. Can u help me ? thanks

**Comment by pyaf** [comment]
did you solve this issue? what is your `cmake` version?

**Comment by Eralien** [comment]
Same  problem here. I replace cmake with custom cmake 3.15 executable path.

**Comment by yusanshi** [comment]
I met the same problem. Looks like I forgot to configure boost headers. I solved this problem by `apt install libboost-all-dev`. Hope helpful to you. :)
