### ISSUE TITLE
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils'

### ISSUE THREAD

**Issue by lihua213** [traveller59/spconv#89]
ImportError: cannot import name 'non_max_suppression' from 'spconv.utils'
However, we can import other successfully:
>>> from spconv.spconv_utils import non_max_suppression_cpu
>>> from spconv.spconv_utils import points_to_voxel_3d_np
>>> from spconv.spconv_utils import rotate_non_max_suppression_cpu
>>> from spconv.spconv_utils import rbbox_iou
>>> from spconv.spconv_utils import rbbox_intersection

**Comment by yzhou377** [comment]
Did you find any solutions?

**Comment by Baser-Bai** [comment]
> ImportError: cannot import name 'non_max_suppression' from 'spconv.utils' However, we can import other successfully:
> 
> > > > from spconv.spconv_utils import non_max_suppression_cpu
> > > > from spconv.spconv_utils import points_to_voxel_3d_np
> > > > from spconv.spconv_utils import rotate_non_max_suppression_cpu
> > > > from spconv.spconv_utils import rbbox_iou
> > > > from spconv.spconv_utils import rbbox_intersection

did your solve it? I have the same question

**Comment by Baser-Bai** [comment]
> Did you find any solutions?
did your solve it? I have the same question

**Comment by frimpz** [comment]
did your solve it? I have the same question
