### ISSUE TITLE
A Bug of VoxelGenerator

### ISSUE THREAD

**Issue by ghost** [traveller59/spconv#93]
Thanks for sharing your code, they are very helpful!! While I encountered a problem when using VoxelGenerator, can you @traveller59 take some time to look at it? Thanks a lot. 

My code is as follows:

```
import spconv
import numpy as np

voxel_generator = spconv.utils.VoxelGenerator(
        voxel_size=[0.2, 0.2, 0.4],
        point_cloud_range= [-1, -40, -3, 70.4, 40, 10],
        max_num_points=35,
        max_voxels=20000,
        full_mean=False)
anchor_center = np.array([0.3, 0.3, 0.3],dtype=np.float32).reshape(-1, 3)
voxels, coors, num_points_per_voxel = voxel_generator.generate(anchor_center)
print(voxels.shape)
```

and the result is: 

`array([], shape=(0, 35, 3), dtype=float32)`

which means the given point cannot be put in any voxel. While the point is in the valid area, so what's the problem? are the paremeters set wrongly?
And I tried the same code with VoxelGenerator in SECOND V1.0 and it returned right result.

**Comment by turboxin** [comment]
Same error as @qiushi223. 
It's really weird because I feed continuous frames into VoxelGenerator, the point clouds are very similar because the ego-car is very slow, it would generate empty results in some of the frames, but non-empty in some other frames.

**Comment by russellyq** [comment]
Hi @turboxin,

I meet the same problem. Any solutions ?
