### ISSUE TITLE
when run python setup.py bdist_wheel

### ISSUE THREAD

**Issue by taku80125** [traveller59/spconv#96]
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/iso/anaconda3/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/takuma/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.0
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found torch: /home/iso/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch.so  
-- Autodetected CUDA architecture(s):  6.1
-- Found PythonInterp: /home/iso/anaconda3/bin/python3.6 (found suitable version "3.6.9", minimum required is "3.6") 
-- Found PythonLibs: /home/iso/anaconda3/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /takuma/spconv/build/temp.linux-x86_64-3.6
make: Warning: File 'Makefile' has modification time 64 s in the future
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 105 s in the future
make[2]: Warning: File 'src/cuhash/CMakeFiles/cuhash.dir/flags.make' has modification time 70 s in the future
make[2]: Warning: File 'src/utils/CMakeFiles/spconv_nms.dir/flags.make' has modification time 95 s in the future
Scanning dependencies of target cuhash
Scanning dependencies of target spconv_nms
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'src/utils/CMakeFiles/spconv_nms.dir/flags.make' has modification time 93 s in the future
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'src/cuhash/CMakeFiles/cuhash.dir/flags.make' has modification time 67 s in the future
[  9%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 18%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cu.o
[ 18%] Building CUDA object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cu.o
[ 18%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_table.cpp.o
[ 22%] Building CXX object src/cuhash/CMakeFiles/cuhash.dir/hash_functions.cpp.o
[ 27%] Linking CUDA static library libspconv_nms.a
[ 31%] Linking CUDA device code CMakeFiles/cuhash.dir/cmake_device_link.o
[ 36%] Linking CXX static library libcuhash.a
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 36%] Built target spconv_nms
make[2]: Warning: File 'src/utils/CMakeFiles/spconv_utils.dir/flags.make' has modification time 61 s in the future
Scanning dependencies of target spconv_utils
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'src/utils/CMakeFiles/spconv_utils.dir/flags.make' has modification time 60 s in the future
[ 40%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 40%] Built target cuhash
make[2]: Warning: File 'src/spconv/CMakeFiles/spconv.dir/flags.make' has modification time 51 s in the future
Scanning dependencies of target spconv
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'src/spconv/CMakeFiles/spconv.dir/flags.make' has modification time 50 s in the future
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 54%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /takuma/spconv/include/torch_utils.h:20:0,
                 from /takuma/spconv/include/spconv/pool_ops.h:20,
                 from /takuma/spconv/src/spconv/all.cc:15:
/home/iso/anaconda3/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:22: fatal error: cusparse.h: No such file or directory
compilation terminated.
src/spconv/CMakeFiles/spconv.dir/build.make:62: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /takuma/spconv/include/torch_utils.h:20:0,
                 from /takuma/spconv/include/spconv/spconv_ops.h:21,
                 from /takuma/spconv/src/spconv/indice.cc:17:
/home/iso/anaconda3/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:22: fatal error: cusparse.h: No such file or directory
compilation terminated.
src/spconv/CMakeFiles/spconv.dir/build.make:75: recipe for target 'src/spconv/CMakeFiles/spconv.dir/indice.cc.o' failed
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/indice.cc.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'src/spconv/CMakeFiles/spconv.dir/all' failed
make[1]: *** [src/spconv/CMakeFiles/spconv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 59%] Linking CUDA device code CMakeFiles/spconv_utils.dir/cmake_device_link.o
[ 63%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 63%] Built target spconv_utils
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/iso/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/iso/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/iso/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/iso/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/iso/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/home/iso/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/iso/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/iso/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/iso/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/iso/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 83, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/iso/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

How do I solve this errors? I dont have any solutions now...

**Comment by hau-zy** [comment]
anyone solved this yet?

**Comment by ZHANGWeishuang** [comment]
I've encountered exactly the same problem when trying to use spconv on Ubuntu 18.04. It turns to me actually a problem in NVIDIA cudnn. Could you please check this cudnn install guide [https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html) and see if you can pass 2.4? 
It take me some effort to fix a "cuda_runtime_api error" mentioned here [https://github.com/onnx/onnx-tensorrt/issues/97](https://github.com/onnx/onnx-tensorrt/issues/97) to run it in the end.
