### ISSUE TITLE
please update your documentation on typo in package name libboostall-dev

### ISSUE THREAD

**Issue by dev-mtshikomba** [traveller59/spconv#97]
The command below does not work: 
`sudo apt-get install libboostall-dev`

Update to this, take note of the typo:
`sudo apt-get install libboost-all-dev`

**Comment by chenxyyy** [comment]
@traveller59 Thank you. This question has been bothering me for a long time.

**Comment by chenxyyy** [comment]
Thank you. This question has been bothering me for a long time.    @TangeniThePyGuru
